2021-07-01 22:02:16,474 - INFO - ServiceNode - [EtcdSupport.py:549]: we have create ServiceRegister
2021-07-01 22:02:16,475 - INFO - ServiceNode - [EtcdSupport.py:552]: we have create ServiceFinder
2021-07-01 22:02:16,484 - INFO - TcpServer - [TcpServer.py:200]: Server on ('127.0.0.1', 9203)
2021-07-01 22:02:19,483 - INFO - ServiceFinder - [EtcdSupport.py:382]: _init_info, now_url: http://127.0.0.1:2379/v2/keys?recursive=true
2021-07-01 22:02:19,488 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> lobby_gate: ('127.0.0.1', 9203)
2021-07-01 22:02:19,491 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> lobby_server: ('127.0.0.1', 10002)
2021-07-01 22:02:19,492 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> dispatcher_service: ('127.0.0.1', 9101)
2021-07-01 22:02:19,493 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> dispatcher_service: ('127.0.0.1', 9102)
2021-07-01 22:02:19,495 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> dispatcher_service: ('127.0.0.1', 9100)
2021-07-01 22:02:19,496 - INFO - ServiceFinder - [EtcdSupport.py:302]: init service info from etcd success, will going to watch, at etcd index -> 398
2021-07-01 22:02:20,879 - INFO - TcpServer - [TcpServer.py:186]: ('127.0.0.1', 5476) is connected !!!!
2021-07-01 22:02:20,924 - WARNING - ProxyLobbyRpcHandler - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RpcHandler.py:216"]: self._try_connect_times=1, id(self._conn)=2627104151104
2021-07-01 22:02:39,861 - INFO - ServiceFinder - [EtcdSupport.py:464]: recv watch expire, info--> dispatcher_2: ('127.0.0.1', 9102) - [417]
2021-07-01 22:02:40,362 - INFO - ServiceFinder - [EtcdSupport.py:464]: recv watch expire, info--> dispatcher_0: ('127.0.0.1', 9100) - [418]
2021-07-01 22:06:17,291 - WARNING - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:168"]: peer addr: ('127.0.0.1', 5476), close_reason='connection is closed by error: [WinError 64] The specified network name is no longer available'
