2021-06-26 21:42:46,167 - DEBUG - ServerEntity.LoadReporter - [ServerEntity.py:23]: __init__ create entity LoadReporter with id 60d72ed68d26451066861cce mem_id=2492053179984
2021-06-26 21:42:46,168 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d72ed68d26451066861cce 
2021-06-26 21:42:46,197 - DEBUG - ServiceNode - [EtcdSupport.py:533]: we have create ServiceFinder
2021-06-26 21:42:46,217 - DEBUG - ServiceFinder - [EtcdSupport.py:352]: _init_info, now_url: http://127.0.0.1:2379/v2/keys?recursive=true
2021-06-26 21:42:46,231 - DEBUG - ServiceRegister - [EtcdSupport.py:155]: _do_regist: now_url: http://127.0.0.1:2379/v2/keys/services/lobby_gate/127.0.0.1|9201
2021-06-26 21:42:46,255 - DEBUG - TcpServer - [TcpServer.py:194]: Server on ('127.0.0.1', 9201)
2021-06-26 21:42:46,305 - DEBUG - ServiceFinder - [EtcdSupport.py:323]: add service node info--> dispatcher_service: ('127.0.0.1', 9100)
2021-06-26 21:42:46,313 - DEBUG - ServiceFinder - [EtcdSupport.py:323]: add service node info--> lobby_server: ('127.0.0.1', 10001)
2021-06-26 21:42:46,320 - DEBUG - ServiceFinder - [EtcdSupport.py:277]: init service info from etcd success, will going to watch, at etcd index -> 6
2021-06-26 21:42:46,345 - DEBUG - ServiceRegister - [EtcdSupport.py:163]: regist service : lobby_gate success, {"action":"set","node":{"key":"/services/lobby_gate/127.0.0.1|9201","value":"","expiration":"2021-06-26T13:45:46.2896744Z","ttl":180,"modifiedIndex":7,"createdIndex":7}}

2021-06-26 21:42:46,370 - DEBUG - ServiceFinder - [EtcdSupport.py:422]: recv watch set service node info--> lobby_gate: ('127.0.0.1', 9201) - [7]
2021-06-26 21:43:46,411 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 7 -> 7
2021-06-26 21:44:28,385 - DEBUG - ServiceRegister - [EtcdSupport.py:196]: outside, time.time()=1624715068.3743458, refresh service lobby_gate, now_url: http://127.0.0.1:2379/v2/keys/services/lobby_gate/127.0.0.1|9201
2021-06-26 21:44:28,472 - DEBUG - ServiceRegister - [EtcdSupport.py:214]: time.time()=1624715068.4647326, refresh service success: lobby_gate: {"action":"set","node":{"key":"/services/lobby_gate/127.0.0.1|9201","value":"","expiration":"2021-06-26T13:47:28.4512364Z","ttl":180,"modifiedIndex":10,"createdIndex":10},"prevNode":{"key":"/services/lobby_gate/127.0.0.1|9201","value":"","expiration":"2021-06-26T13:45:46.2896744Z","ttl":78,"modifiedIndex":7,"createdIndex":7}}
, now_url: http://127.0.0.1:2379/v2/keys/services/lobby_gate/127.0.0.1|9201
2021-06-26 21:44:48,433 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 7 -> 8
2021-06-26 21:45:54,479 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 8 -> 10
2021-06-26 21:46:10,502 - DEBUG - ServiceRegister - [EtcdSupport.py:196]: outside, time.time()=1624715170.4936864, refresh service lobby_gate, now_url: http://127.0.0.1:2379/v2/keys/services/lobby_gate/127.0.0.1|9201
2021-06-26 21:46:10,554 - DEBUG - ServiceRegister - [EtcdSupport.py:214]: time.time()=1624715170.5446792, refresh service success: lobby_gate: {"action":"set","node":{"key":"/services/lobby_gate/127.0.0.1|9201","value":"","expiration":"2021-06-26T13:49:10.5371977Z","ttl":180,"modifiedIndex":12,"createdIndex":12},"prevNode":{"key":"/services/lobby_gate/127.0.0.1|9201","value":"","expiration":"2021-06-26T13:47:28.4512364Z","ttl":78,"modifiedIndex":10,"createdIndex":10}}
, now_url: http://127.0.0.1:2379/v2/keys/services/lobby_gate/127.0.0.1|9201
2021-06-26 21:47:01,516 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 10 -> 11
2021-06-26 21:47:52,593 - DEBUG - ServiceRegister - [EtcdSupport.py:196]: outside, time.time()=1624715272.585205, refresh service lobby_gate, now_url: http://127.0.0.1:2379/v2/keys/services/lobby_gate/127.0.0.1|9201
2021-06-26 21:47:52,642 - DEBUG - ServiceRegister - [EtcdSupport.py:214]: time.time()=1624715272.6344495, refresh service success: lobby_gate: {"action":"set","node":{"key":"/services/lobby_gate/127.0.0.1|9201","value":"","expiration":"2021-06-26T13:50:52.6249223Z","ttl":180,"modifiedIndex":15,"createdIndex":15},"prevNode":{"key":"/services/lobby_gate/127.0.0.1|9201","value":"","expiration":"2021-06-26T13:49:10.5371977Z","ttl":78,"modifiedIndex":12,"createdIndex":12}}
, now_url: http://127.0.0.1:2379/v2/keys/services/lobby_gate/127.0.0.1|9201
2021-06-26 21:48:10,546 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 11 -> 14
2021-06-26 21:49:19,580 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 14 -> 16
2021-06-26 21:49:40,673 - DEBUG - ServiceRegister - [EtcdSupport.py:196]: outside, time.time()=1624715380.6623266, refresh service lobby_gate, now_url: http://127.0.0.1:2379/v2/keys/services/lobby_gate/127.0.0.1|9201
2021-06-26 21:49:40,728 - DEBUG - ServiceRegister - [EtcdSupport.py:214]: time.time()=1624715380.7178257, refresh service success: lobby_gate: {"action":"set","node":{"key":"/services/lobby_gate/127.0.0.1|9201","value":"","expiration":"2021-06-26T13:52:40.7091151Z","ttl":180,"modifiedIndex":18,"createdIndex":18},"prevNode":{"key":"/services/lobby_gate/127.0.0.1|9201","value":"","expiration":"2021-06-26T13:50:52.6249223Z","ttl":72,"modifiedIndex":15,"createdIndex":15}}
, now_url: http://127.0.0.1:2379/v2/keys/services/lobby_gate/127.0.0.1|9201
2021-06-26 21:50:25,614 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 16 -> 17
2021-06-26 21:51:26,742 - DEBUG - ServiceRegister - [EtcdSupport.py:196]: outside, time.time()=1624715486.7384448, refresh service lobby_gate, now_url: http://127.0.0.1:2379/v2/keys/services/lobby_gate/127.0.0.1|9201
2021-06-26 21:51:26,765 - DEBUG - ServiceRegister - [EtcdSupport.py:214]: time.time()=1624715486.7628582, refresh service success: lobby_gate: {"action":"set","node":{"key":"/services/lobby_gate/127.0.0.1|9201","value":"","expiration":"2021-06-26T13:54:26.7593633Z","ttl":180,"modifiedIndex":21,"createdIndex":21},"prevNode":{"key":"/services/lobby_gate/127.0.0.1|9201","value":"","expiration":"2021-06-26T13:52:40.7091151Z","ttl":74,"modifiedIndex":18,"createdIndex":18}}
, now_url: http://127.0.0.1:2379/v2/keys/services/lobby_gate/127.0.0.1|9201
2021-06-26 21:51:34,640 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 17 -> 20
2021-06-26 21:52:35,653 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 20 -> 22
2021-06-26 21:53:10,797 - DEBUG - ServiceRegister - [EtcdSupport.py:196]: outside, time.time()=1624715590.7886117, refresh service lobby_gate, now_url: http://127.0.0.1:2379/v2/keys/services/lobby_gate/127.0.0.1|9201
2021-06-26 21:53:10,843 - DEBUG - ServiceRegister - [EtcdSupport.py:214]: time.time()=1624715590.834905, refresh service success: lobby_gate: {"action":"set","node":{"key":"/services/lobby_gate/127.0.0.1|9201","value":"","expiration":"2021-06-26T13:56:10.828151Z","ttl":180,"modifiedIndex":24,"createdIndex":24},"prevNode":{"key":"/services/lobby_gate/127.0.0.1|9201","value":"","expiration":"2021-06-26T13:54:26.7593633Z","ttl":76,"modifiedIndex":21,"createdIndex":21}}
, now_url: http://127.0.0.1:2379/v2/keys/services/lobby_gate/127.0.0.1|9201
2021-06-26 21:53:42,693 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 22 -> 23
2021-06-26 21:54:50,729 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 23 -> 26
2021-06-26 21:54:53,858 - DEBUG - ServiceRegister - [EtcdSupport.py:196]: outside, time.time()=1624715693.848747, refresh service lobby_gate, now_url: http://127.0.0.1:2379/v2/keys/services/lobby_gate/127.0.0.1|9201
2021-06-26 21:54:53,913 - DEBUG - ServiceRegister - [EtcdSupport.py:214]: time.time()=1624715693.904257, refresh service success: lobby_gate: {"action":"set","node":{"key":"/services/lobby_gate/127.0.0.1|9201","value":"","expiration":"2021-06-26T13:57:53.8952185Z","ttl":180,"modifiedIndex":27,"createdIndex":27},"prevNode":{"key":"/services/lobby_gate/127.0.0.1|9201","value":"","expiration":"2021-06-26T13:56:10.828151Z","ttl":77,"modifiedIndex":24,"createdIndex":24}}
, now_url: http://127.0.0.1:2379/v2/keys/services/lobby_gate/127.0.0.1|9201
2021-06-26 21:55:59,754 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 26 -> 26
2021-06-26 21:56:35,939 - DEBUG - ServiceRegister - [EtcdSupport.py:196]: outside, time.time()=1624715795.9268496, refresh service lobby_gate, now_url: http://127.0.0.1:2379/v2/keys/services/lobby_gate/127.0.0.1|9201
2021-06-26 21:56:36,005 - DEBUG - ServiceRegister - [EtcdSupport.py:214]: time.time()=1624715795.994589, refresh service success: lobby_gate: {"action":"set","node":{"key":"/services/lobby_gate/127.0.0.1|9201","value":"","expiration":"2021-06-26T13:59:35.9827642Z","ttl":180,"modifiedIndex":30,"createdIndex":30},"prevNode":{"key":"/services/lobby_gate/127.0.0.1|9201","value":"","expiration":"2021-06-26T13:57:53.8952185Z","ttl":78,"modifiedIndex":27,"createdIndex":27}}
, now_url: http://127.0.0.1:2379/v2/keys/services/lobby_gate/127.0.0.1|9201
2021-06-26 21:57:00,790 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 26 -> 29
2021-06-26 21:58:04,821 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 29 -> 31
2021-06-26 21:58:20,051 - DEBUG - ServiceRegister - [EtcdSupport.py:196]: outside, time.time()=1624715900.0410757, refresh service lobby_gate, now_url: http://127.0.0.1:2379/v2/keys/services/lobby_gate/127.0.0.1|9201
2021-06-26 21:58:20,113 - DEBUG - ServiceRegister - [EtcdSupport.py:214]: time.time()=1624715900.102578, refresh service success: lobby_gate: {"action":"set","node":{"key":"/services/lobby_gate/127.0.0.1|9201","value":"","expiration":"2021-06-26T14:01:20.0927279Z","ttl":180,"modifiedIndex":33,"createdIndex":33},"prevNode":{"key":"/services/lobby_gate/127.0.0.1|9201","value":"","expiration":"2021-06-26T13:59:35.9827642Z","ttl":76,"modifiedIndex":30,"createdIndex":30}}
, now_url: http://127.0.0.1:2379/v2/keys/services/lobby_gate/127.0.0.1|9201
2021-06-26 21:59:12,853 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 31 -> 32
2021-06-26 22:00:06,136 - DEBUG - ServiceRegister - [EtcdSupport.py:196]: outside, time.time()=1624716006.131222, refresh service lobby_gate, now_url: http://127.0.0.1:2379/v2/keys/services/lobby_gate/127.0.0.1|9201
2021-06-26 22:00:06,157 - DEBUG - ServiceRegister - [EtcdSupport.py:214]: time.time()=1624716006.1544974, refresh service success: lobby_gate: {"action":"set","node":{"key":"/services/lobby_gate/127.0.0.1|9201","value":"","expiration":"2021-06-26T14:03:06.1520593Z","ttl":180,"modifiedIndex":36,"createdIndex":36},"prevNode":{"key":"/services/lobby_gate/127.0.0.1|9201","value":"","expiration":"2021-06-26T14:01:20.0927279Z","ttl":74,"modifiedIndex":33,"createdIndex":33}}
, now_url: http://127.0.0.1:2379/v2/keys/services/lobby_gate/127.0.0.1|9201
2021-06-26 22:00:12,883 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 32 -> 35
2021-06-26 22:01:16,924 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 35 -> 36
2021-06-26 22:01:55,176 - DEBUG - ServiceRegister - [EtcdSupport.py:196]: outside, time.time()=1624716115.1674085, refresh service lobby_gate, now_url: http://127.0.0.1:2379/v2/keys/services/lobby_gate/127.0.0.1|9201
2021-06-26 22:01:55,234 - DEBUG - ServiceRegister - [EtcdSupport.py:214]: time.time()=1624716115.2247987, refresh service success: lobby_gate: {"action":"set","node":{"key":"/services/lobby_gate/127.0.0.1|9201","value":"","expiration":"2021-06-26T14:04:55.216745Z","ttl":180,"modifiedIndex":39,"createdIndex":39},"prevNode":{"key":"/services/lobby_gate/127.0.0.1|9201","value":"","expiration":"2021-06-26T14:03:06.1520593Z","ttl":71,"modifiedIndex":36,"createdIndex":36}}
, now_url: http://127.0.0.1:2379/v2/keys/services/lobby_gate/127.0.0.1|9201
2021-06-26 22:02:23,957 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 36 -> 38
2021-06-26 22:02:52,786 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 7487) is connected !!!!
2021-06-26 22:02:52,838 - CRITICAL - ProxyCliRpcHandler - [ProxyRpcHandler.py:110]: on_traceback, type:<class 'NameError'>, value:name 'ServerEntity' is not defined, traceback:<class 'NameError'>
name 'ServerEntity' is not defined
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\ProxyRpcHandler.py", line 87, in handle_rpc
    locals={'self': <ProxyRpcHandler.ProxyCliRpcHandler object at 0x000002443A1A88E0>, 'rpc_msg': b'\x96\x01\x01\xa6Avatar\xb5puppet_entity_message\x92\xd9!CompAvatarTest.puppet_chat_to_ppt\x81\xa7content\xb2puppet_chat_to_ppt\x80', 'dispatcher_json_conf_path': '../bin/win/conf/dispatcher_service.json', 'conf_file': <_io.TextIOWrapper name='../bin/win/conf/dispatcher_service.json' mode='r' encoding='cp936'>, 'dispatcher_json_conf': {'$MACRO$': {'LOBBY_SRV_IP': '127.0.0.1', 'ETCD_IP': '127.0.0.1', 'DISPATCHER_IP': '127.0.0.1', '$LOBBY_GATE_IP': '127.0.0.1'}, 'etcd_servers': [{'ip': '127.0.0.1', 'port': 2379}], 'log_path': '../bin/win/log/', 'lobby_entity_root': 'lobby_entity', 'battle_entity_root': 'battle_entity', 'server_entity_root': 'server_entity', 'component_root': 'component', 'dispatcher_0': {'ip': '127.0.0.1', 'port': 9100}, 'dispatcher_1': {'ip': '127.0.0.1', 'port': 9101}, 'dispatcher_2': {'ip': '127.0.0.1', 'port': 9102}, 'dispatcher_3': {'ip': '127.0.0.1', 'port': 9103}, 'dispatcher_4': {'ip': '127.0.0.1', '...
2021-06-26 22:02:58,814 - CRITICAL - ProxyCliRpcHandler - [ProxyRpcHandler.py:110]: on_traceback, type:<class 'NameError'>, value:name 'ServerEntity' is not defined, traceback:<class 'NameError'>
name 'ServerEntity' is not defined
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\ProxyRpcHandler.py", line 87, in handle_rpc
    locals={'self': <ProxyRpcHandler.ProxyCliRpcHandler object at 0x000002443A1A88E0>, 'rpc_msg': b'\x91\x03', 'dispatcher_json_conf_path': '../bin/win/conf/dispatcher_service.json', 'conf_file': <_io.TextIOWrapper name='../bin/win/conf/dispatcher_service.json' mode='r' encoding='cp936'>, 'dispatcher_json_conf': {'$MACRO$': {'LOBBY_SRV_IP': '127.0.0.1', 'ETCD_IP': '127.0.0.1', 'DISPATCHER_IP': '127.0.0.1', '$LOBBY_GATE_IP': '127.0.0.1'}, 'etcd_servers': [{'ip': '127.0.0.1', 'port': 2379}], 'log_path': '../bin/win/log/', 'lobby_entity_root': 'lobby_entity', 'battle_entity_root': 'battle_entity', 'server_entity_root': 'server_entity', 'component_root': 'component', 'dispatcher_0': {'ip': '127.0.0.1', 'port': 9100}, 'dispatcher_1': {'ip': '127.0.0.1', 'port': 9101}, 'dispatcher_2': {'ip': '127.0.0.1', 'port': 9102}, 'dispatcher_3': {'ip': '127.0.0.1', 'port': 9103}, 'dispatcher_4': {'ip': '127.0.0.1', 'port': 9104}, 'dispatcher_5': {'ip': '127.0.0.1', 'port': 9105}}, 'rand_dispatcher_service_addr': ('127.0.0.1', 9100), '_s...
2021-06-26 22:03:00,784 - WARNING - TcpConn - [TcpConn.py:173]: heartbeat timeout
2021-06-26 22:03:11,610 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 7496) is connected !!!!
2021-06-26 22:03:11,643 - CRITICAL - ProxyCliRpcHandler - [ProxyRpcHandler.py:110]: on_traceback, type:<class 'NameError'>, value:name 'ServerEntity' is not defined, traceback:<class 'NameError'>
name 'ServerEntity' is not defined
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\ProxyRpcHandler.py", line 87, in handle_rpc
    locals={'self': <ProxyRpcHandler.ProxyCliRpcHandler object at 0x0000024438DE0940>, 'rpc_msg': b'\x96\x01\x02\xa6Avatar\xb5puppet_entity_message\x92\xd9!CompAvatarTest.puppet_chat_to_ppt\x81\xa7content\xb2puppet_chat_to_ppt\x80', 'dispatcher_json_conf_path': '../bin/win/conf/dispatcher_service.json', 'conf_file': <_io.TextIOWrapper name='../bin/win/conf/dispatcher_service.json' mode='r' encoding='cp936'>, 'dispatcher_json_conf': {'$MACRO$': {'LOBBY_SRV_IP': '127.0.0.1', 'ETCD_IP': '127.0.0.1', 'DISPATCHER_IP': '127.0.0.1', '$LOBBY_GATE_IP': '127.0.0.1'}, 'etcd_servers': [{'ip': '127.0.0.1', 'port': 2379}], 'log_path': '../bin/win/log/', 'lobby_entity_root': 'lobby_entity', 'battle_entity_root': 'battle_entity', 'server_entity_root': 'server_entity', 'component_root': 'component', 'dispatcher_0': {'ip': '127.0.0.1', 'port': 9100}, 'dispatcher_1': {'ip': '127.0.0.1', 'port': 9101}, 'dispatcher_2': {'ip': '127.0.0.1', 'port': 9102}, 'dispatcher_3': {'ip': '127.0.0.1', 'port': 9103}, 'dispatcher_4': {'ip': '127.0.0.1', '...
2021-06-26 22:03:17,647 - CRITICAL - ProxyCliRpcHandler - [ProxyRpcHandler.py:110]: on_traceback, type:<class 'NameError'>, value:name 'ServerEntity' is not defined, traceback:<class 'NameError'>
name 'ServerEntity' is not defined
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\ProxyRpcHandler.py", line 87, in handle_rpc
    locals={'self': <ProxyRpcHandler.ProxyCliRpcHandler object at 0x0000024438DE0940>, 'rpc_msg': b'\x91\x03', 'dispatcher_json_conf_path': '../bin/win/conf/dispatcher_service.json', 'conf_file': <_io.TextIOWrapper name='../bin/win/conf/dispatcher_service.json' mode='r' encoding='cp936'>, 'dispatcher_json_conf': {'$MACRO$': {'LOBBY_SRV_IP': '127.0.0.1', 'ETCD_IP': '127.0.0.1', 'DISPATCHER_IP': '127.0.0.1', '$LOBBY_GATE_IP': '127.0.0.1'}, 'etcd_servers': [{'ip': '127.0.0.1', 'port': 2379}], 'log_path': '../bin/win/log/', 'lobby_entity_root': 'lobby_entity', 'battle_entity_root': 'battle_entity', 'server_entity_root': 'server_entity', 'component_root': 'component', 'dispatcher_0': {'ip': '127.0.0.1', 'port': 9100}, 'dispatcher_1': {'ip': '127.0.0.1', 'port': 9101}, 'dispatcher_2': {'ip': '127.0.0.1', 'port': 9102}, 'dispatcher_3': {'ip': '127.0.0.1', 'port': 9103}, 'dispatcher_4': {'ip': '127.0.0.1', 'port': 9104}, 'dispatcher_5': {'ip': '127.0.0.1', 'port': 9105}}, 'rand_dispatcher_service_addr': ('127.0.0.1', 9100), '_s...
2021-06-26 22:03:19,634 - WARNING - TcpConn - [TcpConn.py:173]: heartbeat timeout
2021-06-26 22:03:19,680 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 7500) is connected !!!!
2021-06-26 22:03:21,610 - CRITICAL - ProxyCliRpcHandler - [ProxyRpcHandler.py:110]: on_traceback, type:<class 'NameError'>, value:name 'ServerEntity' is not defined, traceback:<class 'NameError'>
name 'ServerEntity' is not defined
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\ProxyRpcHandler.py", line 87, in handle_rpc
    locals={'self': <ProxyRpcHandler.ProxyCliRpcHandler object at 0x000002443A1A8AC0>, 'rpc_msg': b'\x96\x01\x03\xa6Avatar\xb5puppet_entity_message\x92\xd9!CompAvatarTest.puppet_chat_to_ppt\x81\xa7content\xb2puppet_chat_to_ppt\x80', 'dispatcher_json_conf_path': '../bin/win/conf/dispatcher_service.json', 'conf_file': <_io.TextIOWrapper name='../bin/win/conf/dispatcher_service.json' mode='r' encoding='cp936'>, 'dispatcher_json_conf': {'$MACRO$': {'LOBBY_SRV_IP': '127.0.0.1', 'ETCD_IP': '127.0.0.1', 'DISPATCHER_IP': '127.0.0.1', '$LOBBY_GATE_IP': '127.0.0.1'}, 'etcd_servers': [{'ip': '127.0.0.1', 'port': 2379}], 'log_path': '../bin/win/log/', 'lobby_entity_root': 'lobby_entity', 'battle_entity_root': 'battle_entity', 'server_entity_root': 'server_entity', 'component_root': 'component', 'dispatcher_0': {'ip': '127.0.0.1', 'port': 9100}, 'dispatcher_1': {'ip': '127.0.0.1', 'port': 9101}, 'dispatcher_2': {'ip': '127.0.0.1', 'port': 9102}, 'dispatcher_3': {'ip': '127.0.0.1', 'port': 9103}, 'dispatcher_4': {'ip': '127.0.0.1', '...
2021-06-26 22:03:25,700 - CRITICAL - ProxyCliRpcHandler - [ProxyRpcHandler.py:110]: on_traceback, type:<class 'NameError'>, value:name 'ServerEntity' is not defined, traceback:<class 'NameError'>
name 'ServerEntity' is not defined
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\ProxyRpcHandler.py", line 87, in handle_rpc
    locals={'self': <ProxyRpcHandler.ProxyCliRpcHandler object at 0x000002443A1A8AC0>, 'rpc_msg': b'\x91\x03', 'dispatcher_json_conf_path': '../bin/win/conf/dispatcher_service.json', 'conf_file': <_io.TextIOWrapper name='../bin/win/conf/dispatcher_service.json' mode='r' encoding='cp936'>, 'dispatcher_json_conf': {'$MACRO$': {'LOBBY_SRV_IP': '127.0.0.1', 'ETCD_IP': '127.0.0.1', 'DISPATCHER_IP': '127.0.0.1', '$LOBBY_GATE_IP': '127.0.0.1'}, 'etcd_servers': [{'ip': '127.0.0.1', 'port': 2379}], 'log_path': '../bin/win/log/', 'lobby_entity_root': 'lobby_entity', 'battle_entity_root': 'battle_entity', 'server_entity_root': 'server_entity', 'component_root': 'component', 'dispatcher_0': {'ip': '127.0.0.1', 'port': 9100}, 'dispatcher_1': {'ip': '127.0.0.1', 'port': 9101}, 'dispatcher_2': {'ip': '127.0.0.1', 'port': 9102}, 'dispatcher_3': {'ip': '127.0.0.1', 'port': 9103}, 'dispatcher_4': {'ip': '127.0.0.1', 'port': 9104}, 'dispatcher_5': {'ip': '127.0.0.1', 'port': 9105}}, 'rand_dispatcher_service_addr': ('127.0.0.1', 9100), '_s...
2021-06-26 22:03:27,684 - WARNING - TcpConn - [TcpConn.py:173]: heartbeat timeout
2021-06-26 22:03:27,734 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 7505) is connected !!!!
2021-06-26 22:03:31,616 - CRITICAL - ProxyCliRpcHandler - [ProxyRpcHandler.py:110]: on_traceback, type:<class 'NameError'>, value:name 'ServerEntity' is not defined, traceback:<class 'NameError'>
name 'ServerEntity' is not defined
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\ProxyRpcHandler.py", line 87, in handle_rpc
    locals={'self': <ProxyRpcHandler.ProxyCliRpcHandler object at 0x000002443A1A8880>, 'rpc_msg': b'\x96\x01\x04\xa6Avatar\xb5puppet_entity_message\x92\xd9!CompAvatarTest.puppet_chat_to_ppt\x81\xa7content\xb2puppet_chat_to_ppt\x80', 'dispatcher_json_conf_path': '../bin/win/conf/dispatcher_service.json', 'conf_file': <_io.TextIOWrapper name='../bin/win/conf/dispatcher_service.json' mode='r' encoding='cp936'>, 'dispatcher_json_conf': {'$MACRO$': {'LOBBY_SRV_IP': '127.0.0.1', 'ETCD_IP': '127.0.0.1', 'DISPATCHER_IP': '127.0.0.1', '$LOBBY_GATE_IP': '127.0.0.1'}, 'etcd_servers': [{'ip': '127.0.0.1', 'port': 2379}], 'log_path': '../bin/win/log/', 'lobby_entity_root': 'lobby_entity', 'battle_entity_root': 'battle_entity', 'server_entity_root': 'server_entity', 'component_root': 'component', 'dispatcher_0': {'ip': '127.0.0.1', 'port': 9100}, 'dispatcher_1': {'ip': '127.0.0.1', 'port': 9101}, 'dispatcher_2': {'ip': '127.0.0.1', 'port': 9102}, 'dispatcher_3': {'ip': '127.0.0.1', 'port': 9103}, 'dispatcher_4': {'ip': '127.0.0.1', '...
2021-06-26 22:03:32,983 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 38 -> 40
2021-06-26 22:03:33,768 - CRITICAL - ProxyCliRpcHandler - [ProxyRpcHandler.py:110]: on_traceback, type:<class 'NameError'>, value:name 'ServerEntity' is not defined, traceback:<class 'NameError'>
name 'ServerEntity' is not defined
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\ProxyRpcHandler.py", line 87, in handle_rpc
    locals={'self': <ProxyRpcHandler.ProxyCliRpcHandler object at 0x000002443A1A8880>, 'rpc_msg': b'\x91\x03', 'dispatcher_json_conf_path': '../bin/win/conf/dispatcher_service.json', 'conf_file': <_io.TextIOWrapper name='../bin/win/conf/dispatcher_service.json' mode='r' encoding='cp936'>, 'dispatcher_json_conf': {'$MACRO$': {'LOBBY_SRV_IP': '127.0.0.1', 'ETCD_IP': '127.0.0.1', 'DISPATCHER_IP': '127.0.0.1', '$LOBBY_GATE_IP': '127.0.0.1'}, 'etcd_servers': [{'ip': '127.0.0.1', 'port': 2379}], 'log_path': '../bin/win/log/', 'lobby_entity_root': 'lobby_entity', 'battle_entity_root': 'battle_entity', 'server_entity_root': 'server_entity', 'component_root': 'component', 'dispatcher_0': {'ip': '127.0.0.1', 'port': 9100}, 'dispatcher_1': {'ip': '127.0.0.1', 'port': 9101}, 'dispatcher_2': {'ip': '127.0.0.1', 'port': 9102}, 'dispatcher_3': {'ip': '127.0.0.1', 'port': 9103}, 'dispatcher_4': {'ip': '127.0.0.1', 'port': 9104}, 'dispatcher_5': {'ip': '127.0.0.1', 'port': 9105}}, 'rand_dispatcher_service_addr': ('127.0.0.1', 9100), '_s...
2021-06-26 22:03:35,254 - DEBUG - ServiceRegister - [EtcdSupport.py:196]: outside, time.time()=1624716215.2425432, refresh service lobby_gate, now_url: http://127.0.0.1:2379/v2/keys/services/lobby_gate/127.0.0.1|9201
2021-06-26 22:03:35,300 - DEBUG - ServiceRegister - [EtcdSupport.py:214]: time.time()=1624716215.2942138, refresh service success: lobby_gate: {"action":"set","node":{"key":"/services/lobby_gate/127.0.0.1|9201","value":"","expiration":"2021-06-26T14:06:35.2879919Z","ttl":180,"modifiedIndex":42,"createdIndex":42},"prevNode":{"key":"/services/lobby_gate/127.0.0.1|9201","value":"","expiration":"2021-06-26T14:04:55.216745Z","ttl":80,"modifiedIndex":39,"createdIndex":39}}
, now_url: http://127.0.0.1:2379/v2/keys/services/lobby_gate/127.0.0.1|9201
2021-06-26 22:03:35,749 - WARNING - TcpConn - [TcpConn.py:173]: heartbeat timeout
2021-06-26 22:03:35,801 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 7511) is connected !!!!
2021-06-26 22:03:35,910 - WARNING - TcpConn - [TcpConn.py:173]: connection is closed by error: [WinError 64] The specified network name is no longer available
2021-06-26 22:04:41,024 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 40 -> 41
2021-06-26 22:05:19,321 - DEBUG - ServiceRegister - [EtcdSupport.py:196]: outside, time.time()=1624716319.3053908, refresh service lobby_gate, now_url: http://127.0.0.1:2379/v2/keys/services/lobby_gate/127.0.0.1|9201
2021-06-26 22:05:19,390 - DEBUG - ServiceRegister - [EtcdSupport.py:214]: time.time()=1624716319.3824587, refresh service success: lobby_gate: {"action":"set","node":{"key":"/services/lobby_gate/127.0.0.1|9201","value":"","expiration":"2021-06-26T14:08:19.3721168Z","ttl":180,"modifiedIndex":45,"createdIndex":45},"prevNode":{"key":"/services/lobby_gate/127.0.0.1|9201","value":"","expiration":"2021-06-26T14:06:35.2879919Z","ttl":76,"modifiedIndex":42,"createdIndex":42}}
, now_url: http://127.0.0.1:2379/v2/keys/services/lobby_gate/127.0.0.1|9201
2021-06-26 22:05:46,078 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 41 -> 44
2021-06-26 22:06:50,116 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 44 -> 46
2021-06-26 22:06:59,404 - DEBUG - ServiceRegister - [EtcdSupport.py:196]: outside, time.time()=1624716419.396331, refresh service lobby_gate, now_url: http://127.0.0.1:2379/v2/keys/services/lobby_gate/127.0.0.1|9201
2021-06-26 22:06:59,454 - DEBUG - ServiceRegister - [EtcdSupport.py:214]: time.time()=1624716419.4453516, refresh service success: lobby_gate: {"action":"set","node":{"key":"/services/lobby_gate/127.0.0.1|9201","value":"","expiration":"2021-06-26T14:09:59.4375332Z","ttl":180,"modifiedIndex":48,"createdIndex":48},"prevNode":{"key":"/services/lobby_gate/127.0.0.1|9201","value":"","expiration":"2021-06-26T14:08:19.3721168Z","ttl":80,"modifiedIndex":45,"createdIndex":45}}
, now_url: http://127.0.0.1:2379/v2/keys/services/lobby_gate/127.0.0.1|9201
2021-06-26 22:07:55,144 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 46 -> 47
2021-06-26 22:08:49,482 - DEBUG - ServiceRegister - [EtcdSupport.py:196]: outside, time.time()=1624716529.4718947, refresh service lobby_gate, now_url: http://127.0.0.1:2379/v2/keys/services/lobby_gate/127.0.0.1|9201
2021-06-26 22:08:49,543 - DEBUG - ServiceRegister - [EtcdSupport.py:214]: time.time()=1624716529.5330176, refresh service success: lobby_gate: {"action":"set","node":{"key":"/services/lobby_gate/127.0.0.1|9201","value":"","expiration":"2021-06-26T14:11:49.5250317Z","ttl":180,"modifiedIndex":51,"createdIndex":51},"prevNode":{"key":"/services/lobby_gate/127.0.0.1|9201","value":"","expiration":"2021-06-26T14:09:59.4375332Z","ttl":70,"modifiedIndex":48,"createdIndex":48}}
, now_url: http://127.0.0.1:2379/v2/keys/services/lobby_gate/127.0.0.1|9201
2021-06-26 22:09:01,176 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 47 -> 50
2021-06-26 22:10:09,202 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 50 -> 52
2021-06-26 22:10:31,558 - DEBUG - ServiceRegister - [EtcdSupport.py:196]: outside, time.time()=1624716631.546563, refresh service lobby_gate, now_url: http://127.0.0.1:2379/v2/keys/services/lobby_gate/127.0.0.1|9201
2021-06-26 22:10:31,624 - DEBUG - ServiceRegister - [EtcdSupport.py:214]: time.time()=1624716631.6158776, refresh service success: lobby_gate: {"action":"set","node":{"key":"/services/lobby_gate/127.0.0.1|9201","value":"","expiration":"2021-06-26T14:13:31.6075698Z","ttl":180,"modifiedIndex":54,"createdIndex":54},"prevNode":{"key":"/services/lobby_gate/127.0.0.1|9201","value":"","expiration":"2021-06-26T14:11:49.5250317Z","ttl":78,"modifiedIndex":51,"createdIndex":51}}
, now_url: http://127.0.0.1:2379/v2/keys/services/lobby_gate/127.0.0.1|9201
2021-06-26 22:11:12,227 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 52 -> 53
2021-06-26 22:12:20,639 - DEBUG - ServiceRegister - [EtcdSupport.py:196]: outside, time.time()=1624716740.6324139, refresh service lobby_gate, now_url: http://127.0.0.1:2379/v2/keys/services/lobby_gate/127.0.0.1|9201
2021-06-26 22:12:20,662 - DEBUG - ServiceRegister - [EtcdSupport.py:214]: time.time()=1624716740.659432, refresh service success: lobby_gate: {"action":"set","node":{"key":"/services/lobby_gate/127.0.0.1|9201","value":"","expiration":"2021-06-26T14:15:20.6574947Z","ttl":180,"modifiedIndex":57,"createdIndex":57},"prevNode":{"key":"/services/lobby_gate/127.0.0.1|9201","value":"","expiration":"2021-06-26T14:13:31.6075698Z","ttl":71,"modifiedIndex":54,"createdIndex":54}}
, now_url: http://127.0.0.1:2379/v2/keys/services/lobby_gate/127.0.0.1|9201
2021-06-26 22:12:22,247 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 53 -> 55
2021-06-26 22:13:24,266 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 55 -> 57
2021-06-26 22:13:38,135 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 2951) is connected !!!!
2021-06-26 22:13:38,179 - CRITICAL - ProxyCliRpcHandler - [ProxyRpcHandler.py:110]: on_traceback, type:<class 'NameError'>, value:name 'ServerEntity' is not defined, traceback:<class 'NameError'>
name 'ServerEntity' is not defined
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\ProxyRpcHandler.py", line 87, in handle_rpc
    locals={'self': <ProxyRpcHandler.ProxyCliRpcHandler object at 0x0000024438DE0580>, 'rpc_msg': b'\x96\x01\x01\xa6Avatar\xb5puppet_entity_message\x92\xd9!CompAvatarTest.puppet_chat_to_ppt\x81\xa7content\xb2puppet_chat_to_ppt\x80', 'dispatcher_json_conf_path': '../bin/win/conf/dispatcher_service.json', 'conf_file': <_io.TextIOWrapper name='../bin/win/conf/dispatcher_service.json' mode='r' encoding='cp936'>, 'dispatcher_json_conf': {'$MACRO$': {'LOBBY_SRV_IP': '127.0.0.1', 'ETCD_IP': '127.0.0.1', 'DISPATCHER_IP': '127.0.0.1', '$LOBBY_GATE_IP': '127.0.0.1'}, 'etcd_servers': [{'ip': '127.0.0.1', 'port': 2379}], 'log_path': '../bin/win/log/', 'lobby_entity_root': 'lobby_entity', 'battle_entity_root': 'battle_entity', 'server_entity_root': 'server_entity', 'component_root': 'component', 'dispatcher_0': {'ip': '127.0.0.1', 'port': 9100}, 'dispatcher_1': {'ip': '127.0.0.1', 'port': 9101}, 'dispatcher_2': {'ip': '127.0.0.1', 'port': 9102}, 'dispatcher_3': {'ip': '127.0.0.1', 'port': 9103}, 'dispatcher_4': {'ip': '127.0.0.1', '...
2021-06-26 22:13:44,149 - CRITICAL - ProxyCliRpcHandler - [ProxyRpcHandler.py:110]: on_traceback, type:<class 'NameError'>, value:name 'ServerEntity' is not defined, traceback:<class 'NameError'>
name 'ServerEntity' is not defined
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\ProxyRpcHandler.py", line 87, in handle_rpc
    locals={'self': <ProxyRpcHandler.ProxyCliRpcHandler object at 0x0000024438DE0580>, 'rpc_msg': b'\x91\x03', 'dispatcher_json_conf_path': '../bin/win/conf/dispatcher_service.json', 'conf_file': <_io.TextIOWrapper name='../bin/win/conf/dispatcher_service.json' mode='r' encoding='cp936'>, 'dispatcher_json_conf': {'$MACRO$': {'LOBBY_SRV_IP': '127.0.0.1', 'ETCD_IP': '127.0.0.1', 'DISPATCHER_IP': '127.0.0.1', '$LOBBY_GATE_IP': '127.0.0.1'}, 'etcd_servers': [{'ip': '127.0.0.1', 'port': 2379}], 'log_path': '../bin/win/log/', 'lobby_entity_root': 'lobby_entity', 'battle_entity_root': 'battle_entity', 'server_entity_root': 'server_entity', 'component_root': 'component', 'dispatcher_0': {'ip': '127.0.0.1', 'port': 9100}, 'dispatcher_1': {'ip': '127.0.0.1', 'port': 9101}, 'dispatcher_2': {'ip': '127.0.0.1', 'port': 9102}, 'dispatcher_3': {'ip': '127.0.0.1', 'port': 9103}, 'dispatcher_4': {'ip': '127.0.0.1', 'port': 9104}, 'dispatcher_5': {'ip': '127.0.0.1', 'port': 9105}}, 'rand_dispatcher_service_addr': ('127.0.0.1', 9100), '_s...
2021-06-26 22:13:46,150 - WARNING - TcpConn - [TcpConn.py:173]: heartbeat timeout
2021-06-26 22:13:46,180 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 2954) is connected !!!!
2021-06-26 22:13:48,184 - CRITICAL - ProxyCliRpcHandler - [ProxyRpcHandler.py:110]: on_traceback, type:<class 'NameError'>, value:name 'ServerEntity' is not defined, traceback:<class 'NameError'>
name 'ServerEntity' is not defined
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\ProxyRpcHandler.py", line 87, in handle_rpc
    locals={'self': <ProxyRpcHandler.ProxyCliRpcHandler object at 0x000002443A1A8790>, 'rpc_msg': b'\x96\x01\x02\xa6Avatar\xb5puppet_entity_message\x92\xd9!CompAvatarTest.puppet_chat_to_ppt\x81\xa7content\xb2puppet_chat_to_ppt\x80', 'dispatcher_json_conf_path': '../bin/win/conf/dispatcher_service.json', 'conf_file': <_io.TextIOWrapper name='../bin/win/conf/dispatcher_service.json' mode='r' encoding='cp936'>, 'dispatcher_json_conf': {'$MACRO$': {'LOBBY_SRV_IP': '127.0.0.1', 'ETCD_IP': '127.0.0.1', 'DISPATCHER_IP': '127.0.0.1', '$LOBBY_GATE_IP': '127.0.0.1'}, 'etcd_servers': [{'ip': '127.0.0.1', 'port': 2379}], 'log_path': '../bin/win/log/', 'lobby_entity_root': 'lobby_entity', 'battle_entity_root': 'battle_entity', 'server_entity_root': 'server_entity', 'component_root': 'component', 'dispatcher_0': {'ip': '127.0.0.1', 'port': 9100}, 'dispatcher_1': {'ip': '127.0.0.1', 'port': 9101}, 'dispatcher_2': {'ip': '127.0.0.1', 'port': 9102}, 'dispatcher_3': {'ip': '127.0.0.1', 'port': 9103}, 'dispatcher_4': {'ip': '127.0.0.1', '...
2021-06-26 22:13:52,203 - CRITICAL - ProxyCliRpcHandler - [ProxyRpcHandler.py:110]: on_traceback, type:<class 'NameError'>, value:name 'ServerEntity' is not defined, traceback:<class 'NameError'>
name 'ServerEntity' is not defined
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\ProxyRpcHandler.py", line 87, in handle_rpc
    locals={'self': <ProxyRpcHandler.ProxyCliRpcHandler object at 0x000002443A1A8790>, 'rpc_msg': b'\x91\x03', 'dispatcher_json_conf_path': '../bin/win/conf/dispatcher_service.json', 'conf_file': <_io.TextIOWrapper name='../bin/win/conf/dispatcher_service.json' mode='r' encoding='cp936'>, 'dispatcher_json_conf': {'$MACRO$': {'LOBBY_SRV_IP': '127.0.0.1', 'ETCD_IP': '127.0.0.1', 'DISPATCHER_IP': '127.0.0.1', '$LOBBY_GATE_IP': '127.0.0.1'}, 'etcd_servers': [{'ip': '127.0.0.1', 'port': 2379}], 'log_path': '../bin/win/log/', 'lobby_entity_root': 'lobby_entity', 'battle_entity_root': 'battle_entity', 'server_entity_root': 'server_entity', 'component_root': 'component', 'dispatcher_0': {'ip': '127.0.0.1', 'port': 9100}, 'dispatcher_1': {'ip': '127.0.0.1', 'port': 9101}, 'dispatcher_2': {'ip': '127.0.0.1', 'port': 9102}, 'dispatcher_3': {'ip': '127.0.0.1', 'port': 9103}, 'dispatcher_4': {'ip': '127.0.0.1', 'port': 9104}, 'dispatcher_5': {'ip': '127.0.0.1', 'port': 9105}}, 'rand_dispatcher_service_addr': ('127.0.0.1', 9100), '_s...
2021-06-26 22:14:16,625 - DEBUG - ServerEntity.LoadReporter - [ServerEntity.py:23]: __init__ create entity LoadReporter with id 60d7363896164b5f3d8f53c2 mem_id=2414644267616
2021-06-26 22:14:16,625 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d7363896164b5f3d8f53c2 
2021-06-26 22:14:16,638 - DEBUG - ServiceNode - [EtcdSupport.py:533]: we have create ServiceFinder
2021-06-26 22:14:16,650 - DEBUG - ServiceFinder - [EtcdSupport.py:352]: _init_info, now_url: http://127.0.0.1:2379/v2/keys?recursive=true
2021-06-26 22:14:16,656 - DEBUG - ServiceRegister - [EtcdSupport.py:155]: _do_regist: now_url: http://127.0.0.1:2379/v2/keys/services/lobby_gate/127.0.0.1|9201
2021-06-26 22:14:16,667 - DEBUG - TcpServer - [TcpServer.py:194]: Server on ('127.0.0.1', 9201)
2021-06-26 22:14:16,696 - DEBUG - ServiceFinder - [EtcdSupport.py:323]: add service node info--> lobby_gate: ('127.0.0.1', 9201)
2021-06-26 22:14:16,701 - DEBUG - ServiceFinder - [EtcdSupport.py:323]: add service node info--> dispatcher_service: ('127.0.0.1', 9100)
2021-06-26 22:14:16,705 - DEBUG - ServiceFinder - [EtcdSupport.py:323]: add service node info--> lobby_server: ('127.0.0.1', 10001)
2021-06-26 22:14:16,709 - DEBUG - ServiceFinder - [EtcdSupport.py:277]: init service info from etcd success, will going to watch, at etcd index -> 60
2021-06-26 22:14:16,722 - DEBUG - ServiceRegister - [EtcdSupport.py:163]: regist service : lobby_gate success, {"action":"set","node":{"key":"/services/lobby_gate/127.0.0.1|9201","value":"","expiration":"2021-06-26T14:17:16.6861185Z","ttl":180,"modifiedIndex":61,"createdIndex":61},"prevNode":{"key":"/services/lobby_gate/127.0.0.1|9201","value":"","expiration":"2021-06-26T14:15:20.6574947Z","ttl":64,"modifiedIndex":57,"createdIndex":57}}

2021-06-26 22:14:16,733 - DEBUG - ServiceFinder - [EtcdSupport.py:422]: recv watch set service node info--> lobby_gate: ('127.0.0.1', 9201) - [61]
2021-06-26 22:14:16,736 - DEBUG - ServiceFinder - [EtcdSupport.py:299]: duplicate service info  -> lobby_gate:('127.0.0.1', 9201)
2021-06-26 22:15:20,762 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 61 -> 61
2021-06-26 22:16:02,725 - DEBUG - ServiceRegister - [EtcdSupport.py:196]: outside, time.time()=1624716962.7181752, refresh service lobby_gate, now_url: http://127.0.0.1:2379/v2/keys/services/lobby_gate/127.0.0.1|9201
2021-06-26 22:16:02,754 - DEBUG - ServiceRegister - [EtcdSupport.py:214]: time.time()=1624716962.752602, refresh service success: lobby_gate: {"action":"set","node":{"key":"/services/lobby_gate/127.0.0.1|9201","value":"","expiration":"2021-06-26T14:19:02.7483043Z","ttl":180,"modifiedIndex":64,"createdIndex":64},"prevNode":{"key":"/services/lobby_gate/127.0.0.1|9201","value":"","expiration":"2021-06-26T14:17:16.6861185Z","ttl":74,"modifiedIndex":61,"createdIndex":61}}
, now_url: http://127.0.0.1:2379/v2/keys/services/lobby_gate/127.0.0.1|9201
2021-06-26 22:16:22,779 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 61 -> 62
2021-06-26 22:17:14,305 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 3087) is connected !!!!
2021-06-26 22:17:14,342 - DEBUG - ServerEntity.ServerEntity - [ServerEntity.py:23]: __init__ create entity ServerEntity with id 60d736ea96164b5f3d8f53c3 mem_id=2414646007936
2021-06-26 22:17:14,348 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d736ea96164b5f3d8f53c3 
2021-06-26 22:17:17,378 - ERROR - ProxyCliRpcHandler - [ProxyRpcHandler.py:101]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_server'], rpc_fuc_kwargs={}"
2021-06-26 22:17:20,328 - DEBUG - ServerEntity.ServerEntity - [ServerEntity.py:23]: __init__ create entity ServerEntity with id 60d736f096164b5f3d8f53c4 mem_id=2414646008608
2021-06-26 22:17:20,332 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d736f096164b5f3d8f53c4 
2021-06-26 22:17:22,315 - WARNING - TcpConn - [TcpConn.py:173]: heartbeat timeout
2021-06-26 22:17:22,349 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 3090) is connected !!!!
2021-06-26 22:17:23,365 - ERROR - ProxyCliRpcHandler - [ProxyRpcHandler.py:101]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_server'], rpc_fuc_kwargs={}"
2021-06-26 22:17:24,346 - DEBUG - ServerEntity.ServerEntity - [ServerEntity.py:23]: __init__ create entity ServerEntity with id 60d736f496164b5f3d8f53c5 mem_id=2414647110576
2021-06-26 22:17:24,353 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d736f496164b5f3d8f53c5 
2021-06-26 22:17:27,380 - ERROR - ProxyCliRpcHandler - [ProxyRpcHandler.py:101]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_server'], rpc_fuc_kwargs={}"
2021-06-26 22:17:28,359 - DEBUG - ServerEntity.ServerEntity - [ServerEntity.py:23]: __init__ create entity ServerEntity with id 60d736f896164b5f3d8f53c6 mem_id=2414647785648
2021-06-26 22:17:28,362 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d736f896164b5f3d8f53c6 
2021-06-26 22:17:29,801 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 62 -> 64
2021-06-26 22:17:30,343 - WARNING - TcpConn - [TcpConn.py:173]: heartbeat timeout
2021-06-26 22:17:30,370 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 3096) is connected !!!!
2021-06-26 22:17:31,375 - ERROR - ProxyCliRpcHandler - [ProxyRpcHandler.py:101]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_server'], rpc_fuc_kwargs={}"
2021-06-26 22:17:34,347 - DEBUG - ServerEntity.ServerEntity - [ServerEntity.py:23]: __init__ create entity ServerEntity with id 60d736fe96164b5f3d8f53c7 mem_id=2414647784976
2021-06-26 22:17:34,352 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d736fe96164b5f3d8f53c7 
2021-06-26 22:17:36,372 - DEBUG - ServerEntity.ServerEntity - [ServerEntity.py:23]: __init__ create entity ServerEntity with id 60d7370096164b5f3d8f53c8 mem_id=2414647110144
2021-06-26 22:17:36,374 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d7370096164b5f3d8f53c8 
2021-06-26 22:17:37,395 - ERROR - ProxyCliRpcHandler - [ProxyRpcHandler.py:101]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_server'], rpc_fuc_kwargs={}"
2021-06-26 22:17:38,380 - WARNING - TcpConn - [TcpConn.py:173]: heartbeat timeout
2021-06-26 22:17:38,404 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 3104) is connected !!!!
2021-06-26 22:17:39,393 - ERROR - ProxyCliRpcHandler - [ProxyRpcHandler.py:101]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_server'], rpc_fuc_kwargs={}"
2021-06-26 22:17:44,379 - DEBUG - ServerEntity.ServerEntity - [ServerEntity.py:23]: __init__ create entity ServerEntity with id 60d7370896164b5f3d8f53c9 mem_id=2414647841264
2021-06-26 22:17:44,382 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d7370896164b5f3d8f53c9 
2021-06-26 22:17:44,402 - DEBUG - ServerEntity.ServerEntity - [ServerEntity.py:23]: __init__ create entity ServerEntity with id 60d7370896164b5f3d8f53ca mem_id=2414647844096
2021-06-26 22:17:44,405 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d7370896164b5f3d8f53ca 
2021-06-26 22:23:54,255 - DEBUG - ServerEntity.LoadReporter - [ServerEntity.py:23]: __init__ create entity LoadReporter with id 60d7387a0e9a89981f2c2f0a mem_id=2507801169776
2021-06-26 22:23:54,255 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d7387a0e9a89981f2c2f0a 
2021-06-26 22:23:54,275 - DEBUG - ServiceNode - [EtcdSupport.py:533]: we have create ServiceFinder
2021-06-26 22:23:54,291 - DEBUG - ServiceFinder - [EtcdSupport.py:352]: _init_info, now_url: http://127.0.0.1:2379/v2/keys?recursive=true
2021-06-26 22:23:54,299 - DEBUG - ServiceRegister - [EtcdSupport.py:155]: _do_regist: now_url: http://127.0.0.1:2379/v2/keys/services/lobby_gate/127.0.0.1|9201
2021-06-26 22:23:54,313 - DEBUG - TcpServer - [TcpServer.py:194]: Server on ('127.0.0.1', 9201)
2021-06-26 22:23:54,336 - DEBUG - ServiceFinder - [EtcdSupport.py:323]: add service node info--> dispatcher_service: ('127.0.0.1', 9100)
2021-06-26 22:23:54,340 - DEBUG - ServiceFinder - [EtcdSupport.py:323]: add service node info--> lobby_server: ('127.0.0.1', 10001)
2021-06-26 22:23:54,344 - DEBUG - ServiceFinder - [EtcdSupport.py:277]: init service info from etcd success, will going to watch, at etcd index -> 74
2021-06-26 22:23:54,357 - DEBUG - ServiceRegister - [EtcdSupport.py:163]: regist service : lobby_gate success, {"action":"set","node":{"key":"/services/lobby_gate/127.0.0.1|9201","value":"","expiration":"2021-06-26T14:26:54.328739Z","ttl":180,"modifiedIndex":75,"createdIndex":75}}

2021-06-26 22:23:54,367 - DEBUG - ServiceFinder - [EtcdSupport.py:422]: recv watch set service node info--> lobby_gate: ('127.0.0.1', 9201) - [75]
2021-06-26 22:25:02,413 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 75 -> 75
2021-06-26 22:25:44,384 - DEBUG - ServiceRegister - [EtcdSupport.py:196]: outside, time.time()=1624717544.3749392, refresh service lobby_gate, now_url: http://127.0.0.1:2379/v2/keys/services/lobby_gate/127.0.0.1|9201
2021-06-26 22:25:44,440 - DEBUG - ServiceRegister - [EtcdSupport.py:214]: time.time()=1624717544.4314837, refresh service success: lobby_gate: {"action":"set","node":{"key":"/services/lobby_gate/127.0.0.1|9201","value":"","expiration":"2021-06-26T14:28:44.4234913Z","ttl":180,"modifiedIndex":78,"createdIndex":78},"prevNode":{"key":"/services/lobby_gate/127.0.0.1|9201","value":"","expiration":"2021-06-26T14:26:54.328739Z","ttl":70,"modifiedIndex":75,"createdIndex":75}}
, now_url: http://127.0.0.1:2379/v2/keys/services/lobby_gate/127.0.0.1|9201
2021-06-26 22:26:07,447 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 75 -> 76
2021-06-26 22:26:16,536 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 7625) is connected !!!!
2021-06-26 22:26:16,556 - DEBUG - ServerEntity.ServerEntity - [ServerEntity.py:23]: __init__ create entity ServerEntity with id 60d739080e9a89981f2c2f0b mem_id=2507802585360
2021-06-26 22:26:16,558 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d739080e9a89981f2c2f0b 
2021-06-26 22:26:19,590 - ERROR - ProxyCliRpcHandler - [ProxyRpcHandler.py:101]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_server'], rpc_fuc_kwargs={}"
2021-06-26 22:26:22,571 - DEBUG - ServerEntity.ServerEntity - [ServerEntity.py:23]: __init__ create entity ServerEntity with id 60d7390e0e9a89981f2c2f0c mem_id=2507802585984
2021-06-26 22:26:22,574 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d7390e0e9a89981f2c2f0c 
2021-06-26 22:26:24,554 - WARNING - TcpConn - [TcpConn.py:173]: heartbeat timeout
2021-06-26 22:26:24,586 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 7629) is connected !!!!
2021-06-26 22:26:25,600 - ERROR - ProxyCliRpcHandler - [ProxyRpcHandler.py:101]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_server'], rpc_fuc_kwargs={}"
2021-06-26 22:26:26,571 - DEBUG - ServerEntity.ServerEntity - [ServerEntity.py:23]: __init__ create entity ServerEntity with id 60d739120e9a89981f2c2f0d mem_id=2507801166944
2021-06-26 22:26:26,577 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d739120e9a89981f2c2f0d 
2021-06-26 22:26:29,598 - ERROR - ProxyCliRpcHandler - [ProxyRpcHandler.py:101]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_server'], rpc_fuc_kwargs={}"
2021-06-26 22:27:11,225 - DEBUG - ServerEntity.LoadReporter - [ServerEntity.py:23]: __init__ create entity LoadReporter with id 60d7393f8904308cdb0fadfb mem_id=2121415299024
2021-06-26 22:27:11,225 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d7393f8904308cdb0fadfb 
2021-06-26 22:27:11,239 - DEBUG - ServiceNode - [EtcdSupport.py:533]: we have create ServiceFinder
2021-06-26 22:27:11,250 - DEBUG - ServiceFinder - [EtcdSupport.py:352]: _init_info, now_url: http://127.0.0.1:2379/v2/keys?recursive=true
2021-06-26 22:27:11,256 - DEBUG - ServiceRegister - [EtcdSupport.py:155]: _do_regist: now_url: http://127.0.0.1:2379/v2/keys/services/lobby_gate/127.0.0.1|9201
2021-06-26 22:27:11,270 - DEBUG - TcpServer - [TcpServer.py:194]: Server on ('127.0.0.1', 9201)
2021-06-26 22:27:11,297 - DEBUG - ServiceFinder - [EtcdSupport.py:323]: add service node info--> dispatcher_service: ('127.0.0.1', 9100)
2021-06-26 22:27:11,302 - DEBUG - ServiceFinder - [EtcdSupport.py:323]: add service node info--> lobby_server: ('127.0.0.1', 10001)
2021-06-26 22:27:11,307 - DEBUG - ServiceFinder - [EtcdSupport.py:323]: add service node info--> lobby_gate: ('127.0.0.1', 9201)
2021-06-26 22:27:11,311 - DEBUG - ServiceFinder - [EtcdSupport.py:277]: init service info from etcd success, will going to watch, at etcd index -> 80
2021-06-26 22:27:11,323 - DEBUG - ServiceRegister - [EtcdSupport.py:163]: regist service : lobby_gate success, {"action":"set","node":{"key":"/services/lobby_gate/127.0.0.1|9201","value":"","expiration":"2021-06-26T14:30:11.2903268Z","ttl":180,"modifiedIndex":81,"createdIndex":81},"prevNode":{"key":"/services/lobby_gate/127.0.0.1|9201","value":"","expiration":"2021-06-26T14:28:44.4234913Z","ttl":94,"modifiedIndex":78,"createdIndex":78}}

2021-06-26 22:27:11,338 - DEBUG - ServiceFinder - [EtcdSupport.py:422]: recv watch set service node info--> lobby_gate: ('127.0.0.1', 9201) - [81]
2021-06-26 22:27:11,341 - DEBUG - ServiceFinder - [EtcdSupport.py:299]: duplicate service info  -> lobby_gate:('127.0.0.1', 9201)
2021-06-26 22:27:31,353 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 7678) is connected !!!!
2021-06-26 22:28:02,128 - DEBUG - ServerEntity.ServerEntity - [ServerEntity.py:23]: __init__ create entity ServerEntity with id 60d739728904308cdb0fadfc mem_id=2121418139152
2021-06-26 22:28:02,132 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d739728904308cdb0fadfc 
2021-06-26 22:28:37,514 - WARNING - TcpConn - [TcpConn.py:173]: connection is closed by error: [WinError 10053] An established connection was aborted by the software in your host machine
2021-06-26 22:28:37,533 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 7684) is connected !!!!
2021-06-26 22:28:37,549 - WARNING - TcpConn - [TcpConn.py:173]: heartbeat timeout
2021-06-26 22:28:37,560 - WARNING - RpcHandler - [RpcHandler.py:185]: bbb _try_connect_times=1, id(self._conn)= 2121418139104
2021-06-26 22:28:43,175 - DEBUG - ServerEntity.ServerEntity - [ServerEntity.py:23]: __init__ create entity ServerEntity with id 60d7399b8904308cdb0fadfd mem_id=2121418837920
2021-06-26 22:28:43,181 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d7399b8904308cdb0fadfd 
2021-06-26 22:28:43,195 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 7688) is connected !!!!
2021-06-26 22:28:43,218 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 7693) is connected !!!!
2021-06-26 22:28:43,228 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 81 -> 81
2021-06-26 22:28:45,368 - DEBUG - ServerEntity.ServerEntity - [ServerEntity.py:23]: __init__ create entity ServerEntity with id 60d7399d8904308cdb0fadfe mem_id=2121397241552
2021-06-26 22:28:45,372 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d7399d8904308cdb0fadfe 
2021-06-26 22:28:45,385 - DEBUG - ServerEntity.ServerEntity - [ServerEntity.py:23]: __init__ create entity ServerEntity with id 60d7399d8904308cdb0fadff mem_id=2121418913872
2021-06-26 22:28:45,387 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d7399d8904308cdb0fadff 
2021-06-26 22:28:45,402 - WARNING - RpcHandler - [RpcHandler.py:190]: aaa _try_connect_times=2, id(self._conn)= 2121418780048
2021-06-26 22:28:45,406 - WARNING - RpcHandler - [RpcHandler.py:212]: rrr _try_connect_times=2, id(self._conn)= 2121418780048
2021-06-26 22:28:45,416 - WARNING - TcpConn - [TcpConn.py:173]: the peer has performed an orderly shutdown (recv 0 byte).
2021-06-26 22:28:45,425 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 7697) is connected !!!!
2021-06-26 22:28:45,449 - DEBUG - ServerEntity.ServerEntity - [ServerEntity.py:23]: __init__ create entity ServerEntity with id 60d7399d8904308cdb0fae00 mem_id=2121416888480
2021-06-26 22:28:45,453 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d7399d8904308cdb0fae00 
2021-06-26 22:28:45,464 - DEBUG - ServerEntity.ServerEntity - [ServerEntity.py:23]: __init__ create entity ServerEntity with id 60d7399d8904308cdb0fae01 mem_id=2121418834704
2021-06-26 22:28:45,470 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d7399d8904308cdb0fae01 
2021-06-26 22:28:45,487 - WARNING - TcpConn - [TcpConn.py:173]: the peer has performed an orderly shutdown (recv 0 byte).
2021-06-26 22:28:45,501 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 7701) is connected !!!!
2021-06-26 22:28:45,539 - DEBUG - ServerEntity.ServerEntity - [ServerEntity.py:23]: __init__ create entity ServerEntity with id 60d7399d8904308cdb0fae02 mem_id=2121419160016
2021-06-26 22:28:45,545 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d7399d8904308cdb0fae02 
2021-06-26 22:28:45,557 - DEBUG - ServerEntity.ServerEntity - [ServerEntity.py:23]: __init__ create entity ServerEntity with id 60d7399d8904308cdb0fae03 mem_id=2121419161120
2021-06-26 22:28:45,562 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d7399d8904308cdb0fae03 
2021-06-26 22:28:45,578 - WARNING - TcpConn - [TcpConn.py:173]: the peer has performed an orderly shutdown (recv 0 byte).
2021-06-26 22:28:45,591 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 7707) is connected !!!!
2021-06-26 22:31:28,722 - DEBUG - ServerEntity.LoadReporter - [ServerEntity.py:23]: __init__ create entity LoadReporter with id 60d73a40d95c97a54da26692 mem_id=2451253960560
2021-06-26 22:31:28,722 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d73a40d95c97a54da26692 
2021-06-26 22:31:28,738 - DEBUG - ServiceNode - [EtcdSupport.py:533]: we have create ServiceFinder
2021-06-26 22:31:28,753 - DEBUG - ServiceFinder - [EtcdSupport.py:352]: _init_info, now_url: http://127.0.0.1:2379/v2/keys?recursive=true
2021-06-26 22:31:28,760 - DEBUG - ServiceRegister - [EtcdSupport.py:155]: _do_regist: now_url: http://127.0.0.1:2379/v2/keys/services/lobby_gate/127.0.0.1|9201
2021-06-26 22:31:28,771 - DEBUG - TcpServer - [TcpServer.py:194]: Server on ('127.0.0.1', 9201)
2021-06-26 22:31:28,795 - DEBUG - ServiceFinder - [EtcdSupport.py:323]: add service node info--> dispatcher_service: ('127.0.0.1', 9100)
2021-06-26 22:31:28,798 - DEBUG - ServiceFinder - [EtcdSupport.py:323]: add service node info--> lobby_server: ('127.0.0.1', 10001)
2021-06-26 22:31:28,801 - DEBUG - ServiceFinder - [EtcdSupport.py:277]: init service info from etcd success, will going to watch, at etcd index -> 88
2021-06-26 22:31:28,818 - DEBUG - ServiceRegister - [EtcdSupport.py:163]: regist service : lobby_gate success, {"action":"set","node":{"key":"/services/lobby_gate/127.0.0.1|9201","value":"","expiration":"2021-06-26T14:34:28.7867038Z","ttl":180,"modifiedIndex":89,"createdIndex":89}}

2021-06-26 22:31:28,828 - DEBUG - ServiceFinder - [EtcdSupport.py:422]: recv watch set service node info--> lobby_gate: ('127.0.0.1', 9201) - [89]
2021-06-26 22:31:46,454 - DEBUG - ServerEntity.LoadReporter - [ServerEntity.py:23]: __init__ create entity LoadReporter with id 60d73a52125a84528931c3a9 mem_id=2190397070832
2021-06-26 22:31:46,456 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d73a52125a84528931c3a9 
2021-06-26 22:31:46,465 - DEBUG - ServiceNode - [EtcdSupport.py:533]: we have create ServiceFinder
2021-06-26 22:31:46,472 - DEBUG - ServiceFinder - [EtcdSupport.py:352]: _init_info, now_url: http://127.0.0.1:2379/v2/keys?recursive=true
2021-06-26 22:31:46,475 - DEBUG - ServiceRegister - [EtcdSupport.py:155]: _do_regist: now_url: http://127.0.0.1:2379/v2/keys/services/lobby_gate/127.0.0.1|9201
2021-06-26 22:31:46,481 - DEBUG - TcpServer - [TcpServer.py:194]: Server on ('127.0.0.1', 9201)
2021-06-26 22:31:46,494 - DEBUG - ServiceFinder - [EtcdSupport.py:323]: add service node info--> dispatcher_service: ('127.0.0.1', 9100)
2021-06-26 22:31:46,496 - DEBUG - ServiceFinder - [EtcdSupport.py:323]: add service node info--> lobby_server: ('127.0.0.1', 10001)
2021-06-26 22:31:46,499 - DEBUG - ServiceFinder - [EtcdSupport.py:323]: add service node info--> lobby_gate: ('127.0.0.1', 9201)
2021-06-26 22:31:46,500 - DEBUG - ServiceFinder - [EtcdSupport.py:277]: init service info from etcd success, will going to watch, at etcd index -> 89
2021-06-26 22:31:46,508 - DEBUG - ServiceRegister - [EtcdSupport.py:163]: regist service : lobby_gate success, {"action":"set","node":{"key":"/services/lobby_gate/127.0.0.1|9201","value":"","expiration":"2021-06-26T14:34:46.4900422Z","ttl":180,"modifiedIndex":90,"createdIndex":90},"prevNode":{"key":"/services/lobby_gate/127.0.0.1|9201","value":"","expiration":"2021-06-26T14:34:28.7867038Z","ttl":163,"modifiedIndex":89,"createdIndex":89}}

2021-06-26 22:31:46,517 - DEBUG - ServiceFinder - [EtcdSupport.py:422]: recv watch set service node info--> lobby_gate: ('127.0.0.1', 9201) - [90]
2021-06-26 22:31:46,519 - DEBUG - ServiceFinder - [EtcdSupport.py:299]: duplicate service info  -> lobby_gate:('127.0.0.1', 9201)
2021-06-26 22:31:49,231 - DEBUG - ServerEntity.LoadReporter - [ServerEntity.py:23]: __init__ create entity LoadReporter with id 60d73a5539b48eec9a84be5d mem_id=2088634796304
2021-06-26 22:31:49,231 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d73a5539b48eec9a84be5d 
2021-06-26 22:31:49,250 - DEBUG - ServiceNode - [EtcdSupport.py:533]: we have create ServiceFinder
2021-06-26 22:31:49,259 - DEBUG - ServiceFinder - [EtcdSupport.py:352]: _init_info, now_url: http://127.0.0.1:2379/v2/keys?recursive=true
2021-06-26 22:31:49,266 - DEBUG - ServiceRegister - [EtcdSupport.py:155]: _do_regist: now_url: http://127.0.0.1:2379/v2/keys/services/lobby_gate/127.0.0.1|9201
2021-06-26 22:31:49,278 - DEBUG - TcpServer - [TcpServer.py:194]: Server on ('127.0.0.1', 9201)
2021-06-26 22:31:49,306 - DEBUG - ServiceFinder - [EtcdSupport.py:323]: add service node info--> lobby_server: ('127.0.0.1', 10001)
2021-06-26 22:31:49,310 - DEBUG - ServiceFinder - [EtcdSupport.py:323]: add service node info--> lobby_gate: ('127.0.0.1', 9201)
2021-06-26 22:31:49,316 - DEBUG - ServiceFinder - [EtcdSupport.py:323]: add service node info--> dispatcher_service: ('127.0.0.1', 9100)
2021-06-26 22:31:49,320 - DEBUG - ServiceFinder - [EtcdSupport.py:277]: init service info from etcd success, will going to watch, at etcd index -> 90
2021-06-26 22:31:49,335 - DEBUG - ServiceRegister - [EtcdSupport.py:163]: regist service : lobby_gate success, {"action":"set","node":{"key":"/services/lobby_gate/127.0.0.1|9201","value":"","expiration":"2021-06-26T14:34:49.2997779Z","ttl":180,"modifiedIndex":91,"createdIndex":91},"prevNode":{"key":"/services/lobby_gate/127.0.0.1|9201","value":"","expiration":"2021-06-26T14:34:46.4900422Z","ttl":178,"modifiedIndex":90,"createdIndex":90}}

2021-06-26 22:31:49,356 - DEBUG - ServiceFinder - [EtcdSupport.py:422]: recv watch set service node info--> lobby_gate: ('127.0.0.1', 9201) - [91]
2021-06-26 22:31:49,359 - DEBUG - ServiceFinder - [EtcdSupport.py:299]: duplicate service info  -> lobby_gate:('127.0.0.1', 9201)
2021-06-26 22:32:59,383 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 91 -> 91
2021-06-26 22:33:07,805 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 2736) is connected !!!!
2021-06-26 22:33:07,853 - DEBUG - ServerEntity.ServerEntity - [ServerEntity.py:23]: __init__ create entity ServerEntity with id 60d73aa339b48eec9a84be5e mem_id=2088637685328
2021-06-26 22:33:07,858 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d73aa339b48eec9a84be5e 
2021-06-26 22:35:15,743 - DEBUG - ServerEntity.LoadReporter - [ServerEntity.py:23]: __init__ create entity LoadReporter with id 60d73b234cd8c3f6763f0604 mem_id=3190779664704
2021-06-26 22:35:15,744 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d73b234cd8c3f6763f0604 
2021-06-26 22:35:15,754 - DEBUG - ServiceNode - [EtcdSupport.py:533]: we have create ServiceFinder
2021-06-26 22:35:15,765 - DEBUG - ServiceFinder - [EtcdSupport.py:352]: _init_info, now_url: http://127.0.0.1:2379/v2/keys?recursive=true
2021-06-26 22:35:15,775 - DEBUG - ServiceRegister - [EtcdSupport.py:155]: _do_regist: now_url: http://127.0.0.1:2379/v2/keys/services/lobby_gate/127.0.0.1|9201
2021-06-26 22:35:15,790 - DEBUG - TcpServer - [TcpServer.py:194]: Server on ('127.0.0.1', 9201)
2021-06-26 22:35:15,818 - DEBUG - ServiceFinder - [EtcdSupport.py:323]: add service node info--> dispatcher_service: ('127.0.0.1', 9100)
2021-06-26 22:35:15,824 - DEBUG - ServiceFinder - [EtcdSupport.py:323]: add service node info--> lobby_server: ('127.0.0.1', 10001)
2021-06-26 22:35:15,828 - DEBUG - ServiceFinder - [EtcdSupport.py:277]: init service info from etcd success, will going to watch, at etcd index -> 96
2021-06-26 22:35:15,843 - DEBUG - ServiceRegister - [EtcdSupport.py:163]: regist service : lobby_gate success, {"action":"set","node":{"key":"/services/lobby_gate/127.0.0.1|9201","value":"","expiration":"2021-06-26T14:38:15.8111565Z","ttl":180,"modifiedIndex":97,"createdIndex":97}}

2021-06-26 22:35:15,858 - DEBUG - ServiceFinder - [EtcdSupport.py:422]: recv watch set service node info--> lobby_gate: ('127.0.0.1', 9201) - [97]
2021-06-26 22:35:25,712 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 8521) is connected !!!!
2021-06-26 22:35:25,754 - DEBUG - ServerEntity.ServerEntity - [ServerEntity.py:23]: __init__ create entity ServerEntity with id 60d73b2d4cd8c3f6763f0605 mem_id=3190782541152
2021-06-26 22:35:25,760 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d73b2d4cd8c3f6763f0605 
2021-06-26 22:36:40,827 - DEBUG - ServerEntity.LoadReporter - [ServerEntity.py:23]: __init__ create entity LoadReporter with id 60d73b781efa58fb743f1ced mem_id=2149220080032
2021-06-26 22:36:40,827 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d73b781efa58fb743f1ced 
2021-06-26 22:36:40,844 - DEBUG - ServiceNode - [EtcdSupport.py:533]: we have create ServiceFinder
2021-06-26 22:36:40,854 - DEBUG - ServiceFinder - [EtcdSupport.py:352]: _init_info, now_url: http://127.0.0.1:2379/v2/keys?recursive=true
2021-06-26 22:36:40,863 - DEBUG - ServiceRegister - [EtcdSupport.py:155]: _do_regist: now_url: http://127.0.0.1:2379/v2/keys/services/lobby_gate/127.0.0.1|9201
2021-06-26 22:36:40,875 - DEBUG - TcpServer - [TcpServer.py:194]: Server on ('127.0.0.1', 9201)
2021-06-26 22:36:40,901 - DEBUG - ServiceFinder - [EtcdSupport.py:323]: add service node info--> dispatcher_service: ('127.0.0.1', 9100)
2021-06-26 22:36:40,906 - DEBUG - ServiceFinder - [EtcdSupport.py:323]: add service node info--> lobby_server: ('127.0.0.1', 10001)
2021-06-26 22:36:40,911 - DEBUG - ServiceFinder - [EtcdSupport.py:323]: add service node info--> lobby_gate: ('127.0.0.1', 9201)
2021-06-26 22:36:40,914 - DEBUG - ServiceFinder - [EtcdSupport.py:277]: init service info from etcd success, will going to watch, at etcd index -> 98
2021-06-26 22:36:40,926 - DEBUG - ServiceRegister - [EtcdSupport.py:163]: regist service : lobby_gate success, {"action":"set","node":{"key":"/services/lobby_gate/127.0.0.1|9201","value":"","expiration":"2021-06-26T14:39:40.8930583Z","ttl":180,"modifiedIndex":99,"createdIndex":99},"prevNode":{"key":"/services/lobby_gate/127.0.0.1|9201","value":"","expiration":"2021-06-26T14:38:15.8111565Z","ttl":95,"modifiedIndex":97,"createdIndex":97}}

2021-06-26 22:36:40,941 - DEBUG - ServiceFinder - [EtcdSupport.py:422]: recv watch set service node info--> lobby_gate: ('127.0.0.1', 9201) - [99]
2021-06-26 22:36:40,944 - DEBUG - ServiceFinder - [EtcdSupport.py:299]: duplicate service info  -> lobby_gate:('127.0.0.1', 9201)
2021-06-26 22:36:41,430 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 8579) is connected !!!!
2021-06-26 22:36:42,188 - WARNING - TcpConn - [TcpConn.py:173]: connection is closed by error: [WinError 64] The specified network name is no longer available
2021-06-26 22:36:44,048 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 8588) is connected !!!!
2021-06-26 22:36:44,095 - DEBUG - ServerEntity.ServerEntity - [ServerEntity.py:23]: __init__ create entity ServerEntity with id 60d73b7c1efa58fb743f1cee mem_id=2149222950896
2021-06-26 22:36:44,097 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d73b7c1efa58fb743f1cee 
2021-06-26 22:37:16,599 - CRITICAL - ProxyCliRpcHandler - [ProxyRpcHandler.py:116]: on_traceback, type:<class 'socket.gaierror'>, value:[Errno 10109] getaddrinfo failed, traceback:<class 'socket.gaierror'>
[Errno 10109] getaddrinfo failed
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\ProxyRpcHandler.py", line 111, in handle_rpc
    locals={'self': <ProxyRpcHandler.ProxyCliRpcHandler object at 0x000001F467ABA580>, 'rpc_msg': b'\x96\x01\x01\xa6Avatar\xb5puppet_entity_message\x92\xd9!CompAvatarTest.puppet_chat_to_ppt\x81\xa7content\xb2puppet_chat_to_ppt\x80', 'dispatcher_json_conf_path': '../bin/win/conf/dispatcher_service.json', 'conf_file': <_io.TextIOWrapper name='../bin/win/conf/dispatcher_service.json' mode='r' encoding='cp936'>, 'dispatcher_json_conf': {'$MACRO$': {'LOBBY_SRV_IP': '127.0.0.1', 'ETCD_IP': '127.0.0.1', 'DISPATCHER_IP': '127.0.0.1', '$LOBBY_GATE_IP': '127.0.0.1'}, 'etcd_servers': [{'ip': '127.0.0.1', 'port': 2379}], 'log_path': '../bin/win/log/', 'lobby_entity_root': 'lobby_entity', 'battle_entity_root': 'battle_entity', 'server_entity_root': 'server_entity', 'component_root': 'component', 'dispatcher_0': {'ip': '127.0.0.1', 'port': 9100}}, 'rand_dispatcher_service_addr': ('127.0.0.1', 9100), '_svr_name': 'dispatcher_0', '_svr_info': {'ip': '127.0.0.1', 'port': 9100}, 'temp_se': <server_entity.ServerEntity.ServerEntity object ...
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\ConnMgr.py", line 39, in get_conn_by_addr
    locals={'self': <ConnMgr.ConnMgr object at 0x000001F467ABA310>, 'addr': ('lobby_0', '127.0.0.1', 10001), 'rpc_handler': <ProxyRpcHandler.ProxyLobbyRpcHandler object at 0x000001F4666C25B0>, '_conn': None}
  File "C:\Program Files\Python38\lib\asyncio\streams.py", line 52, in open_connection
    locals={'host': 'lobby_0', 'port': '127.0.0.1', 'loop': <ProactorEventLoop running=True closed=False debug=True>, 'limit': 65536, 'kwds': {}, 'reader': <StreamReader>, 'protocol': <asyncio.streams.StreamReaderProtocol object at 0x000001F467ABAAF0>}
  File "C:\Program Files\Python38\lib\asyncio\base_events.py", line 986, in create_connection
    locals={'self': <ProactorEventLoop running=True closed=False debug=True>, 'protocol_factory': <function open_connection.<locals>.<lambda> at 0x000001F467B44F70>, 'host': 'lobby_0', 'port': '127.0.0.1', 'ssl': None, 'family': 0, 'proto': 0, 'flags': 0, 'sock': None, 'local_addr': None, 'server_hostname': None, 'ssl_handshake_timeout': None, 'happy_eyeballs_delay': None, 'interleave': None}
  File "C:\Program Files\Python38\lib\asyncio\base_events.py", line 1365, in _ensure_resolved
    locals={'self': <ProactorEventLoop running=True closed=False debug=True>, 'address': ('lobby_0', '127.0.0.1'), 'family': 0, 'type': <SocketKind.SOCK_STREAM: 1>, 'proto': 0, 'flags': 0, 'loop': <ProactorEventLoop running=True closed=False debug=True>, 'host': 'lobby_0', 'port': '127.0.0.1', 'info': None}
  File "C:\Program Files\Python38\lib\asyncio\base_events.py", line 825, in getaddrinfo
    locals={'self': <ProactorEventLoop running=True closed=False debug=True>, 'host': 'lobby_0', 'port': '127.0.0.1', 'family': 0, 'type': <SocketKind.SOCK_STREAM: 1>, 'proto': 0, 'flags': 0, 'getaddr_func': <bound method BaseEventLoop._getaddrinfo_debug of <ProactorEventLoop running=True closed=False debug=True>>}
  File "C:\Program Files\Python38\lib\concurrent\futures\thread.py", line 57, in run
    locals={}
  File "C:\Program Files\Python38\lib\asyncio\base_events.py", line 808, in _getaddrinfo_debug
    locals={'self': <ProactorEventLoop running=True closed=False debug=True>, 'host': 'lobby_0', 'port': '127.0.0.1', 'family': 0, 'type': <SocketKind.SOCK_STREAM: 1>, 'proto': 0, 'flags': 0, 'msg': "lobby_0:'127.0.0.1', type=<SocketKind.SOCK_STREAM: 1>", 't0': 620113.843}
  File "C:\Program Files\Python38\lib\socket.py", line 918, in getaddrinfo
    locals={'host': 'lobby_0', 'port': '127.0.0.1', 'family': 0, 'type': <SocketKind.SOCK_STREAM: 1>, 'proto': 0, 'flags': 0, 'addrlist': []}
2021-06-26 22:37:16,607 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 8595) is connected !!!!
2021-06-26 22:37:16,616 - WARNING - TcpConn - [TcpConn.py:173]: heartbeat timeout
2021-06-26 22:37:16,620 - WARNING - TcpConn - [TcpConn.py:173]: heartbeat timeout
2021-06-26 22:37:16,633 - DEBUG - ServerEntity.ServerEntity - [ServerEntity.py:23]: __init__ create entity ServerEntity with id 60d73b9c1efa58fb743f1cef mem_id=2149223650016
2021-06-26 22:37:16,636 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d73b9c1efa58fb743f1cef 
2021-06-26 22:37:16,653 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 8598) is connected !!!!
2021-06-26 22:37:16,670 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 8602) is connected !!!!
2021-06-26 22:37:16,683 - DEBUG - ServerEntity.ServerEntity - [ServerEntity.py:23]: __init__ create entity ServerEntity with id 60d73b9c1efa58fb743f1cf0 mem_id=2149223649440
2021-06-26 22:37:16,686 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d73b9c1efa58fb743f1cf0 
2021-06-26 22:37:16,697 - WARNING - TcpConn - [TcpConn.py:173]: the peer has performed an orderly shutdown (recv 0 byte).
2021-06-26 22:37:16,705 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 8606) is connected !!!!
2021-06-26 22:37:16,725 - DEBUG - ServerEntity.ServerEntity - [ServerEntity.py:23]: __init__ create entity ServerEntity with id 60d73b9c1efa58fb743f1cf1 mem_id=2149221475232
2021-06-26 22:37:16,728 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d73b9c1efa58fb743f1cf1 
2021-06-26 22:37:16,743 - WARNING - TcpConn - [TcpConn.py:173]: the peer has performed an orderly shutdown (recv 0 byte).
2021-06-26 22:37:16,759 - DEBUG - ServerEntity.ServerEntity - [ServerEntity.py:23]: __init__ create entity ServerEntity with id 60d73b9c1efa58fb743f1cf2 mem_id=2149223696080
2021-06-26 22:37:16,764 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d73b9c1efa58fb743f1cf2 
2021-06-26 22:37:16,774 - WARNING - TcpConn - [TcpConn.py:173]: the peer has performed an orderly shutdown (recv 0 byte).
2021-06-26 22:37:18,989 - CRITICAL - ProxyCliRpcHandler - [ProxyRpcHandler.py:116]: on_traceback, type:<class 'socket.gaierror'>, value:[Errno 10109] getaddrinfo failed, traceback:<class 'socket.gaierror'>
[Errno 10109] getaddrinfo failed
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\ProxyRpcHandler.py", line 111, in handle_rpc
    locals={'self': <ProxyRpcHandler.ProxyCliRpcHandler object at 0x000001F467ABA580>, 'rpc_msg': b'\x91\x03', 'dispatcher_json_conf_path': '../bin/win/conf/dispatcher_service.json', 'conf_file': <_io.TextIOWrapper name='../bin/win/conf/dispatcher_service.json' mode='r' encoding='cp936'>, 'dispatcher_json_conf': {'$MACRO$': {'LOBBY_SRV_IP': '127.0.0.1', 'ETCD_IP': '127.0.0.1', 'DISPATCHER_IP': '127.0.0.1', '$LOBBY_GATE_IP': '127.0.0.1'}, 'etcd_servers': [{'ip': '127.0.0.1', 'port': 2379}], 'log_path': '../bin/win/log/', 'lobby_entity_root': 'lobby_entity', 'battle_entity_root': 'battle_entity', 'server_entity_root': 'server_entity', 'component_root': 'component', 'dispatcher_0': {'ip': '127.0.0.1', 'port': 9100}}, 'rand_dispatcher_service_addr': ('127.0.0.1', 9100), '_svr_name': 'dispatcher_0', '_svr_info': {'ip': '127.0.0.1', 'port': 9100}, 'temp_se': <server_entity.ServerEntity.ServerEntity object at 0x000001F467B652E0>, 'start_time': 1624718236.6399376, '_err': None, '_lobby_addr': ('lobby_0', '127.0.0.1', 10001), 'e...
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\ConnMgr.py", line 39, in get_conn_by_addr
    locals={'self': <ConnMgr.ConnMgr object at 0x000001F467ABA310>, 'addr': ('lobby_0', '127.0.0.1', 10001), 'rpc_handler': <ProxyRpcHandler.ProxyLobbyRpcHandler object at 0x000001F467B48580>, '_conn': None}
  File "C:\Program Files\Python38\lib\asyncio\streams.py", line 52, in open_connection
    locals={'host': 'lobby_0', 'port': '127.0.0.1', 'loop': <ProactorEventLoop running=True closed=False debug=True>, 'limit': 65536, 'kwds': {}, 'reader': <StreamReader>, 'protocol': <asyncio.streams.StreamReaderProtocol object at 0x000001F467B70070>}
  File "C:\Program Files\Python38\lib\asyncio\base_events.py", line 986, in create_connection
    locals={'self': <ProactorEventLoop running=True closed=False debug=True>, 'protocol_factory': <function open_connection.<locals>.<lambda> at 0x000001F467BB7E50>, 'host': 'lobby_0', 'port': '127.0.0.1', 'ssl': None, 'family': 0, 'proto': 0, 'flags': 0, 'sock': None, 'local_addr': None, 'server_hostname': None, 'ssl_handshake_timeout': None, 'happy_eyeballs_delay': None, 'interleave': None}
  File "C:\Program Files\Python38\lib\asyncio\base_events.py", line 1365, in _ensure_resolved
    locals={'self': <ProactorEventLoop running=True closed=False debug=True>, 'address': ('lobby_0', '127.0.0.1'), 'family': 0, 'type': <SocketKind.SOCK_STREAM: 1>, 'proto': 0, 'flags': 0, 'loop': <ProactorEventLoop running=True closed=False debug=True>, 'host': 'lobby_0', 'port': '127.0.0.1', 'info': None}
  File "C:\Program Files\Python38\lib\asyncio\base_events.py", line 825, in getaddrinfo
    locals={'self': <ProactorEventLoop running=True closed=False debug=True>, 'host': 'lobby_0', 'port': '127.0.0.1', 'family': 0, 'type': <SocketKind.SOCK_STREAM: 1>, 'proto': 0, 'flags': 0, 'getaddr_func': <bound method BaseEventLoop._getaddrinfo_debug of <ProactorEventLoop running=True closed=False debug=True>>}
  File "C:\Program Files\Python38\lib\concurrent\futures\thread.py", line 57, in run
    locals={}
  File "C:\Program Files\Python38\lib\asyncio\base_events.py", line 808, in _getaddrinfo_debug
    locals={'self': <ProactorEventLoop running=True closed=False debug=True>, 'host': 'lobby_0', 'port': '127.0.0.1', 'family': 0, 'type': <SocketKind.SOCK_STREAM: 1>, 'proto': 0, 'flags': 0, 'msg': "lobby_0:'127.0.0.1', type=<SocketKind.SOCK_STREAM: 1>", 't0': 620116.281}
  File "C:\Program Files\Python38\lib\socket.py", line 918, in getaddrinfo
    locals={'host': 'lobby_0', 'port': '127.0.0.1', 'family': 0, 'type': <SocketKind.SOCK_STREAM: 1>, 'proto': 0, 'flags': 0, 'addrlist': []}
2021-06-26 22:37:20,038 - CRITICAL - ProxyCliRpcHandler - [ProxyRpcHandler.py:116]: on_traceback, type:<class 'socket.gaierror'>, value:[Errno 10109] getaddrinfo failed, traceback:<class 'socket.gaierror'>
[Errno 10109] getaddrinfo failed
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\ProxyRpcHandler.py", line 111, in handle_rpc
    locals={'self': <ProxyRpcHandler.ProxyCliRpcHandler object at 0x000001F467ABA1C0>, 'rpc_msg': b'\x91\x03', 'dispatcher_json_conf_path': '../bin/win/conf/dispatcher_service.json', 'conf_file': <_io.TextIOWrapper name='../bin/win/conf/dispatcher_service.json' mode='r' encoding='cp936'>, 'dispatcher_json_conf': {'$MACRO$': {'LOBBY_SRV_IP': '127.0.0.1', 'ETCD_IP': '127.0.0.1', 'DISPATCHER_IP': '127.0.0.1', '$LOBBY_GATE_IP': '127.0.0.1'}, 'etcd_servers': [{'ip': '127.0.0.1', 'port': 2379}], 'log_path': '../bin/win/log/', 'lobby_entity_root': 'lobby_entity', 'battle_entity_root': 'battle_entity', 'server_entity_root': 'server_entity', 'component_root': 'component', 'dispatcher_0': {'ip': '127.0.0.1', 'port': 9100}}, 'rand_dispatcher_service_addr': ('127.0.0.1', 9100), '_svr_name': 'dispatcher_0', '_svr_info': {'ip': '127.0.0.1', 'port': 9100}, 'temp_se': <server_entity.ServerEntity.ServerEntity object at 0x000001F467B650A0>, 'start_time': 1624718236.689323, '_err': None, '_lobby_addr': ('lobby_0', '127.0.0.1', 10001), 'en...
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\ConnMgr.py", line 39, in get_conn_by_addr
    locals={'self': <ConnMgr.ConnMgr object at 0x000001F467ABA310>, 'addr': ('lobby_0', '127.0.0.1', 10001), 'rpc_handler': <ProxyRpcHandler.ProxyLobbyRpcHandler object at 0x000001F467BC4340>, '_conn': None}
  File "C:\Program Files\Python38\lib\asyncio\streams.py", line 52, in open_connection
    locals={'host': 'lobby_0', 'port': '127.0.0.1', 'loop': <ProactorEventLoop running=True closed=False debug=True>, 'limit': 65536, 'kwds': {}, 'reader': <StreamReader>, 'protocol': <asyncio.streams.StreamReaderProtocol object at 0x000001F467B70AF0>}
  File "C:\Program Files\Python38\lib\asyncio\base_events.py", line 986, in create_connection
    locals={'self': <ProactorEventLoop running=True closed=False debug=True>, 'protocol_factory': <function open_connection.<locals>.<lambda> at 0x000001F467BB7AF0>, 'host': 'lobby_0', 'port': '127.0.0.1', 'ssl': None, 'family': 0, 'proto': 0, 'flags': 0, 'sock': None, 'local_addr': None, 'server_hostname': None, 'ssl_handshake_timeout': None, 'happy_eyeballs_delay': None, 'interleave': None}
  File "C:\Program Files\Python38\lib\asyncio\base_events.py", line 1365, in _ensure_resolved
    locals={'self': <ProactorEventLoop running=True closed=False debug=True>, 'address': ('lobby_0', '127.0.0.1'), 'family': 0, 'type': <SocketKind.SOCK_STREAM: 1>, 'proto': 0, 'flags': 0, 'loop': <ProactorEventLoop running=True closed=False debug=True>, 'host': 'lobby_0', 'port': '127.0.0.1', 'info': None}
  File "C:\Program Files\Python38\lib\asyncio\base_events.py", line 825, in getaddrinfo
    locals={'self': <ProactorEventLoop running=True closed=False debug=True>, 'host': 'lobby_0', 'port': '127.0.0.1', 'family': 0, 'type': <SocketKind.SOCK_STREAM: 1>, 'proto': 0, 'flags': 0, 'getaddr_func': <bound method BaseEventLoop._getaddrinfo_debug of <ProactorEventLoop running=True closed=False debug=True>>}
  File "C:\Program Files\Python38\lib\concurrent\futures\thread.py", line 57, in run
    locals={}
  File "C:\Program Files\Python38\lib\asyncio\base_events.py", line 808, in _getaddrinfo_debug
    locals={'self': <ProactorEventLoop running=True closed=False debug=True>, 'host': 'lobby_0', 'port': '127.0.0.1', 'family': 0, 'type': <SocketKind.SOCK_STREAM: 1>, 'proto': 0, 'flags': 0, 'msg': "lobby_0:'127.0.0.1', type=<SocketKind.SOCK_STREAM: 1>", 't0': 620117.328}
  File "C:\Program Files\Python38\lib\socket.py", line 918, in getaddrinfo
    locals={'host': 'lobby_0', 'port': '127.0.0.1', 'family': 0, 'type': <SocketKind.SOCK_STREAM: 1>, 'proto': 0, 'flags': 0, 'addrlist': []}
2021-06-26 22:40:12,985 - DEBUG - ServerEntity.LoadReporter - [ServerEntity.py:23]: __init__ create entity LoadReporter with id 60d73c4c56ff79d0c5f6ece8 mem_id=2965133441248
2021-06-26 22:40:12,985 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d73c4c56ff79d0c5f6ece8 
2021-06-26 22:40:13,005 - DEBUG - ServiceNode - [EtcdSupport.py:533]: we have create ServiceFinder
2021-06-26 22:40:13,015 - DEBUG - ServiceFinder - [EtcdSupport.py:352]: _init_info, now_url: http://127.0.0.1:2379/v2/keys?recursive=true
2021-06-26 22:40:13,023 - DEBUG - ServiceRegister - [EtcdSupport.py:155]: _do_regist: now_url: http://127.0.0.1:2379/v2/keys/services/lobby_gate/127.0.0.1|9201
2021-06-26 22:40:13,038 - DEBUG - TcpServer - [TcpServer.py:194]: Server on ('127.0.0.1', 9201)
2021-06-26 22:40:13,063 - DEBUG - ServiceFinder - [EtcdSupport.py:323]: add service node info--> dispatcher_service: ('127.0.0.1', 9100)
2021-06-26 22:40:13,067 - DEBUG - ServiceFinder - [EtcdSupport.py:323]: add service node info--> lobby_server: ('127.0.0.1', 10001)
2021-06-26 22:40:13,071 - DEBUG - ServiceFinder - [EtcdSupport.py:277]: init service info from etcd success, will going to watch, at etcd index -> 106
2021-06-26 22:40:13,085 - DEBUG - ServiceRegister - [EtcdSupport.py:163]: regist service : lobby_gate success, {"action":"set","node":{"key":"/services/lobby_gate/127.0.0.1|9201","value":"","expiration":"2021-06-26T14:43:13.0543209Z","ttl":180,"modifiedIndex":107,"createdIndex":107}}

2021-06-26 22:40:13,098 - DEBUG - ServiceFinder - [EtcdSupport.py:422]: recv watch set service node info--> lobby_gate: ('127.0.0.1', 9201) - [107]
2021-06-26 22:40:25,782 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 8734) is connected !!!!
2021-06-26 22:40:25,806 - DEBUG - ServerEntity.ServerEntity - [ServerEntity.py:23]: __init__ create entity ServerEntity with id 60d73c5956ff79d0c5f6ece9 mem_id=2965136334176
2021-06-26 22:40:25,812 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d73c5956ff79d0c5f6ece9 
2021-06-26 22:40:28,870 - ERROR - ProxyCliRpcHandler - [ProxyRpcHandler.py:107]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_server'], rpc_fuc_kwargs={}"
2021-06-26 22:40:31,804 - DEBUG - ServerEntity.ServerEntity - [ServerEntity.py:23]: __init__ create entity ServerEntity with id 60d73c5f56ff79d0c5f6ecea mem_id=2965136334080
2021-06-26 22:40:31,810 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d73c5f56ff79d0c5f6ecea 
2021-06-26 22:40:33,800 - WARNING - TcpConn - [TcpConn.py:173]: heartbeat timeout
2021-06-26 22:40:33,824 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 8738) is connected !!!!
2021-06-26 22:40:34,842 - ERROR - ProxyCliRpcHandler - [ProxyRpcHandler.py:107]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_server'], rpc_fuc_kwargs={}"
2021-06-26 22:40:39,840 - DEBUG - ServerEntity.ServerEntity - [ServerEntity.py:23]: __init__ create entity ServerEntity with id 60d73c6756ff79d0c5f6eceb mem_id=2965136333216
2021-06-26 22:40:39,845 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d73c6756ff79d0c5f6eceb 
2021-06-26 22:40:41,834 - WARNING - TcpConn - [TcpConn.py:173]: heartbeat timeout
2021-06-26 22:40:41,859 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 8746) is connected !!!!
2021-06-26 22:40:42,876 - ERROR - ProxyCliRpcHandler - [ProxyRpcHandler.py:107]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_server'], rpc_fuc_kwargs={}"
2021-06-26 22:40:47,879 - DEBUG - ServerEntity.ServerEntity - [ServerEntity.py:23]: __init__ create entity ServerEntity with id 60d73c6f56ff79d0c5f6ecec mem_id=2965136907472
2021-06-26 22:40:47,884 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d73c6f56ff79d0c5f6ecec 
2021-06-26 22:40:49,881 - WARNING - TcpConn - [TcpConn.py:173]: heartbeat timeout
2021-06-26 22:40:49,900 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 8752) is connected !!!!
2021-06-26 22:40:50,916 - ERROR - ProxyCliRpcHandler - [ProxyRpcHandler.py:107]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_server'], rpc_fuc_kwargs={}"
2021-06-26 22:40:55,914 - DEBUG - ServerEntity.ServerEntity - [ServerEntity.py:23]: __init__ create entity ServerEntity with id 60d73c7756ff79d0c5f6eced mem_id=2965136330816
2021-06-26 22:40:55,919 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d73c7756ff79d0c5f6eced 
2021-06-26 22:40:57,915 - WARNING - TcpConn - [TcpConn.py:173]: heartbeat timeout
2021-06-26 22:40:57,941 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 8755) is connected !!!!
2021-06-26 22:40:58,961 - ERROR - ProxyCliRpcHandler - [ProxyRpcHandler.py:107]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_server'], rpc_fuc_kwargs={}"
2021-06-26 22:41:03,964 - DEBUG - ServerEntity.ServerEntity - [ServerEntity.py:23]: __init__ create entity ServerEntity with id 60d73c7f56ff79d0c5f6ecee mem_id=2965136967568
2021-06-26 22:41:03,970 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d73c7f56ff79d0c5f6ecee 
2021-06-26 22:41:05,956 - WARNING - TcpConn - [TcpConn.py:173]: heartbeat timeout
2021-06-26 22:41:05,991 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 8763) is connected !!!!
2021-06-26 22:41:06,989 - ERROR - ProxyCliRpcHandler - [ProxyRpcHandler.py:107]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_server'], rpc_fuc_kwargs={}"
2021-06-26 22:41:12,009 - DEBUG - ServerEntity.ServerEntity - [ServerEntity.py:23]: __init__ create entity ServerEntity with id 60d73c8856ff79d0c5f6ecef mem_id=2965136967136
2021-06-26 22:41:12,014 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d73c8856ff79d0c5f6ecef 
2021-06-26 22:41:14,012 - WARNING - TcpConn - [TcpConn.py:173]: heartbeat timeout
2021-06-26 22:41:14,037 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 8768) is connected !!!!
2021-06-26 22:41:15,044 - ERROR - ProxyCliRpcHandler - [ProxyRpcHandler.py:107]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_server'], rpc_fuc_kwargs={}"
2021-06-26 22:41:20,043 - DEBUG - ServerEntity.ServerEntity - [ServerEntity.py:23]: __init__ create entity ServerEntity with id 60d73c9056ff79d0c5f6ecf0 mem_id=2965136968432
2021-06-26 22:41:20,048 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d73c9056ff79d0c5f6ecf0 
2021-06-26 22:41:22,052 - WARNING - TcpConn - [TcpConn.py:173]: heartbeat timeout
2021-06-26 22:41:22,073 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 8772) is connected !!!!
2021-06-26 22:41:23,091 - ERROR - ProxyCliRpcHandler - [ProxyRpcHandler.py:107]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_server'], rpc_fuc_kwargs={}"
2021-06-26 22:41:23,094 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 107 -> 107
2021-06-26 22:41:28,092 - DEBUG - ServerEntity.ServerEntity - [ServerEntity.py:23]: __init__ create entity ServerEntity with id 60d73c9856ff79d0c5f6ecf1 mem_id=2965136906080
2021-06-26 22:41:28,096 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d73c9856ff79d0c5f6ecf1 
2021-06-26 22:41:30,091 - WARNING - TcpConn - [TcpConn.py:173]: heartbeat timeout
2021-06-26 22:41:30,115 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 8777) is connected !!!!
2021-06-26 22:41:31,123 - ERROR - ProxyCliRpcHandler - [ProxyRpcHandler.py:107]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_server'], rpc_fuc_kwargs={}"
2021-06-26 22:41:36,129 - DEBUG - ServerEntity.ServerEntity - [ServerEntity.py:23]: __init__ create entity ServerEntity with id 60d73ca056ff79d0c5f6ecf2 mem_id=2965135706432
2021-06-26 22:41:36,134 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d73ca056ff79d0c5f6ecf2 
2021-06-26 22:41:38,131 - WARNING - TcpConn - [TcpConn.py:173]: heartbeat timeout
2021-06-26 22:41:38,152 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 8783) is connected !!!!
2021-06-26 22:41:39,167 - ERROR - ProxyCliRpcHandler - [ProxyRpcHandler.py:107]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_server'], rpc_fuc_kwargs={}"
2021-06-26 22:46:38,453 - DEBUG - ServerEntity.LoadReporter - [ServerEntity.py:23]: __init__ create entity LoadReporter with id 60d73dcecf079bd0dbd93c56 mem_id=3064368439408
2021-06-26 22:46:38,453 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d73dcecf079bd0dbd93c56 
2021-06-26 22:46:38,465 - DEBUG - ServiceNode - [EtcdSupport.py:533]: we have create ServiceFinder
2021-06-26 22:46:38,475 - DEBUG - ServiceFinder - [EtcdSupport.py:352]: _init_info, now_url: http://127.0.0.1:2379/v2/keys?recursive=true
2021-06-26 22:46:38,482 - DEBUG - ServiceRegister - [EtcdSupport.py:155]: _do_regist: now_url: http://127.0.0.1:2379/v2/keys/services/lobby_gate/127.0.0.1|9201
2021-06-26 22:46:38,491 - DEBUG - TcpServer - [TcpServer.py:194]: Server on ('127.0.0.1', 9201)
2021-06-26 22:46:38,513 - DEBUG - ServiceFinder - [EtcdSupport.py:323]: add service node info--> dispatcher_service: ('127.0.0.1', 9100)
2021-06-26 22:46:38,516 - DEBUG - ServiceFinder - [EtcdSupport.py:323]: add service node info--> lobby_server: ('127.0.0.1', 10001)
2021-06-26 22:46:38,520 - DEBUG - ServiceFinder - [EtcdSupport.py:277]: init service info from etcd success, will going to watch, at etcd index -> 114
2021-06-26 22:46:38,530 - DEBUG - ServiceRegister - [EtcdSupport.py:163]: regist service : lobby_gate success, {"action":"set","node":{"key":"/services/lobby_gate/127.0.0.1|9201","value":"","expiration":"2021-06-26T14:49:38.506941Z","ttl":180,"modifiedIndex":115,"createdIndex":115}}

2021-06-26 22:46:38,540 - DEBUG - ServiceFinder - [EtcdSupport.py:422]: recv watch set service node info--> lobby_gate: ('127.0.0.1', 9201) - [115]
2021-06-26 22:47:44,551 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 115 -> 115
2021-06-26 22:48:32,961 - DEBUG - ServerEntity.LoadReporter - [ServerEntity.py:23]: __init__ create entity LoadReporter with id 60d73e40f8563e58fd76370b mem_id=2906790047648
2021-06-26 22:48:32,962 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d73e40f8563e58fd76370b 
2021-06-26 22:48:32,974 - DEBUG - ServiceNode - [EtcdSupport.py:533]: we have create ServiceFinder
2021-06-26 22:48:32,983 - DEBUG - ServiceFinder - [EtcdSupport.py:352]: _init_info, now_url: http://127.0.0.1:2379/v2/keys?recursive=true
2021-06-26 22:48:32,990 - DEBUG - ServiceRegister - [EtcdSupport.py:155]: _do_regist: now_url: http://127.0.0.1:2379/v2/keys/services/lobby_gate/127.0.0.1|9201
2021-06-26 22:48:32,999 - DEBUG - TcpServer - [TcpServer.py:194]: Server on ('127.0.0.1', 9201)
2021-06-26 22:48:33,020 - DEBUG - ServiceFinder - [EtcdSupport.py:323]: add service node info--> dispatcher_service: ('127.0.0.1', 9100)
2021-06-26 22:48:33,023 - DEBUG - ServiceFinder - [EtcdSupport.py:323]: add service node info--> lobby_server: ('127.0.0.1', 10001)
2021-06-26 22:48:33,026 - DEBUG - ServiceFinder - [EtcdSupport.py:323]: add service node info--> lobby_gate: ('127.0.0.1', 9201)
2021-06-26 22:48:33,029 - DEBUG - ServiceFinder - [EtcdSupport.py:277]: init service info from etcd success, will going to watch, at etcd index -> 117
2021-06-26 22:48:33,041 - DEBUG - ServiceRegister - [EtcdSupport.py:163]: regist service : lobby_gate success, {"action":"set","node":{"key":"/services/lobby_gate/127.0.0.1|9201","value":"","expiration":"2021-06-26T14:51:33.0157288Z","ttl":180,"modifiedIndex":118,"createdIndex":118},"prevNode":{"key":"/services/lobby_gate/127.0.0.1|9201","value":"","expiration":"2021-06-26T14:49:38.506941Z","ttl":66,"modifiedIndex":115,"createdIndex":115}}

2021-06-26 22:48:33,051 - DEBUG - ServiceFinder - [EtcdSupport.py:422]: recv watch set service node info--> lobby_gate: ('127.0.0.1', 9201) - [118]
2021-06-26 22:48:33,054 - DEBUG - ServiceFinder - [EtcdSupport.py:299]: duplicate service info  -> lobby_gate:('127.0.0.1', 9201)
2021-06-26 22:48:36,177 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 7104) is connected !!!!
2021-06-26 22:48:36,191 - DEBUG - ServerEntity.ServerEntity - [ServerEntity.py:23]: __init__ create entity ServerEntity with id 60d73e44f8563e58fd76370c mem_id=2906793210352
2021-06-26 22:48:36,195 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d73e44f8563e58fd76370c 
2021-06-26 22:48:36,241 - CRITICAL - ProxyCliRpcHandler - [ProxyRpcHandler.py:116]: on_traceback, type:<class 'socket.gaierror'>, value:[Errno 10109] getaddrinfo failed, traceback:<class 'socket.gaierror'>
[Errno 10109] getaddrinfo failed
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\ProxyRpcHandler.py", line 111, in handle_rpc
    locals={'self': <ProxyRpcHandler.ProxyCliRpcHandler object at 0x000002A4CA532790>, 'rpc_msg': b'\x96\x01\x01\xa6Avatar\xb5puppet_entity_message\x92\xd9!CompAvatarTest.puppet_chat_to_ppt\x81\xa7content\xb2puppet_chat_to_ppt\x80', 'dispatcher_json_conf_path': '../bin/win/conf/dispatcher_service.json', 'conf_file': <_io.TextIOWrapper name='../bin/win/conf/dispatcher_service.json' mode='r' encoding='cp936'>, 'dispatcher_json_conf': {'$MACRO$': {'LOBBY_SRV_IP': '127.0.0.1', 'ETCD_IP': '127.0.0.1', 'DISPATCHER_IP': '127.0.0.1', '$LOBBY_GATE_IP': '127.0.0.1'}, 'etcd_servers': [{'ip': '127.0.0.1', 'port': 2379}], 'log_path': '../bin/win/log/', 'lobby_entity_root': 'lobby_entity', 'battle_entity_root': 'battle_entity', 'server_entity_root': 'server_entity', 'component_root': 'component', 'dispatcher_0': {'ip': '127.0.0.1', 'port': 9100}}, 'rand_dispatcher_service_addr': ('127.0.0.1', 9100), '_svr_name': 'dispatcher_0', '_svr_info': {'ip': '127.0.0.1', 'port': 9100}, 'temp_se': <server_entity.ServerEntity.ServerEntity object ...
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\ConnMgr.py", line 39, in get_conn_by_addr
    locals={'self': <ConnMgr.ConnMgr object at 0x000002A4CA532730>, 'addr': ('lobby_0', '127.0.0.1', 10001), 'rpc_handler': <ProxyRpcHandler.ProxyLobbyRpcHandler object at 0x000002A4CA48AC40>, '_conn': None}
  File "C:\Program Files\Python38\lib\asyncio\streams.py", line 52, in open_connection
    locals={'host': 'lobby_0', 'port': '127.0.0.1', 'loop': <ProactorEventLoop running=True closed=False debug=True>, 'limit': 65536, 'kwds': {}, 'reader': <StreamReader>, 'protocol': <asyncio.streams.StreamReaderProtocol object at 0x000002A4CA64C040>}
  File "C:\Program Files\Python38\lib\asyncio\base_events.py", line 986, in create_connection
    locals={'self': <ProactorEventLoop running=True closed=False debug=True>, 'protocol_factory': <function open_connection.<locals>.<lambda> at 0x000002A4CA3A3670>, 'host': 'lobby_0', 'port': '127.0.0.1', 'ssl': None, 'family': 0, 'proto': 0, 'flags': 0, 'sock': None, 'local_addr': None, 'server_hostname': None, 'ssl_handshake_timeout': None, 'happy_eyeballs_delay': None, 'interleave': None}
  File "C:\Program Files\Python38\lib\asyncio\base_events.py", line 1365, in _ensure_resolved
    locals={'self': <ProactorEventLoop running=True closed=False debug=True>, 'address': ('lobby_0', '127.0.0.1'), 'family': 0, 'type': <SocketKind.SOCK_STREAM: 1>, 'proto': 0, 'flags': 0, 'loop': <ProactorEventLoop running=True closed=False debug=True>, 'host': 'lobby_0', 'port': '127.0.0.1', 'info': None}
  File "C:\Program Files\Python38\lib\asyncio\base_events.py", line 825, in getaddrinfo
    locals={'self': <ProactorEventLoop running=True closed=False debug=True>, 'host': 'lobby_0', 'port': '127.0.0.1', 'family': 0, 'type': <SocketKind.SOCK_STREAM: 1>, 'proto': 0, 'flags': 0, 'getaddr_func': <bound method BaseEventLoop._getaddrinfo_debug of <ProactorEventLoop running=True closed=False debug=True>>}
  File "C:\Program Files\Python38\lib\concurrent\futures\thread.py", line 57, in run
    locals={}
  File "C:\Program Files\Python38\lib\asyncio\base_events.py", line 808, in _getaddrinfo_debug
    locals={'self': <ProactorEventLoop running=True closed=False debug=True>, 'host': 'lobby_0', 'port': '127.0.0.1', 'family': 0, 'type': <SocketKind.SOCK_STREAM: 1>, 'proto': 0, 'flags': 0, 'msg': "lobby_0:'127.0.0.1', type=<SocketKind.SOCK_STREAM: 1>", 't0': 620793.531}
  File "C:\Program Files\Python38\lib\socket.py", line 918, in getaddrinfo
    locals={'host': 'lobby_0', 'port': '127.0.0.1', 'family': 0, 'type': <SocketKind.SOCK_STREAM: 1>, 'proto': 0, 'flags': 0, 'addrlist': []}
2021-06-26 22:48:42,185 - DEBUG - ServerEntity.ServerEntity - [ServerEntity.py:23]: __init__ create entity ServerEntity with id 60d73e4af8563e58fd76370d mem_id=2906793213856
2021-06-26 22:48:42,188 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d73e4af8563e58fd76370d 
2021-06-26 22:48:44,175 - WARNING - TcpConn - [TcpConn.py:173]: heartbeat timeout
2021-06-26 22:48:44,194 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 7110) is connected !!!!
2021-06-26 22:48:45,208 - ERROR - ProxyCliRpcHandler - [ProxyRpcHandler.py:107]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_server'], rpc_fuc_kwargs={}"
2021-06-26 22:48:50,200 - DEBUG - ServerEntity.ServerEntity - [ServerEntity.py:23]: __init__ create entity ServerEntity with id 60d73e52f8563e58fd76370e mem_id=2906791651264
2021-06-26 22:48:50,203 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d73e52f8563e58fd76370e 
2021-06-26 22:48:50,400 - WARNING - TcpConn - [TcpConn.py:173]: connection is closed by error: [WinError 64] The specified network name is no longer available
2021-06-26 22:50:24,083 - DEBUG - ServerEntity.LoadReporter - [ServerEntity.py:23]: __init__ create entity LoadReporter with id 60d73eb0799b73f18549a25d mem_id=1802933610672
2021-06-26 22:50:24,083 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d73eb0799b73f18549a25d 
2021-06-26 22:50:24,097 - DEBUG - ServiceNode - [EtcdSupport.py:533]: we have create ServiceFinder
2021-06-26 22:50:24,106 - DEBUG - ServiceFinder - [EtcdSupport.py:352]: _init_info, now_url: http://127.0.0.1:2379/v2/keys?recursive=true
2021-06-26 22:50:24,112 - DEBUG - ServiceRegister - [EtcdSupport.py:155]: _do_regist: now_url: http://127.0.0.1:2379/v2/keys/services/lobby_gate/127.0.0.1|9201
2021-06-26 22:50:24,122 - DEBUG - TcpServer - [TcpServer.py:194]: Server on ('127.0.0.1', 9201)
2021-06-26 22:50:24,144 - DEBUG - ServiceFinder - [EtcdSupport.py:323]: add service node info--> dispatcher_service: ('127.0.0.1', 9100)
2021-06-26 22:50:24,148 - DEBUG - ServiceFinder - [EtcdSupport.py:323]: add service node info--> lobby_server: ('127.0.0.1', 10001)
2021-06-26 22:50:24,151 - DEBUG - ServiceFinder - [EtcdSupport.py:323]: add service node info--> lobby_gate: ('127.0.0.1', 9201)
2021-06-26 22:50:24,154 - DEBUG - ServiceFinder - [EtcdSupport.py:277]: init service info from etcd success, will going to watch, at etcd index -> 121
2021-06-26 22:50:24,166 - DEBUG - ServiceRegister - [EtcdSupport.py:163]: regist service : lobby_gate success, {"action":"set","node":{"key":"/services/lobby_gate/127.0.0.1|9201","value":"","expiration":"2021-06-26T14:53:24.138607Z","ttl":180,"modifiedIndex":122,"createdIndex":122},"prevNode":{"key":"/services/lobby_gate/127.0.0.1|9201","value":"","expiration":"2021-06-26T14:51:33.0157288Z","ttl":69,"modifiedIndex":118,"createdIndex":118}}

2021-06-26 22:50:24,177 - DEBUG - ServiceFinder - [EtcdSupport.py:422]: recv watch set service node info--> lobby_gate: ('127.0.0.1', 9201) - [122]
2021-06-26 22:50:24,180 - DEBUG - ServiceFinder - [EtcdSupport.py:299]: duplicate service info  -> lobby_gate:('127.0.0.1', 9201)
2021-06-26 22:50:26,045 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 7182) is connected !!!!
2021-06-26 22:50:26,089 - DEBUG - ServerEntity.ServerEntity - [ServerEntity.py:23]: __init__ create entity ServerEntity with id 60d73eb2799b73f18549a25e mem_id=1802935269600
2021-06-26 22:50:26,092 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d73eb2799b73f18549a25e 
2021-06-26 22:50:26,134 - CRITICAL - ProxyCliRpcHandler - [ProxyRpcHandler.py:116]: on_traceback, type:<class 'socket.gaierror'>, value:[Errno 10109] getaddrinfo failed, traceback:<class 'socket.gaierror'>
[Errno 10109] getaddrinfo failed
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\ProxyRpcHandler.py", line 111, in handle_rpc
    locals={'self': <ProxyRpcHandler.ProxyCliRpcHandler object at 0x000001A3C75BE0A0>, 'rpc_msg': b'\x96\x01\x01\xa6Avatar\xb5puppet_entity_message\x92\xd9!CompAvatarTest.puppet_chat_to_ppt\x81\xa7content\xb2puppet_chat_to_ppt\x80', 'dispatcher_json_conf_path': '../bin/win/conf/dispatcher_service.json', 'conf_file': <_io.TextIOWrapper name='../bin/win/conf/dispatcher_service.json' mode='r' encoding='cp936'>, 'dispatcher_json_conf': {'$MACRO$': {'LOBBY_SRV_IP': '127.0.0.1', 'ETCD_IP': '127.0.0.1', 'DISPATCHER_IP': '127.0.0.1', '$LOBBY_GATE_IP': '127.0.0.1'}, 'etcd_servers': [{'ip': '127.0.0.1', 'port': 2379}], 'log_path': '../bin/win/log/', 'lobby_entity_root': 'lobby_entity', 'battle_entity_root': 'battle_entity', 'server_entity_root': 'server_entity', 'component_root': 'component', 'dispatcher_0': {'ip': '127.0.0.1', 'port': 9100}}, 'rand_dispatcher_service_addr': ('127.0.0.1', 9100), '_svr_name': 'dispatcher_0', '_svr_info': {'ip': '127.0.0.1', 'port': 9100}, 'temp_se': <server_entity.ServerEntity.ServerEntity object ...
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\ConnMgr.py", line 39, in get_conn_by_addr
    locals={'self': <ConnMgr.ConnMgr object at 0x000001A3C750FD30>, 'addr': ('lobby_0', '127.0.0.1', 10001), 'rpc_handler': <ProxyRpcHandler.ProxyLobbyRpcHandler object at 0x000001A3C750F700>, '_conn': None}
  File "C:\Program Files\Python38\lib\asyncio\streams.py", line 52, in open_connection
    locals={'host': 'lobby_0', 'port': '127.0.0.1', 'loop': <ProactorEventLoop running=True closed=False debug=True>, 'limit': 65536, 'kwds': {}, 'reader': <StreamReader>, 'protocol': <asyncio.streams.StreamReaderProtocol object at 0x000001A3C763A130>}
  File "C:\Program Files\Python38\lib\asyncio\base_events.py", line 986, in create_connection
    locals={'self': <ProactorEventLoop running=True closed=False debug=True>, 'protocol_factory': <function open_connection.<locals>.<lambda> at 0x000001A3C762EEE0>, 'host': 'lobby_0', 'port': '127.0.0.1', 'ssl': None, 'family': 0, 'proto': 0, 'flags': 0, 'sock': None, 'local_addr': None, 'server_hostname': None, 'ssl_handshake_timeout': None, 'happy_eyeballs_delay': None, 'interleave': None}
  File "C:\Program Files\Python38\lib\asyncio\base_events.py", line 1365, in _ensure_resolved
    locals={'self': <ProactorEventLoop running=True closed=False debug=True>, 'address': ('lobby_0', '127.0.0.1'), 'family': 0, 'type': <SocketKind.SOCK_STREAM: 1>, 'proto': 0, 'flags': 0, 'loop': <ProactorEventLoop running=True closed=False debug=True>, 'host': 'lobby_0', 'port': '127.0.0.1', 'info': None}
  File "C:\Program Files\Python38\lib\asyncio\base_events.py", line 825, in getaddrinfo
    locals={'self': <ProactorEventLoop running=True closed=False debug=True>, 'host': 'lobby_0', 'port': '127.0.0.1', 'family': 0, 'type': <SocketKind.SOCK_STREAM: 1>, 'proto': 0, 'flags': 0, 'getaddr_func': <bound method BaseEventLoop._getaddrinfo_debug of <ProactorEventLoop running=True closed=False debug=True>>}
  File "C:\Program Files\Python38\lib\concurrent\futures\thread.py", line 57, in run
    locals={}
  File "C:\Program Files\Python38\lib\asyncio\base_events.py", line 808, in _getaddrinfo_debug
    locals={'self': <ProactorEventLoop running=True closed=False debug=True>, 'host': 'lobby_0', 'port': '127.0.0.1', 'family': 0, 'type': <SocketKind.SOCK_STREAM: 1>, 'proto': 0, 'flags': 0, 'msg': "lobby_0:'127.0.0.1', type=<SocketKind.SOCK_STREAM: 1>", 't0': 620903.421}
  File "C:\Program Files\Python38\lib\socket.py", line 918, in getaddrinfo
    locals={'host': 'lobby_0', 'port': '127.0.0.1', 'family': 0, 'type': <SocketKind.SOCK_STREAM: 1>, 'proto': 0, 'flags': 0, 'addrlist': []}
2021-06-26 22:50:32,036 - DEBUG - ServerEntity.ServerEntity - [ServerEntity.py:23]: __init__ create entity ServerEntity with id 60d73eb8799b73f18549a25f mem_id=1802935986064
2021-06-26 22:50:32,039 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d73eb8799b73f18549a25f 
2021-06-26 22:50:34,053 - WARNING - TcpConn - [TcpConn.py:173]: heartbeat timeout
2021-06-26 22:50:34,072 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 7188) is connected !!!!
2021-06-26 22:50:35,064 - ERROR - ProxyCliRpcHandler - [ProxyRpcHandler.py:107]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_server'], rpc_fuc_kwargs={}"
2021-06-26 22:50:40,077 - DEBUG - ServerEntity.ServerEntity - [ServerEntity.py:23]: __init__ create entity ServerEntity with id 60d73ec0799b73f18549a260 mem_id=1802934660496
2021-06-26 22:50:40,080 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d73ec0799b73f18549a260 
2021-06-26 22:50:42,069 - WARNING - TcpConn - [TcpConn.py:173]: heartbeat timeout
2021-06-26 22:50:42,088 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 7196) is connected !!!!
2021-06-26 22:50:43,115 - ERROR - ProxyCliRpcHandler - [ProxyRpcHandler.py:107]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_server'], rpc_fuc_kwargs={}"
2021-06-26 22:50:48,097 - DEBUG - ServerEntity.ServerEntity - [ServerEntity.py:23]: __init__ create entity ServerEntity with id 60d73ec8799b73f18549a261 mem_id=1802936495936
2021-06-26 22:50:48,100 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d73ec8799b73f18549a261 
2021-06-26 22:50:50,099 - WARNING - TcpConn - [TcpConn.py:173]: heartbeat timeout
2021-06-26 22:50:50,117 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 7201) is connected !!!!
2021-06-26 22:50:51,133 - ERROR - ProxyCliRpcHandler - [ProxyRpcHandler.py:107]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_server'], rpc_fuc_kwargs={}"
2021-06-26 22:50:56,138 - DEBUG - ServerEntity.ServerEntity - [ServerEntity.py:23]: __init__ create entity ServerEntity with id 60d73ed0799b73f18549a262 mem_id=1802936690240
2021-06-26 22:50:56,141 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d73ed0799b73f18549a262 
2021-06-26 22:50:58,114 - WARNING - TcpConn - [TcpConn.py:173]: heartbeat timeout
2021-06-26 22:50:58,135 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 7206) is connected !!!!
2021-06-26 22:50:59,146 - ERROR - ProxyCliRpcHandler - [ProxyRpcHandler.py:107]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_server'], rpc_fuc_kwargs={}"
2021-06-26 22:51:04,141 - DEBUG - ServerEntity.ServerEntity - [ServerEntity.py:23]: __init__ create entity ServerEntity with id 60d73ed8799b73f18549a263 mem_id=1802936691104
2021-06-26 22:51:04,146 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d73ed8799b73f18549a263 
2021-06-26 22:51:06,121 - WARNING - TcpConn - [TcpConn.py:173]: heartbeat timeout
2021-06-26 22:51:06,142 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 7210) is connected !!!!
2021-06-26 22:51:07,167 - ERROR - ProxyCliRpcHandler - [ProxyRpcHandler.py:107]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_server'], rpc_fuc_kwargs={}"
2021-06-26 22:51:12,172 - DEBUG - ServerEntity.ServerEntity - [ServerEntity.py:23]: __init__ create entity ServerEntity with id 60d73ee0799b73f18549a264 mem_id=1802936736112
2021-06-26 22:51:12,176 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d73ee0799b73f18549a264 
2021-06-26 22:51:14,163 - WARNING - TcpConn - [TcpConn.py:173]: heartbeat timeout
2021-06-26 22:51:14,183 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 7213) is connected !!!!
2021-06-26 22:51:15,207 - ERROR - ProxyCliRpcHandler - [ProxyRpcHandler.py:107]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_server'], rpc_fuc_kwargs={}"
2021-06-26 22:51:20,183 - DEBUG - ServerEntity.ServerEntity - [ServerEntity.py:23]: __init__ create entity ServerEntity with id 60d73ee8799b73f18549a265 mem_id=1802936734912
2021-06-26 22:51:20,189 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d73ee8799b73f18549a265 
2021-06-26 22:51:22,197 - WARNING - TcpConn - [TcpConn.py:173]: heartbeat timeout
2021-06-26 22:51:22,214 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 7217) is connected !!!!
2021-06-26 22:51:23,201 - ERROR - ProxyCliRpcHandler - [ProxyRpcHandler.py:107]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_server'], rpc_fuc_kwargs={}"
2021-06-26 22:51:24,205 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 122 -> 122
2021-06-26 22:51:28,220 - DEBUG - ServerEntity.ServerEntity - [ServerEntity.py:23]: __init__ create entity ServerEntity with id 60d73ef0799b73f18549a266 mem_id=1802936735440
2021-06-26 22:51:28,223 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d73ef0799b73f18549a266 
2021-06-26 22:51:30,252 - DEBUG - ServerEntity.LoadReporter - [ServerEntity.py:23]: __init__ create entity LoadReporter with id 60d73ef2f8918174b09d7026 mem_id=2841440983360
2021-06-26 22:51:30,254 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d73ef2f8918174b09d7026 
2021-06-26 22:51:30,265 - DEBUG - ServiceNode - [EtcdSupport.py:533]: we have create ServiceFinder
2021-06-26 22:51:30,273 - DEBUG - ServiceFinder - [EtcdSupport.py:352]: _init_info, now_url: http://127.0.0.1:2379/v2/keys?recursive=true
2021-06-26 22:51:30,280 - DEBUG - ServiceRegister - [EtcdSupport.py:155]: _do_regist: now_url: http://127.0.0.1:2379/v2/keys/services/lobby_gate/127.0.0.1|9201
2021-06-26 22:51:30,290 - DEBUG - TcpServer - [TcpServer.py:194]: Server on ('127.0.0.1', 9201)
2021-06-26 22:51:30,309 - DEBUG - ServiceFinder - [EtcdSupport.py:323]: add service node info--> dispatcher_service: ('127.0.0.1', 9100)
2021-06-26 22:51:30,312 - DEBUG - ServiceFinder - [EtcdSupport.py:323]: add service node info--> lobby_server: ('127.0.0.1', 10001)
2021-06-26 22:51:30,316 - DEBUG - ServiceFinder - [EtcdSupport.py:323]: add service node info--> lobby_gate: ('127.0.0.1', 9201)
2021-06-26 22:51:30,320 - DEBUG - ServiceFinder - [EtcdSupport.py:277]: init service info from etcd success, will going to watch, at etcd index -> 123
2021-06-26 22:51:30,331 - DEBUG - ServiceRegister - [EtcdSupport.py:163]: regist service : lobby_gate success, {"action":"set","node":{"key":"/services/lobby_gate/127.0.0.1|9201","value":"","expiration":"2021-06-26T14:54:30.3044705Z","ttl":180,"modifiedIndex":124,"createdIndex":124},"prevNode":{"key":"/services/lobby_gate/127.0.0.1|9201","value":"","expiration":"2021-06-26T14:53:24.138607Z","ttl":114,"modifiedIndex":122,"createdIndex":122}}

2021-06-26 22:51:30,341 - DEBUG - ServiceFinder - [EtcdSupport.py:422]: recv watch set service node info--> lobby_gate: ('127.0.0.1', 9201) - [124]
2021-06-26 22:51:30,344 - DEBUG - ServiceFinder - [EtcdSupport.py:299]: duplicate service info  -> lobby_gate:('127.0.0.1', 9201)
2021-06-26 22:51:30,748 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 7223) is connected !!!!
2021-06-26 22:51:32,943 - DEBUG - ServiceFinder - [EtcdSupport.py:422]: recv watch set service node info--> lobby_server: ('127.0.0.1', 10001) - [125]
2021-06-26 22:51:32,947 - DEBUG - ServiceFinder - [EtcdSupport.py:299]: duplicate service info  -> lobby_server:('127.0.0.1', 10001)
2021-06-26 22:51:36,762 - DEBUG - ServerEntity.ServerEntity - [ServerEntity.py:23]: __init__ create entity ServerEntity with id 60d73ef8f8918174b09d7027 mem_id=2841443882992
2021-06-26 22:51:36,765 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d73ef8f8918174b09d7027 
2021-06-26 22:51:38,768 - WARNING - TcpConn - [TcpConn.py:173]: heartbeat timeout
2021-06-26 22:51:38,785 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 7248) is connected !!!!
2021-06-26 22:51:39,820 - ERROR - ProxyCliRpcHandler - [ProxyRpcHandler.py:107]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_server'], rpc_fuc_kwargs={}"
2021-06-26 22:51:44,796 - DEBUG - ServerEntity.ServerEntity - [ServerEntity.py:23]: __init__ create entity ServerEntity with id 60d73f00f8918174b09d7028 mem_id=2841444467280
2021-06-26 22:51:44,799 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d73f00f8918174b09d7028 
2021-06-26 22:51:46,802 - WARNING - TcpConn - [TcpConn.py:173]: heartbeat timeout
2021-06-26 22:51:46,820 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 7253) is connected !!!!
2021-06-26 22:51:47,821 - ERROR - ProxyCliRpcHandler - [ProxyRpcHandler.py:107]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_server'], rpc_fuc_kwargs={}"
2021-06-26 22:51:52,207 - WARNING - TcpConn - [TcpConn.py:173]: connection is closed by error: [WinError 64] The specified network name is no longer available
2021-06-26 22:52:17,566 - DEBUG - ServerEntity.LoadReporter - [ServerEntity.py:23]: __init__ create entity LoadReporter with id 60d73f2168df91e3522b229a mem_id=2332159875344
2021-06-26 22:52:17,567 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d73f2168df91e3522b229a 
2021-06-26 22:52:17,579 - DEBUG - ServiceNode - [EtcdSupport.py:533]: we have create ServiceFinder
2021-06-26 22:52:17,587 - DEBUG - ServiceFinder - [EtcdSupport.py:352]: _init_info, now_url: http://127.0.0.1:2379/v2/keys?recursive=true
2021-06-26 22:52:17,593 - DEBUG - ServiceRegister - [EtcdSupport.py:155]: _do_regist: now_url: http://127.0.0.1:2379/v2/keys/services/lobby_gate/127.0.0.1|9201
2021-06-26 22:52:17,603 - DEBUG - TcpServer - [TcpServer.py:194]: Server on ('127.0.0.1', 9201)
2021-06-26 22:52:17,622 - DEBUG - ServiceFinder - [EtcdSupport.py:323]: add service node info--> dispatcher_service: ('127.0.0.1', 9100)
2021-06-26 22:52:17,625 - DEBUG - ServiceFinder - [EtcdSupport.py:323]: add service node info--> lobby_server: ('127.0.0.1', 10001)
2021-06-26 22:52:17,628 - DEBUG - ServiceFinder - [EtcdSupport.py:323]: add service node info--> lobby_gate: ('127.0.0.1', 9201)
2021-06-26 22:52:17,631 - DEBUG - ServiceFinder - [EtcdSupport.py:277]: init service info from etcd success, will going to watch, at etcd index -> 127
2021-06-26 22:52:17,641 - DEBUG - ServiceRegister - [EtcdSupport.py:163]: regist service : lobby_gate success, {"action":"set","node":{"key":"/services/lobby_gate/127.0.0.1|9201","value":"","expiration":"2021-06-26T14:55:17.6173453Z","ttl":180,"modifiedIndex":128,"createdIndex":128},"prevNode":{"key":"/services/lobby_gate/127.0.0.1|9201","value":"","expiration":"2021-06-26T14:54:30.3044705Z","ttl":133,"modifiedIndex":124,"createdIndex":124}}

2021-06-26 22:52:17,651 - DEBUG - ServiceFinder - [EtcdSupport.py:422]: recv watch set service node info--> lobby_gate: ('127.0.0.1', 9201) - [128]
2021-06-26 22:52:17,654 - DEBUG - ServiceFinder - [EtcdSupport.py:299]: duplicate service info  -> lobby_gate:('127.0.0.1', 9201)
2021-06-26 22:52:49,528 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 7328) is connected !!!!
2021-06-26 22:52:49,559 - DEBUG - ServerEntity.ServerEntity - [ServerEntity.py:23]: __init__ create entity ServerEntity with id 60d73f4168df91e3522b229b mem_id=2332162774688
2021-06-26 22:52:49,562 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d73f4168df91e3522b229b 
2021-06-26 22:52:52,597 - ERROR - ProxyCliRpcHandler - [ProxyRpcHandler.py:107]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_server'], rpc_fuc_kwargs={}"
2021-06-26 22:52:55,547 - DEBUG - ServerEntity.ServerEntity - [ServerEntity.py:23]: __init__ create entity ServerEntity with id 60d73f4768df91e3522b229c mem_id=2332162775600
2021-06-26 22:52:55,550 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d73f4768df91e3522b229c 
2021-06-26 22:52:57,552 - WARNING - TcpConn - [TcpConn.py:173]: heartbeat timeout
2021-06-26 22:52:57,571 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 7332) is connected !!!!
2021-06-26 22:52:58,583 - ERROR - ProxyCliRpcHandler - [ProxyRpcHandler.py:107]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_server'], rpc_fuc_kwargs={}"
2021-06-26 22:53:03,580 - DEBUG - ServerEntity.ServerEntity - [ServerEntity.py:23]: __init__ create entity ServerEntity with id 60d73f4f68df91e3522b229d mem_id=2332162132096
2021-06-26 22:53:03,583 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d73f4f68df91e3522b229d 
2021-06-26 22:53:05,584 - WARNING - TcpConn - [TcpConn.py:173]: heartbeat timeout
2021-06-26 22:53:05,602 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 7335) is connected !!!!
2021-06-26 22:53:06,613 - ERROR - ProxyCliRpcHandler - [ProxyRpcHandler.py:107]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_server'], rpc_fuc_kwargs={}"
2021-06-26 22:53:11,614 - DEBUG - ServerEntity.ServerEntity - [ServerEntity.py:23]: __init__ create entity ServerEntity with id 60d73f5768df91e3522b229e mem_id=2332163348320
2021-06-26 22:53:11,619 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d73f5768df91e3522b229e 
2021-06-26 22:53:13,602 - WARNING - TcpConn - [TcpConn.py:173]: heartbeat timeout
2021-06-26 22:53:13,621 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 7339) is connected !!!!
2021-06-26 22:53:14,649 - ERROR - ProxyCliRpcHandler - [ProxyRpcHandler.py:107]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_server'], rpc_fuc_kwargs={}"
2021-06-26 22:53:19,623 - DEBUG - ServerEntity.ServerEntity - [ServerEntity.py:23]: __init__ create entity ServerEntity with id 60d73f5f68df91e3522b229f mem_id=2332163445184
2021-06-26 22:53:19,627 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d73f5f68df91e3522b229f 
2021-06-26 22:53:21,630 - WARNING - TcpConn - [TcpConn.py:173]: heartbeat timeout
2021-06-26 22:53:21,649 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 7344) is connected !!!!
2021-06-26 22:53:22,646 - ERROR - ProxyCliRpcHandler - [ProxyRpcHandler.py:107]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_server'], rpc_fuc_kwargs={}"
2021-06-26 22:53:27,656 - DEBUG - ServerEntity.ServerEntity - [ServerEntity.py:23]: __init__ create entity ServerEntity with id 60d73f6768df91e3522b22a0 mem_id=2332163447488
2021-06-26 22:53:27,659 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d73f6768df91e3522b22a0 
2021-06-26 22:53:27,671 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 128 -> 128
2021-06-26 22:53:29,658 - WARNING - TcpConn - [TcpConn.py:173]: heartbeat timeout
2021-06-26 22:53:29,679 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 7349) is connected !!!!
2021-06-26 22:53:30,685 - ERROR - ProxyCliRpcHandler - [ProxyRpcHandler.py:107]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_server'], rpc_fuc_kwargs={}"
2021-06-26 22:53:35,693 - DEBUG - ServerEntity.ServerEntity - [ServerEntity.py:23]: __init__ create entity ServerEntity with id 60d73f6f68df91e3522b22a1 mem_id=2332162776704
2021-06-26 22:53:35,698 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d73f6f68df91e3522b22a1 
2021-06-26 22:53:37,687 - WARNING - TcpConn - [TcpConn.py:173]: heartbeat timeout
2021-06-26 22:53:37,706 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 7353) is connected !!!!
2021-06-26 22:53:38,720 - ERROR - ProxyCliRpcHandler - [ProxyRpcHandler.py:107]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_server'], rpc_fuc_kwargs={}"
2021-06-26 22:53:43,730 - DEBUG - ServerEntity.ServerEntity - [ServerEntity.py:23]: __init__ create entity ServerEntity with id 60d73f7768df91e3522b22a2 mem_id=2332163490912
2021-06-26 22:53:43,734 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d73f7768df91e3522b22a2 
2021-06-26 22:53:45,718 - WARNING - TcpConn - [TcpConn.py:173]: heartbeat timeout
2021-06-26 22:53:45,738 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 7359) is connected !!!!
2021-06-26 22:53:46,738 - ERROR - ProxyCliRpcHandler - [ProxyRpcHandler.py:107]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_server'], rpc_fuc_kwargs={}"
2021-06-26 22:53:51,739 - DEBUG - ServerEntity.ServerEntity - [ServerEntity.py:23]: __init__ create entity ServerEntity with id 60d73f7f68df91e3522b22a3 mem_id=2332163492064
2021-06-26 22:53:51,742 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d73f7f68df91e3522b22a3 
2021-06-26 22:53:53,746 - WARNING - TcpConn - [TcpConn.py:173]: heartbeat timeout
2021-06-26 22:53:53,766 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 7363) is connected !!!!
2021-06-26 22:53:54,776 - ERROR - ProxyCliRpcHandler - [ProxyRpcHandler.py:107]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_server'], rpc_fuc_kwargs={}"
2021-06-26 22:53:56,890 - WARNING - TcpConn - [TcpConn.py:173]: connection is closed by error: [WinError 64] The specified network name is no longer available
2021-06-26 22:53:59,656 - DEBUG - ServiceRegister - [EtcdSupport.py:196]: outside, time.time()=1624719239.6540287, refresh service lobby_gate, now_url: http://127.0.0.1:2379/v2/keys/services/lobby_gate/127.0.0.1|9201
2021-06-26 22:53:59,672 - DEBUG - ServiceRegister - [EtcdSupport.py:214]: time.time()=1624719239.6691647, refresh service success: lobby_gate: {"action":"set","node":{"key":"/services/lobby_gate/127.0.0.1|9201","value":"","expiration":"2021-06-26T14:56:59.6659154Z","ttl":180,"modifiedIndex":129,"createdIndex":129},"prevNode":{"key":"/services/lobby_gate/127.0.0.1|9201","value":"","expiration":"2021-06-26T14:55:17.6173453Z","ttl":78,"modifiedIndex":128,"createdIndex":128}}
, now_url: http://127.0.0.1:2379/v2/keys/services/lobby_gate/127.0.0.1|9201
2021-06-26 22:54:28,699 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 128 -> 128
2021-06-26 22:55:29,702 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 128 -> 131
2021-06-26 22:55:42,236 - DEBUG - ServerEntity.LoadReporter - [ServerEntity.py:23]: __init__ create entity LoadReporter with id 60d73feea4a002ef61a1a518 mem_id=1915687119216
2021-06-26 22:55:42,237 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d73feea4a002ef61a1a518 
2021-06-26 22:55:42,248 - DEBUG - ServiceNode - [EtcdSupport.py:533]: we have create ServiceFinder
2021-06-26 22:55:42,257 - DEBUG - ServiceFinder - [EtcdSupport.py:352]: _init_info, now_url: http://127.0.0.1:2379/v2/keys?recursive=true
2021-06-26 22:55:42,264 - DEBUG - ServiceRegister - [EtcdSupport.py:155]: _do_regist: now_url: http://127.0.0.1:2379/v2/keys/services/lobby_gate/127.0.0.1|9201
2021-06-26 22:55:42,274 - DEBUG - TcpServer - [TcpServer.py:194]: Server on ('127.0.0.1', 9201)
2021-06-26 22:55:42,296 - DEBUG - ServiceFinder - [EtcdSupport.py:323]: add service node info--> lobby_gate: ('127.0.0.1', 9201)
2021-06-26 22:55:42,299 - DEBUG - ServiceFinder - [EtcdSupport.py:323]: add service node info--> dispatcher_service: ('127.0.0.1', 9100)
2021-06-26 22:55:42,303 - DEBUG - ServiceFinder - [EtcdSupport.py:323]: add service node info--> lobby_server: ('127.0.0.1', 10001)
2021-06-26 22:55:42,306 - DEBUG - ServiceFinder - [EtcdSupport.py:277]: init service info from etcd success, will going to watch, at etcd index -> 131
2021-06-26 22:55:42,318 - DEBUG - ServiceRegister - [EtcdSupport.py:163]: regist service : lobby_gate success, {"action":"set","node":{"key":"/services/lobby_gate/127.0.0.1|9201","value":"","expiration":"2021-06-26T14:58:42.2899932Z","ttl":180,"modifiedIndex":132,"createdIndex":132},"prevNode":{"key":"/services/lobby_gate/127.0.0.1|9201","value":"","expiration":"2021-06-26T14:56:59.6659154Z","ttl":78,"modifiedIndex":129,"createdIndex":129}}

2021-06-26 22:55:42,328 - DEBUG - ServiceFinder - [EtcdSupport.py:422]: recv watch set service node info--> lobby_gate: ('127.0.0.1', 9201) - [132]
2021-06-26 22:55:42,332 - DEBUG - ServiceFinder - [EtcdSupport.py:299]: duplicate service info  -> lobby_gate:('127.0.0.1', 9201)
2021-06-26 22:55:47,437 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 13227) is connected !!!!
2021-06-26 22:55:47,473 - DEBUG - ServerEntity.ServerEntity - [ServerEntity.py:23]: __init__ create entity ServerEntity with id 60d73ff3a4a002ef61a1a519 mem_id=1915689984544
2021-06-26 22:55:47,476 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d73ff3a4a002ef61a1a519 
2021-06-26 22:55:47,516 - CRITICAL - ProxyCliRpcHandler - [ProxyRpcHandler.py:119]: on_traceback, type:<class 'socket.gaierror'>, value:[Errno 10109] getaddrinfo failed, traceback:<class 'socket.gaierror'>
[Errno 10109] getaddrinfo failed
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\ProxyRpcHandler.py", line 112, in handle_rpc
    locals={'self': <ProxyRpcHandler.ProxyCliRpcHandler object at 0x000001BE08056040>, 'rpc_msg': b'\x96\x01\x01\xa6Avatar\xb5puppet_entity_message\x92\xd9!CompAvatarTest.puppet_chat_to_ppt\x81\xa7content\xb2puppet_chat_to_ppt\x80', 'dispatcher_json_conf_path': '../bin/win/conf/dispatcher_service.json', 'conf_file': <_io.TextIOWrapper name='../bin/win/conf/dispatcher_service.json' mode='r' encoding='cp936'>, 'dispatcher_json_conf': {'$MACRO$': {'LOBBY_SRV_IP': '127.0.0.1', 'ETCD_IP': '127.0.0.1', 'DISPATCHER_IP': '127.0.0.1', '$LOBBY_GATE_IP': '127.0.0.1'}, 'etcd_servers': [{'ip': '127.0.0.1', 'port': 2379}], 'log_path': '../bin/win/log/', 'lobby_entity_root': 'lobby_entity', 'battle_entity_root': 'battle_entity', 'server_entity_root': 'server_entity', 'component_root': 'component', 'dispatcher_0': {'ip': '127.0.0.1', 'port': 9100}}, 'rand_dispatcher_service_addr': ('127.0.0.1', 9100), '_svr_name': 'dispatcher_0', '_svr_info': {'ip': '127.0.0.1', 'port': 9100}, 'temp_se': <server_entity.ServerEntity.ServerEntity object ...
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\ConnMgr.py", line 39, in get_conn_by_addr
    locals={'self': <ConnMgr.ConnMgr object at 0x000001BE08056160>, 'addr': ('lobby_0', '127.0.0.1', 10001), 'rpc_handler': <ProxyRpcHandler.ProxyLobbyRpcHandler object at 0x000001BE07FAF070>, '_conn': None}
  File "C:\Program Files\Python38\lib\asyncio\streams.py", line 52, in open_connection
    locals={'host': 'lobby_0', 'port': '127.0.0.1', 'loop': <ProactorEventLoop running=True closed=False debug=True>, 'limit': 65536, 'kwds': {}, 'reader': <StreamReader>, 'protocol': <asyncio.streams.StreamReaderProtocol object at 0x000001BE080DD1F0>}
  File "C:\Program Files\Python38\lib\asyncio\base_events.py", line 986, in create_connection
    locals={'self': <ProactorEventLoop running=True closed=False debug=True>, 'protocol_factory': <function open_connection.<locals>.<lambda> at 0x000001BE07E33670>, 'host': 'lobby_0', 'port': '127.0.0.1', 'ssl': None, 'family': 0, 'proto': 0, 'flags': 0, 'sock': None, 'local_addr': None, 'server_hostname': None, 'ssl_handshake_timeout': None, 'happy_eyeballs_delay': None, 'interleave': None}
  File "C:\Program Files\Python38\lib\asyncio\base_events.py", line 1365, in _ensure_resolved
    locals={'self': <ProactorEventLoop running=True closed=False debug=True>, 'address': ('lobby_0', '127.0.0.1'), 'family': 0, 'type': <SocketKind.SOCK_STREAM: 1>, 'proto': 0, 'flags': 0, 'loop': <ProactorEventLoop running=True closed=False debug=True>, 'host': 'lobby_0', 'port': '127.0.0.1', 'info': None}
  File "C:\Program Files\Python38\lib\asyncio\base_events.py", line 825, in getaddrinfo
    locals={'self': <ProactorEventLoop running=True closed=False debug=True>, 'host': 'lobby_0', 'port': '127.0.0.1', 'family': 0, 'type': <SocketKind.SOCK_STREAM: 1>, 'proto': 0, 'flags': 0, 'getaddr_func': <bound method BaseEventLoop._getaddrinfo_debug of <ProactorEventLoop running=True closed=False debug=True>>}
  File "C:\Program Files\Python38\lib\concurrent\futures\thread.py", line 57, in run
    locals={}
  File "C:\Program Files\Python38\lib\asyncio\base_events.py", line 808, in _getaddrinfo_debug
    locals={'self': <ProactorEventLoop running=True closed=False debug=True>, 'host': 'lobby_0', 'port': '127.0.0.1', 'family': 0, 'type': <SocketKind.SOCK_STREAM: 1>, 'proto': 0, 'flags': 0, 'msg': "lobby_0:'127.0.0.1', type=<SocketKind.SOCK_STREAM: 1>", 't0': 621224.796}
  File "C:\Program Files\Python38\lib\socket.py", line 918, in getaddrinfo
    locals={'host': 'lobby_0', 'port': '127.0.0.1', 'family': 0, 'type': <SocketKind.SOCK_STREAM: 1>, 'proto': 0, 'flags': 0, 'addrlist': []}
2021-06-26 22:55:53,456 - DEBUG - ServerEntity.ServerEntity - [ServerEntity.py:23]: __init__ create entity ServerEntity with id 60d73ff9a4a002ef61a1a51a mem_id=1915689984592
2021-06-26 22:55:53,459 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d73ff9a4a002ef61a1a51a 
2021-06-26 22:55:55,463 - WARNING - TcpConn - [TcpConn.py:173]: heartbeat timeout
2021-06-26 22:55:55,480 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 13243) is connected !!!!
2021-06-26 22:55:56,489 - ERROR - ProxyCliRpcHandler - [ProxyRpcHandler.py:107]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_server'], rpc_fuc_kwargs={}"
2021-06-26 22:56:01,485 - DEBUG - ServerEntity.ServerEntity - [ServerEntity.py:23]: __init__ create entity ServerEntity with id 60d74001a4a002ef61a1a51b mem_id=1915689986320
2021-06-26 22:56:01,489 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d74001a4a002ef61a1a51b 
2021-06-26 22:56:03,511 - WARNING - TcpConn - [TcpConn.py:173]: heartbeat timeout
2021-06-26 22:56:03,530 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 13247) is connected !!!!
2021-06-26 22:56:04,524 - ERROR - ProxyCliRpcHandler - [ProxyRpcHandler.py:107]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_server'], rpc_fuc_kwargs={}"
2021-06-26 22:59:26,172 - DEBUG - ServerEntity.LoadReporter - [ServerEntity.py:23]: __init__ create entity LoadReporter with id 60d740ce64bb1ca1ed3150c5 mem_id=1992727765968
2021-06-26 22:59:26,172 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d740ce64bb1ca1ed3150c5 
2021-06-26 22:59:26,184 - DEBUG - ServiceNode - [EtcdSupport.py:533]: we have create ServiceFinder
2021-06-26 22:59:26,193 - DEBUG - ServiceFinder - [EtcdSupport.py:352]: _init_info, now_url: http://127.0.0.1:2379/v2/keys?recursive=true
2021-06-26 22:59:26,198 - DEBUG - ServiceRegister - [EtcdSupport.py:155]: _do_regist: now_url: http://127.0.0.1:2379/v2/keys/services/lobby_gate/127.0.0.1|9201
2021-06-26 22:59:26,208 - DEBUG - TcpServer - [TcpServer.py:194]: Server on ('127.0.0.1', 9201)
2021-06-26 22:59:26,229 - DEBUG - ServiceFinder - [EtcdSupport.py:323]: add service node info--> dispatcher_service: ('127.0.0.1', 9100)
2021-06-26 22:59:26,232 - DEBUG - ServiceFinder - [EtcdSupport.py:323]: add service node info--> lobby_server: ('127.0.0.1', 10001)
2021-06-26 22:59:26,235 - DEBUG - ServiceFinder - [EtcdSupport.py:277]: init service info from etcd success, will going to watch, at etcd index -> 139
2021-06-26 22:59:26,245 - DEBUG - ServiceRegister - [EtcdSupport.py:163]: regist service : lobby_gate success, {"action":"set","node":{"key":"/services/lobby_gate/127.0.0.1|9201","value":"","expiration":"2021-06-26T15:02:26.2246866Z","ttl":180,"modifiedIndex":140,"createdIndex":140}}

2021-06-26 22:59:26,257 - DEBUG - ServiceFinder - [EtcdSupport.py:422]: recv watch set service node info--> lobby_gate: ('127.0.0.1', 9201) - [140]
2021-06-26 22:59:31,236 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 11668) is connected !!!!
2021-06-26 22:59:31,281 - DEBUG - ServerEntity.ServerEntity - [ServerEntity.py:23]: __init__ create entity ServerEntity with id 60d740d364bb1ca1ed3150c6 mem_id=1992730137024
2021-06-26 22:59:31,284 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d740d364bb1ca1ed3150c6 
2021-06-26 22:59:37,254 - CRITICAL - ProxyCliRpcHandler - [ProxyRpcHandler.py:123]: on_traceback, type:<class 'UnboundLocalError'>, value:local variable '_lobby_addr' referenced before assignment, traceback:<class 'UnboundLocalError'>
local variable '_lobby_addr' referenced before assignment
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\ProxyRpcHandler.py", line 119, in handle_rpc
    locals={'self': <ProxyRpcHandler.ProxyCliRpcHandler object at 0x000001CFF7E49BE0>, 'rpc_msg': b'\x91\x03'}
2021-06-26 22:59:39,233 - WARNING - TcpConn - [TcpConn.py:173]: heartbeat timeout
2021-06-26 22:59:39,254 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 11678) is connected !!!!
2021-06-26 22:59:39,326 - WARNING - TcpConn - [TcpConn.py:173]: heartbeat timeout
2021-06-26 22:59:45,270 - DEBUG - ServerEntity.ServerEntity - [ServerEntity.py:23]: __init__ create entity ServerEntity with id 60d740e164bb1ca1ed3150c7 mem_id=1992730662752
2021-06-26 22:59:45,274 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d740e164bb1ca1ed3150c7 
2021-06-26 22:59:47,271 - WARNING - TcpConn - [TcpConn.py:173]: heartbeat timeout
2021-06-26 22:59:47,291 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 11683) is connected !!!!
2021-06-26 22:59:47,332 - WARNING - TcpConn - [TcpConn.py:173]: heartbeat timeout
2021-06-26 22:59:48,302 - ERROR - ProxyCliRpcHandler - [ProxyRpcHandler.py:107]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_server'], rpc_fuc_kwargs={}"
2021-06-26 22:59:53,299 - DEBUG - ServerEntity.ServerEntity - [ServerEntity.py:23]: __init__ create entity ServerEntity with id 60d740e964bb1ca1ed3150c8 mem_id=1992730664528
2021-06-26 22:59:53,303 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d740e964bb1ca1ed3150c8 
2021-06-26 22:59:55,307 - WARNING - TcpConn - [TcpConn.py:173]: heartbeat timeout
2021-06-26 22:59:55,327 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 11688) is connected !!!!
2021-06-26 22:59:55,332 - WARNING - TcpConn - [TcpConn.py:173]: heartbeat timeout
2021-06-26 22:59:56,319 - ERROR - ProxyCliRpcHandler - [ProxyRpcHandler.py:107]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_server'], rpc_fuc_kwargs={}"
2021-06-26 23:00:01,340 - DEBUG - ServerEntity.ServerEntity - [ServerEntity.py:23]: __init__ create entity ServerEntity with id 60d740f164bb1ca1ed3150c9 mem_id=1992730662896
2021-06-26 23:00:01,343 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d740f164bb1ca1ed3150c9 
2021-06-26 23:00:03,352 - WARNING - TcpConn - [TcpConn.py:173]: heartbeat timeout
2021-06-26 23:00:03,356 - WARNING - TcpConn - [TcpConn.py:173]: heartbeat timeout
2021-06-26 23:00:03,376 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 11696) is connected !!!!
2021-06-26 23:00:04,369 - ERROR - ProxyCliRpcHandler - [ProxyRpcHandler.py:107]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_server'], rpc_fuc_kwargs={}"
2021-06-26 23:00:09,392 - DEBUG - ServerEntity.ServerEntity - [ServerEntity.py:23]: __init__ create entity ServerEntity with id 60d740f964bb1ca1ed3150ca mem_id=1992730136832
2021-06-26 23:00:09,395 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d740f964bb1ca1ed3150ca 
2021-06-26 23:00:11,381 - WARNING - TcpConn - [TcpConn.py:173]: heartbeat timeout
2021-06-26 23:00:11,385 - WARNING - TcpConn - [TcpConn.py:173]: heartbeat timeout
2021-06-26 23:00:11,411 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 11701) is connected !!!!
2021-06-26 23:00:12,427 - CRITICAL - ProxyCliRpcHandler - [ProxyRpcHandler.py:123]: on_traceback, type:<class 'OSError'>, value:[Errno 22] Invalid argument, traceback:<class 'OSError'>
[Errno 22] Invalid argument
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\ProxyRpcHandler.py", line 104, in handle_rpc
    locals={'self': <ProxyRpcHandler.ProxyCliRpcHandler object at 0x000001CFF803B640>, 'rpc_msg': b'\x91\x03', 'dispatcher_json_conf_path': '../bin/win/conf/dispatcher_service.json', 'conf_file': <_io.TextIOWrapper name='../bin/win/conf/dispatcher_service.json' mode='r' encoding='cp936'>, 'dispatcher_json_conf': {'$MACRO$': {'LOBBY_SRV_IP': '127.0.0.1', 'ETCD_IP': '127.0.0.1', 'DISPATCHER_IP': '127.0.0.1', '$LOBBY_GATE_IP': '127.0.0.1'}, 'etcd_servers': [{'ip': '127.0.0.1', 'port': 2379}], 'log_path': '../bin/win/log/', 'lobby_entity_root': 'lobby_entity', 'battle_entity_root': 'battle_entity', 'server_entity_root': 'server_entity', 'component_root': 'component', 'dispatcher_0': {'ip': '127.0.0.1', 'port': 9100}}, 'rand_dispatcher_service_addr': ('127.0.0.1', 9100), '_svr_name': 'dispatcher_0', '_svr_info': {'ip': '127.0.0.1', 'port': 9100}, 'temp_se': <server_entity.ServerEntity.ServerEntity object at 0x000001CFF7F8D100>, 'start_time': 1624719609.3988316, '_err': "request rpc timeout, rpc_fuc_name='pick_lowest_load_ser...
2021-06-26 23:00:14,252 - CRITICAL - ServerEntity.LoadReporter - [LoadReporter.py:44]: on_traceback, type:<class 'OSError'>, value:[Errno 22] Invalid argument, traceback:<class 'OSError'>
[Errno 22] Invalid argument
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\server_entity\LoadReporter.py", line 40, in report_load
    locals={'self': <server_entity.LoadReporter.LoadReporter object at 0x000001CFF7D4A3D0>, 'dispatcher_service_addr': ('127.0.0.1', 9100)}
2021-06-26 23:00:17,432 - DEBUG - ServerEntity.ServerEntity - [ServerEntity.py:23]: __init__ create entity ServerEntity with id 60d7410164bb1ca1ed3150cb mem_id=1992730852272
2021-06-26 23:00:17,437 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d7410164bb1ca1ed3150cb 
2021-06-26 23:00:17,446 - CRITICAL - ProxyCliRpcHandler - [ProxyRpcHandler.py:123]: on_traceback, type:<class 'OSError'>, value:[Errno 22] Invalid argument, traceback:<class 'OSError'>
[Errno 22] Invalid argument
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\ProxyRpcHandler.py", line 90, in handle_rpc
    locals={'self': <ProxyRpcHandler.ProxyCliRpcHandler object at 0x000001CFF803BF40>, 'rpc_msg': b'\x91\x03', 'dispatcher_json_conf_path': '../bin/win/conf/dispatcher_service.json', 'conf_file': <_io.TextIOWrapper name='../bin/win/conf/dispatcher_service.json' mode='r' encoding='cp936'>, 'dispatcher_json_conf': {'$MACRO$': {'LOBBY_SRV_IP': '127.0.0.1', 'ETCD_IP': '127.0.0.1', 'DISPATCHER_IP': '127.0.0.1', '$LOBBY_GATE_IP': '127.0.0.1'}, 'etcd_servers': [{'ip': '127.0.0.1', 'port': 2379}], 'log_path': '../bin/win/log/', 'lobby_entity_root': 'lobby_entity', 'battle_entity_root': 'battle_entity', 'server_entity_root': 'server_entity', 'component_root': 'component', 'dispatcher_0': {'ip': '127.0.0.1', 'port': 9100}}, 'rand_dispatcher_service_addr': ('127.0.0.1', 9100), '_svr_name': 'dispatcher_0', '_svr_info': {'ip': '127.0.0.1', 'port': 9100}, 'temp_se': <server_entity.ServerEntity.ServerEntity object at 0x000001CFF803BBB0>, 'start_time': 1624719617.442966}
2021-06-26 23:00:19,400 - WARNING - TcpConn - [TcpConn.py:173]: heartbeat timeout
2021-06-26 23:00:19,408 - WARNING - TcpConn - [TcpConn.py:173]: heartbeat timeout
2021-06-26 23:00:19,430 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 11706) is connected !!!!
2021-06-26 23:00:20,270 - CRITICAL - ServerEntity.LoadReporter - [LoadReporter.py:44]: on_traceback, type:<class 'OSError'>, value:[Errno 22] Invalid argument, traceback:<class 'OSError'>
[Errno 22] Invalid argument
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\server_entity\LoadReporter.py", line 40, in report_load
    locals={'self': <server_entity.LoadReporter.LoadReporter object at 0x000001CFF7D4A3D0>, 'dispatcher_service_addr': ('127.0.0.1', 9100)}
2021-06-26 23:00:25,432 - DEBUG - ServerEntity.ServerEntity - [ServerEntity.py:23]: __init__ create entity ServerEntity with id 60d7410964bb1ca1ed3150cc mem_id=1992730863264
2021-06-26 23:00:25,437 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d7410964bb1ca1ed3150cc 
2021-06-26 23:00:25,448 - CRITICAL - ProxyCliRpcHandler - [ProxyRpcHandler.py:123]: on_traceback, type:<class 'OSError'>, value:[Errno 22] Invalid argument, traceback:<class 'OSError'>
[Errno 22] Invalid argument
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\ProxyRpcHandler.py", line 90, in handle_rpc
    locals={'self': <ProxyRpcHandler.ProxyCliRpcHandler object at 0x000001CFF800D5E0>, 'rpc_msg': b'\x91\x03', 'dispatcher_json_conf_path': '../bin/win/conf/dispatcher_service.json', 'conf_file': <_io.TextIOWrapper name='../bin/win/conf/dispatcher_service.json' mode='r' encoding='cp936'>, 'dispatcher_json_conf': {'$MACRO$': {'LOBBY_SRV_IP': '127.0.0.1', 'ETCD_IP': '127.0.0.1', 'DISPATCHER_IP': '127.0.0.1', '$LOBBY_GATE_IP': '127.0.0.1'}, 'etcd_servers': [{'ip': '127.0.0.1', 'port': 2379}], 'log_path': '../bin/win/log/', 'lobby_entity_root': 'lobby_entity', 'battle_entity_root': 'battle_entity', 'server_entity_root': 'server_entity', 'component_root': 'component', 'dispatcher_0': {'ip': '127.0.0.1', 'port': 9100}}, 'rand_dispatcher_service_addr': ('127.0.0.1', 9100), '_svr_name': 'dispatcher_0', '_svr_info': {'ip': '127.0.0.1', 'port': 9100}, 'temp_se': <server_entity.ServerEntity.ServerEntity object at 0x000001CFF803E6A0>, 'start_time': 1624719625.4424982}
2021-06-26 23:00:26,290 - CRITICAL - ServerEntity.LoadReporter - [LoadReporter.py:44]: on_traceback, type:<class 'OSError'>, value:[Errno 22] Invalid argument, traceback:<class 'OSError'>
[Errno 22] Invalid argument
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\server_entity\LoadReporter.py", line 40, in report_load
    locals={'self': <server_entity.LoadReporter.LoadReporter object at 0x000001CFF7D4A3D0>, 'dispatcher_service_addr': ('127.0.0.1', 9100)}
2021-06-26 23:00:27,422 - WARNING - TcpConn - [TcpConn.py:173]: heartbeat timeout
2021-06-26 23:00:27,428 - WARNING - TcpConn - [TcpConn.py:173]: heartbeat timeout
2021-06-26 23:00:27,460 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 11718) is connected !!!!
2021-06-26 23:00:32,312 - CRITICAL - ServerEntity.LoadReporter - [LoadReporter.py:44]: on_traceback, type:<class 'OSError'>, value:[Errno 22] Invalid argument, traceback:<class 'OSError'>
[Errno 22] Invalid argument
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\server_entity\LoadReporter.py", line 40, in report_load
    locals={'self': <server_entity.LoadReporter.LoadReporter object at 0x000001CFF7D4A3D0>, 'dispatcher_service_addr': ('127.0.0.1', 9100)}
2021-06-26 23:00:33,466 - DEBUG - ServerEntity.ServerEntity - [ServerEntity.py:23]: __init__ create entity ServerEntity with id 60d7411164bb1ca1ed3150cd mem_id=1992730861920
2021-06-26 23:00:33,471 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d7411164bb1ca1ed3150cd 
2021-06-26 23:00:33,481 - CRITICAL - ProxyCliRpcHandler - [ProxyRpcHandler.py:123]: on_traceback, type:<class 'OSError'>, value:[Errno 22] Invalid argument, traceback:<class 'OSError'>
[Errno 22] Invalid argument
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\ProxyRpcHandler.py", line 90, in handle_rpc
    locals={'self': <ProxyRpcHandler.ProxyCliRpcHandler object at 0x000001CFF7EF3880>, 'rpc_msg': b'\x91\x03', 'dispatcher_json_conf_path': '../bin/win/conf/dispatcher_service.json', 'conf_file': <_io.TextIOWrapper name='../bin/win/conf/dispatcher_service.json' mode='r' encoding='cp936'>, 'dispatcher_json_conf': {'$MACRO$': {'LOBBY_SRV_IP': '127.0.0.1', 'ETCD_IP': '127.0.0.1', 'DISPATCHER_IP': '127.0.0.1', '$LOBBY_GATE_IP': '127.0.0.1'}, 'etcd_servers': [{'ip': '127.0.0.1', 'port': 2379}], 'log_path': '../bin/win/log/', 'lobby_entity_root': 'lobby_entity', 'battle_entity_root': 'battle_entity', 'server_entity_root': 'server_entity', 'component_root': 'component', 'dispatcher_0': {'ip': '127.0.0.1', 'port': 9100}}, 'rand_dispatcher_service_addr': ('127.0.0.1', 9100), '_svr_name': 'dispatcher_0', '_svr_info': {'ip': '127.0.0.1', 'port': 9100}, 'temp_se': <server_entity.ServerEntity.ServerEntity object at 0x000001CFF803E160>, 'start_time': 1624719633.4764256}
2021-06-26 23:00:35,460 - WARNING - TcpConn - [TcpConn.py:173]: heartbeat timeout
2021-06-26 23:00:35,465 - WARNING - TcpConn - [TcpConn.py:173]: heartbeat timeout
2021-06-26 23:00:35,492 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 11729) is connected !!!!
2021-06-26 23:00:36,275 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 140 -> 140
2021-06-26 23:00:38,323 - CRITICAL - ServerEntity.LoadReporter - [LoadReporter.py:44]: on_traceback, type:<class 'OSError'>, value:[Errno 22] Invalid argument, traceback:<class 'OSError'>
[Errno 22] Invalid argument
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\server_entity\LoadReporter.py", line 40, in report_load
    locals={'self': <server_entity.LoadReporter.LoadReporter object at 0x000001CFF7D4A3D0>, 'dispatcher_service_addr': ('127.0.0.1', 9100)}
2021-06-26 23:00:41,507 - DEBUG - ServerEntity.ServerEntity - [ServerEntity.py:23]: __init__ create entity ServerEntity with id 60d7411964bb1ca1ed3150ce mem_id=1992730903504
2021-06-26 23:00:41,510 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d7411964bb1ca1ed3150ce 
2021-06-26 23:00:41,517 - CRITICAL - ProxyCliRpcHandler - [ProxyRpcHandler.py:123]: on_traceback, type:<class 'OSError'>, value:[Errno 22] Invalid argument, traceback:<class 'OSError'>
[Errno 22] Invalid argument
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\ProxyRpcHandler.py", line 90, in handle_rpc
    locals={'self': <ProxyRpcHandler.ProxyCliRpcHandler object at 0x000001CFF803EFD0>, 'rpc_msg': b'\x91\x03', 'dispatcher_json_conf_path': '../bin/win/conf/dispatcher_service.json', 'conf_file': <_io.TextIOWrapper name='../bin/win/conf/dispatcher_service.json' mode='r' encoding='cp936'>, 'dispatcher_json_conf': {'$MACRO$': {'LOBBY_SRV_IP': '127.0.0.1', 'ETCD_IP': '127.0.0.1', 'DISPATCHER_IP': '127.0.0.1', '$LOBBY_GATE_IP': '127.0.0.1'}, 'etcd_servers': [{'ip': '127.0.0.1', 'port': 2379}], 'log_path': '../bin/win/log/', 'lobby_entity_root': 'lobby_entity', 'battle_entity_root': 'battle_entity', 'server_entity_root': 'server_entity', 'component_root': 'component', 'dispatcher_0': {'ip': '127.0.0.1', 'port': 9100}}, 'rand_dispatcher_service_addr': ('127.0.0.1', 9100), '_svr_name': 'dispatcher_0', '_svr_info': {'ip': '127.0.0.1', 'port': 9100}, 'temp_se': <server_entity.ServerEntity.ServerEntity object at 0x000001CFF80483D0>, 'start_time': 1624719641.5147161}
2021-06-26 23:00:43,480 - WARNING - TcpConn - [TcpConn.py:173]: heartbeat timeout
2021-06-26 23:00:43,491 - WARNING - TcpConn - [TcpConn.py:173]: heartbeat timeout
2021-06-26 23:00:43,514 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 11738) is connected !!!!
2021-06-26 23:00:44,350 - CRITICAL - ServerEntity.LoadReporter - [LoadReporter.py:44]: on_traceback, type:<class 'OSError'>, value:[Errno 22] Invalid argument, traceback:<class 'OSError'>
[Errno 22] Invalid argument
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\server_entity\LoadReporter.py", line 40, in report_load
    locals={'self': <server_entity.LoadReporter.LoadReporter object at 0x000001CFF7D4A3D0>, 'dispatcher_service_addr': ('127.0.0.1', 9100)}
2021-06-26 23:00:49,514 - DEBUG - ServerEntity.ServerEntity - [ServerEntity.py:23]: __init__ create entity ServerEntity with id 60d7412164bb1ca1ed3150cf mem_id=1992730862976
2021-06-26 23:00:49,517 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d7412164bb1ca1ed3150cf 
2021-06-26 23:00:49,523 - CRITICAL - ProxyCliRpcHandler - [ProxyRpcHandler.py:123]: on_traceback, type:<class 'OSError'>, value:[Errno 22] Invalid argument, traceback:<class 'OSError'>
[Errno 22] Invalid argument
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\ProxyRpcHandler.py", line 90, in handle_rpc
    locals={'self': <ProxyRpcHandler.ProxyCliRpcHandler object at 0x000001CFF803EFA0>, 'rpc_msg': b'\x91\x03', 'dispatcher_json_conf_path': '../bin/win/conf/dispatcher_service.json', 'conf_file': <_io.TextIOWrapper name='../bin/win/conf/dispatcher_service.json' mode='r' encoding='cp936'>, 'dispatcher_json_conf': {'$MACRO$': {'LOBBY_SRV_IP': '127.0.0.1', 'ETCD_IP': '127.0.0.1', 'DISPATCHER_IP': '127.0.0.1', '$LOBBY_GATE_IP': '127.0.0.1'}, 'etcd_servers': [{'ip': '127.0.0.1', 'port': 2379}], 'log_path': '../bin/win/log/', 'lobby_entity_root': 'lobby_entity', 'battle_entity_root': 'battle_entity', 'server_entity_root': 'server_entity', 'component_root': 'component', 'dispatcher_0': {'ip': '127.0.0.1', 'port': 9100}}, 'rand_dispatcher_service_addr': ('127.0.0.1', 9100), '_svr_name': 'dispatcher_0', '_svr_info': {'ip': '127.0.0.1', 'port': 9100}, 'temp_se': <server_entity.ServerEntity.ServerEntity object at 0x000001CFF803E580>, 'start_time': 1624719649.520936}
2021-06-26 23:00:50,360 - CRITICAL - ServerEntity.LoadReporter - [LoadReporter.py:44]: on_traceback, type:<class 'OSError'>, value:[Errno 22] Invalid argument, traceback:<class 'OSError'>
[Errno 22] Invalid argument
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\server_entity\LoadReporter.py", line 40, in report_load
    locals={'self': <server_entity.LoadReporter.LoadReporter object at 0x000001CFF7D4A3D0>, 'dispatcher_service_addr': ('127.0.0.1', 9100)}
2021-06-26 23:00:51,512 - WARNING - TcpConn - [TcpConn.py:173]: heartbeat timeout
2021-06-26 23:00:51,519 - WARNING - TcpConn - [TcpConn.py:173]: heartbeat timeout
2021-06-26 23:00:51,542 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 11745) is connected !!!!
2021-06-26 23:00:53,144 - WARNING - TcpConn - [TcpConn.py:173]: connection is closed by error: [WinError 64] The specified network name is no longer available
2021-06-26 23:00:55,181 - ERROR - ProxyLobbyRpcHandler - [RpcHandler.py:193]: [WinError 1225] The remote computer refused the network connection
2021-06-26 23:00:55,184 - WARNING - ProxyLobbyRpcHandler - [RpcHandler.py:195]: try reconnect ('127.0.0.1', 10001) ... 1
2021-06-26 23:00:55,800 - WARNING - ProxyLobbyRpcHandler - [RpcHandler.py:185]: bbb _try_connect_times=1, id(self._conn)= 1992729506432
2021-06-26 23:00:56,364 - CRITICAL - ServerEntity.LoadReporter - [LoadReporter.py:44]: on_traceback, type:<class 'OSError'>, value:[Errno 22] Invalid argument, traceback:<class 'OSError'>
[Errno 22] Invalid argument
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\server_entity\LoadReporter.py", line 40, in report_load
    locals={'self': <server_entity.LoadReporter.LoadReporter object at 0x000001CFF7D4A3D0>, 'dispatcher_service_addr': ('127.0.0.1', 9100)}
2021-06-26 23:00:57,379 - WARNING - TcpConn - [TcpConn.py:173]: connection is closed by error: [WinError 64] The specified network name is no longer available
2021-06-26 23:00:57,834 - ERROR - ProxyLobbyRpcHandler - [RpcHandler.py:193]: [WinError 1225] The remote computer refused the network connection
2021-06-26 23:00:57,838 - WARNING - ProxyLobbyRpcHandler - [RpcHandler.py:195]: try reconnect ('127.0.0.1', 10001) ... 2
2021-06-26 23:00:58,456 - WARNING - ProxyLobbyRpcHandler - [RpcHandler.py:185]: bbb _try_connect_times=2, id(self._conn)= 1992729506432
2021-06-26 23:01:23,759 - DEBUG - ServerEntity.LoadReporter - [ServerEntity.py:23]: __init__ create entity LoadReporter with id 60d74143277eeb35eba36988 mem_id=1286161938704
2021-06-26 23:01:23,761 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d74143277eeb35eba36988 
2021-06-26 23:01:23,776 - DEBUG - ServiceNode - [EtcdSupport.py:533]: we have create ServiceFinder
2021-06-26 23:01:23,787 - DEBUG - ServiceFinder - [EtcdSupport.py:352]: _init_info, now_url: http://127.0.0.1:2379/v2/keys?recursive=true
2021-06-26 23:01:23,799 - DEBUG - ServiceRegister - [EtcdSupport.py:155]: _do_regist: now_url: http://127.0.0.1:2379/v2/keys/services/lobby_gate/127.0.0.1|9201
2021-06-26 23:01:23,814 - DEBUG - TcpServer - [TcpServer.py:194]: Server on ('127.0.0.1', 9201)
2021-06-26 23:01:23,846 - DEBUG - ServiceFinder - [EtcdSupport.py:323]: add service node info--> dispatcher_service: ('127.0.0.1', 9100)
2021-06-26 23:01:23,851 - DEBUG - ServiceFinder - [EtcdSupport.py:323]: add service node info--> lobby_server: ('127.0.0.1', 10001)
2021-06-26 23:01:23,856 - DEBUG - ServiceFinder - [EtcdSupport.py:323]: add service node info--> lobby_gate: ('127.0.0.1', 9201)
2021-06-26 23:01:23,862 - DEBUG - ServiceFinder - [EtcdSupport.py:277]: init service info from etcd success, will going to watch, at etcd index -> 141
2021-06-26 23:01:23,875 - DEBUG - ServiceRegister - [EtcdSupport.py:163]: regist service : lobby_gate success, {"action":"set","node":{"key":"/services/lobby_gate/127.0.0.1|9201","value":"","expiration":"2021-06-26T15:04:23.8393235Z","ttl":180,"modifiedIndex":142,"createdIndex":142},"prevNode":{"key":"/services/lobby_gate/127.0.0.1|9201","value":"","expiration":"2021-06-26T15:02:26.2246866Z","ttl":63,"modifiedIndex":140,"createdIndex":140}}

2021-06-26 23:01:23,889 - DEBUG - ServiceFinder - [EtcdSupport.py:422]: recv watch set service node info--> lobby_gate: ('127.0.0.1', 9201) - [142]
2021-06-26 23:01:23,892 - DEBUG - ServiceFinder - [EtcdSupport.py:299]: duplicate service info  -> lobby_gate:('127.0.0.1', 9201)
2021-06-26 23:01:26,207 - DEBUG - ServiceFinder - [EtcdSupport.py:422]: recv watch set service node info--> lobby_server: ('127.0.0.1', 10001) - [143]
2021-06-26 23:01:26,210 - DEBUG - ServiceFinder - [EtcdSupport.py:299]: duplicate service info  -> lobby_server:('127.0.0.1', 10001)
2021-06-26 23:02:26,245 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 143 -> 143
2021-06-26 23:03:07,868 - DEBUG - ServiceRegister - [EtcdSupport.py:196]: outside, time.time()=1624719787.865189, refresh service lobby_gate, now_url: http://127.0.0.1:2379/v2/keys/services/lobby_gate/127.0.0.1|9201
2021-06-26 23:03:07,899 - DEBUG - ServiceRegister - [EtcdSupport.py:214]: time.time()=1624719787.896136, refresh service success: lobby_gate: {"action":"set","node":{"key":"/services/lobby_gate/127.0.0.1|9201","value":"","expiration":"2021-06-26T15:06:07.8926149Z","ttl":180,"modifiedIndex":146,"createdIndex":146},"prevNode":{"key":"/services/lobby_gate/127.0.0.1|9201","value":"","expiration":"2021-06-26T15:04:23.8393235Z","ttl":76,"modifiedIndex":142,"createdIndex":142}}
, now_url: http://127.0.0.1:2379/v2/keys/services/lobby_gate/127.0.0.1|9201
2021-06-26 23:03:35,274 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 143 -> 143
2021-06-26 23:04:37,295 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 143 -> 146
2021-06-26 23:04:51,930 - DEBUG - ServiceRegister - [EtcdSupport.py:196]: outside, time.time()=1624719891.9273443, refresh service lobby_gate, now_url: http://127.0.0.1:2379/v2/keys/services/lobby_gate/127.0.0.1|9201
2021-06-26 23:04:51,946 - DEBUG - ServiceRegister - [EtcdSupport.py:214]: time.time()=1624719891.943867, refresh service success: lobby_gate: {"action":"set","node":{"key":"/services/lobby_gate/127.0.0.1|9201","value":"","expiration":"2021-06-26T15:07:51.9403692Z","ttl":180,"modifiedIndex":148,"createdIndex":148},"prevNode":{"key":"/services/lobby_gate/127.0.0.1|9201","value":"","expiration":"2021-06-26T15:06:07.8926149Z","ttl":76,"modifiedIndex":146,"createdIndex":146}}
, now_url: http://127.0.0.1:2379/v2/keys/services/lobby_gate/127.0.0.1|9201
2021-06-26 23:05:16,133 - DEBUG - ServerEntity.LoadReporter - [ServerEntity.py:23]: __init__ create entity LoadReporter with id 60d7422c7c1f34695f2df91b mem_id=2682385388544
2021-06-26 23:05:16,134 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d7422c7c1f34695f2df91b 
2021-06-26 23:05:16,146 - DEBUG - ServiceNode - [EtcdSupport.py:533]: we have create ServiceFinder
2021-06-26 23:05:16,155 - DEBUG - ServiceFinder - [EtcdSupport.py:352]: _init_info, now_url: http://127.0.0.1:2379/v2/keys?recursive=true
2021-06-26 23:05:16,161 - DEBUG - ServiceRegister - [EtcdSupport.py:155]: _do_regist: now_url: http://127.0.0.1:2379/v2/keys/services/lobby_gate/127.0.0.1|9201
2021-06-26 23:05:16,170 - DEBUG - TcpServer - [TcpServer.py:194]: Server on ('127.0.0.1', 9201)
2021-06-26 23:05:16,189 - DEBUG - ServiceFinder - [EtcdSupport.py:323]: add service node info--> lobby_server: ('127.0.0.1', 10001)
2021-06-26 23:05:16,192 - DEBUG - ServiceFinder - [EtcdSupport.py:323]: add service node info--> lobby_gate: ('127.0.0.1', 9201)
2021-06-26 23:05:16,195 - DEBUG - ServiceFinder - [EtcdSupport.py:323]: add service node info--> dispatcher_service: ('127.0.0.1', 9100)
2021-06-26 23:05:16,199 - DEBUG - ServiceFinder - [EtcdSupport.py:277]: init service info from etcd success, will going to watch, at etcd index -> 150
2021-06-26 23:05:16,208 - DEBUG - ServiceRegister - [EtcdSupport.py:163]: regist service : lobby_gate success, {"action":"set","node":{"key":"/services/lobby_gate/127.0.0.1|9201","value":"","expiration":"2021-06-26T15:08:16.1847014Z","ttl":180,"modifiedIndex":151,"createdIndex":151},"prevNode":{"key":"/services/lobby_gate/127.0.0.1|9201","value":"","expiration":"2021-06-26T15:07:51.9403692Z","ttl":156,"modifiedIndex":148,"createdIndex":148}}

2021-06-26 23:05:16,219 - DEBUG - ServiceFinder - [EtcdSupport.py:422]: recv watch set service node info--> lobby_gate: ('127.0.0.1', 9201) - [151]
2021-06-26 23:05:16,221 - DEBUG - ServiceFinder - [EtcdSupport.py:299]: duplicate service info  -> lobby_gate:('127.0.0.1', 9201)
2021-06-26 23:05:20,957 - DEBUG - ServiceFinder - [EtcdSupport.py:422]: recv watch set service node info--> lobby_server: ('127.0.0.1', 10001) - [152]
2021-06-26 23:05:20,960 - DEBUG - ServiceFinder - [EtcdSupport.py:299]: duplicate service info  -> lobby_server:('127.0.0.1', 10001)
2021-06-26 23:06:26,983 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 152 -> 152
2021-06-26 23:06:56,227 - DEBUG - ServiceRegister - [EtcdSupport.py:196]: outside, time.time()=1624720016.2238512, refresh service lobby_gate, now_url: http://127.0.0.1:2379/v2/keys/services/lobby_gate/127.0.0.1|9201
2021-06-26 23:06:56,244 - DEBUG - ServiceRegister - [EtcdSupport.py:214]: time.time()=1624720016.241895, refresh service success: lobby_gate: {"action":"set","node":{"key":"/services/lobby_gate/127.0.0.1|9201","value":"","expiration":"2021-06-26T15:09:56.2398715Z","ttl":180,"modifiedIndex":153,"createdIndex":153},"prevNode":{"key":"/services/lobby_gate/127.0.0.1|9201","value":"","expiration":"2021-06-26T15:08:16.1847014Z","ttl":80,"modifiedIndex":151,"createdIndex":151}}
, now_url: http://127.0.0.1:2379/v2/keys/services/lobby_gate/127.0.0.1|9201
2021-06-26 23:07:03,023 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 2111) is connected !!!!
2021-06-26 23:07:03,055 - DEBUG - ServerEntity.ServerEntity - [ServerEntity.py:23]: __init__ create entity ServerEntity with id 60d742977c1f34695f2df91c mem_id=2682388260416
2021-06-26 23:07:03,058 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d742977c1f34695f2df91c 
2021-06-26 23:07:06,087 - ERROR - ProxyCliRpcHandler - [ProxyRpcHandler.py:107]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_server'], rpc_fuc_kwargs={}"
2021-06-26 23:07:09,052 - DEBUG - ServerEntity.ServerEntity - [ServerEntity.py:23]: __init__ create entity ServerEntity with id 60d7429d7c1f34695f2df91d mem_id=2682388261952
2021-06-26 23:07:09,056 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d7429d7c1f34695f2df91d 
2021-06-26 23:07:11,026 - WARNING - TcpConn - [TcpConn.py:173]: heartbeat timeout
2021-06-26 23:07:11,044 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 2114) is connected !!!!
2021-06-26 23:07:12,086 - ERROR - ProxyCliRpcHandler - [ProxyRpcHandler.py:107]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_server'], rpc_fuc_kwargs={}"
2021-06-26 23:07:17,053 - DEBUG - ServerEntity.ServerEntity - [ServerEntity.py:23]: __init__ create entity ServerEntity with id 60d742a57c1f34695f2df91e mem_id=2682387646784
2021-06-26 23:07:17,056 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d742a57c1f34695f2df91e 
2021-06-26 23:07:19,057 - WARNING - TcpConn - [TcpConn.py:173]: heartbeat timeout
2021-06-26 23:07:19,074 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 2118) is connected !!!!
2021-06-26 23:07:20,086 - ERROR - ProxyCliRpcHandler - [ProxyRpcHandler.py:107]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_server'], rpc_fuc_kwargs={}"
2021-06-26 23:07:25,069 - DEBUG - ServerEntity.ServerEntity - [ServerEntity.py:23]: __init__ create entity ServerEntity with id 60d742ad7c1f34695f2df91f mem_id=2682388879440
2021-06-26 23:07:25,072 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d742ad7c1f34695f2df91f 
2021-06-26 23:07:27,075 - WARNING - TcpConn - [TcpConn.py:173]: heartbeat timeout
2021-06-26 23:07:27,094 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 2123) is connected !!!!
2021-06-26 23:07:28,012 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 152 -> 152
2021-06-26 23:07:28,089 - ERROR - ProxyCliRpcHandler - [ProxyRpcHandler.py:107]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_server'], rpc_fuc_kwargs={}"
2021-06-26 23:15:33,588 - DEBUG - ServerEntity.LoadReporter - [ServerEntity.py:23]: __init__ create entity LoadReporter with id 60d74495001f0d886f373fad mem_id=1867249787856
2021-06-26 23:15:33,588 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d74495001f0d886f373fad 
2021-06-26 23:15:33,601 - DEBUG - ServiceNode - [EtcdSupport.py:533]: we have create ServiceFinder
2021-06-26 23:15:33,612 - DEBUG - ServiceFinder - [EtcdSupport.py:352]: _init_info, now_url: http://127.0.0.1:2379/v2/keys?recursive=true
2021-06-26 23:15:33,618 - DEBUG - ServiceRegister - [EtcdSupport.py:155]: _do_regist: now_url: http://127.0.0.1:2379/v2/keys/services/lobby_gate/127.0.0.1|9201
2021-06-26 23:15:33,629 - DEBUG - TcpServer - [TcpServer.py:194]: Server on ('127.0.0.1', 9201)
2021-06-26 23:15:33,652 - DEBUG - ServiceFinder - [EtcdSupport.py:323]: add service node info--> dispatcher_service: ('127.0.0.1', 9100)
2021-06-26 23:15:33,657 - DEBUG - ServiceFinder - [EtcdSupport.py:323]: add service node info--> lobby_server: ('127.0.0.1', 10001)
2021-06-26 23:15:33,661 - DEBUG - ServiceFinder - [EtcdSupport.py:277]: init service info from etcd success, will going to watch, at etcd index -> 164
2021-06-26 23:15:33,674 - DEBUG - ServiceRegister - [EtcdSupport.py:163]: regist service : lobby_gate success, {"action":"set","node":{"key":"/services/lobby_gate/127.0.0.1|9201","value":"","expiration":"2021-06-26T15:18:33.6459317Z","ttl":180,"modifiedIndex":165,"createdIndex":165}}

2021-06-26 23:15:33,686 - DEBUG - ServiceFinder - [EtcdSupport.py:422]: recv watch set service node info--> lobby_gate: ('127.0.0.1', 9201) - [165]
2021-06-26 23:15:35,825 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 14673) is connected !!!!
2021-06-26 23:15:35,864 - DEBUG - ServerEntity.ServerEntity - [ServerEntity.py:23]: __init__ create entity ServerEntity with id 60d74497001f0d886f373fae mem_id=1867252158912
2021-06-26 23:15:35,867 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d74497001f0d886f373fae 
2021-06-26 23:15:35,872 - INFO - ProxyCliRpcHandler - [ProxyRpcHandler.py:90]: start: start_time=1624720535.8703084
2021-06-26 23:15:35,907 - INFO - ProxyCliRpcHandler - [ProxyRpcHandler.py:104]: end: offset=0.03518939018249512
2021-06-26 23:15:41,842 - CRITICAL - ProxyCliRpcHandler - [ProxyRpcHandler.py:123]: on_traceback, type:<class 'UnboundLocalError'>, value:local variable '_lobby_addr' referenced before assignment, traceback:<class 'UnboundLocalError'>
local variable '_lobby_addr' referenced before assignment
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\ProxyRpcHandler.py", line 119, in handle_rpc
    locals={'self': <ProxyRpcHandler.ProxyCliRpcHandler object at 0x000001B2C0E6D070>, 'rpc_msg': b'\x91\x03'}
2021-06-26 23:15:43,845 - WARNING - TcpConn - [TcpConn.py:173]: heartbeat timeout
2021-06-26 23:15:43,864 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 14686) is connected !!!!
2021-06-26 23:15:43,908 - WARNING - TcpConn - [TcpConn.py:173]: heartbeat timeout
2021-06-26 23:15:49,879 - DEBUG - ServerEntity.ServerEntity - [ServerEntity.py:23]: __init__ create entity ServerEntity with id 60d744a5001f0d886f373faf mem_id=1867252159152
2021-06-26 23:15:49,882 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d744a5001f0d886f373faf 
2021-06-26 23:15:49,891 - INFO - ProxyCliRpcHandler - [ProxyRpcHandler.py:90]: start: start_time=1624720549.888598
2021-06-26 23:15:51,867 - WARNING - TcpConn - [TcpConn.py:173]: heartbeat timeout
2021-06-26 23:15:51,887 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 14693) is connected !!!!
2021-06-26 23:15:51,913 - WARNING - TcpConn - [TcpConn.py:173]: heartbeat timeout
2021-06-26 23:15:52,911 - INFO - ProxyCliRpcHandler - [ProxyRpcHandler.py:104]: end: offset=3.0195815563201904
2021-06-26 23:15:52,914 - ERROR - ProxyCliRpcHandler - [ProxyRpcHandler.py:107]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_server'], rpc_fuc_kwargs={}"
2021-06-26 23:15:57,899 - DEBUG - ServerEntity.ServerEntity - [ServerEntity.py:23]: __init__ create entity ServerEntity with id 60d744ad001f0d886f373fb0 mem_id=1867252160016
2021-06-26 23:15:57,902 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d744ad001f0d886f373fb0 
2021-06-26 23:15:57,908 - INFO - ProxyCliRpcHandler - [ProxyRpcHandler.py:90]: start: start_time=1624720557.906921
2021-06-26 23:15:58,599 - WARNING - TcpConn - [TcpConn.py:173]: connection is closed by error: [WinError 64] The specified network name is no longer available
2021-06-26 23:15:59,921 - WARNING - TcpConn - [TcpConn.py:173]: heartbeat timeout
2021-06-26 23:19:56,228 - DEBUG - ServerEntity.LoadReporter - [ServerEntity.py:23]: __init__ create entity LoadReporter with id 60d7459c7ec16975271b6686 mem_id=2951696115120
2021-06-26 23:19:56,229 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d7459c7ec16975271b6686 
2021-06-26 23:19:56,241 - DEBUG - ServiceNode - [EtcdSupport.py:533]: we have create ServiceFinder
2021-06-26 23:19:56,252 - DEBUG - ServiceFinder - [EtcdSupport.py:352]: _init_info, now_url: http://127.0.0.1:2379/v2/keys?recursive=true
2021-06-26 23:19:56,259 - DEBUG - ServiceRegister - [EtcdSupport.py:155]: _do_regist: now_url: http://127.0.0.1:2379/v2/keys/services/lobby_gate/127.0.0.1|9201
2021-06-26 23:19:56,270 - DEBUG - TcpServer - [TcpServer.py:194]: Server on ('127.0.0.1', 9201)
2021-06-26 23:19:56,294 - DEBUG - ServiceFinder - [EtcdSupport.py:323]: add service node info--> dispatcher_service: ('127.0.0.1', 9100)
2021-06-26 23:19:56,297 - DEBUG - ServiceFinder - [EtcdSupport.py:323]: add service node info--> lobby_server: ('127.0.0.1', 10001)
2021-06-26 23:19:56,301 - DEBUG - ServiceFinder - [EtcdSupport.py:277]: init service info from etcd success, will going to watch, at etcd index -> 172
2021-06-26 23:19:56,312 - DEBUG - ServiceRegister - [EtcdSupport.py:163]: regist service : lobby_gate success, {"action":"set","node":{"key":"/services/lobby_gate/127.0.0.1|9201","value":"","expiration":"2021-06-26T15:22:56.2851562Z","ttl":180,"modifiedIndex":173,"createdIndex":173}}

2021-06-26 23:19:56,323 - DEBUG - ServiceFinder - [EtcdSupport.py:422]: recv watch set service node info--> lobby_gate: ('127.0.0.1', 9201) - [173]
2021-06-26 23:20:14,348 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 1830) is connected !!!!
2021-06-26 23:20:14,362 - DEBUG - ServerEntity.ServerEntity - [ServerEntity.py:23]: __init__ create entity ServerEntity with id 60d745ae7ec16975271b6687 mem_id=2951698716128
2021-06-26 23:20:14,366 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d745ae7ec16975271b6687 
2021-06-26 23:20:14,373 - INFO - ProxyCliRpcHandler - [ProxyRpcHandler.py:90]: start: start_time=1624720814.3699493
2021-06-26 23:20:17,388 - INFO - ProxyCliRpcHandler - [ProxyRpcHandler.py:104]: end: offset=3.017019748687744
2021-06-26 23:20:17,392 - ERROR - ProxyCliRpcHandler - [ProxyRpcHandler.py:107]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_server'], rpc_fuc_kwargs={}"
2021-06-26 23:20:20,356 - DEBUG - ServerEntity.ServerEntity - [ServerEntity.py:23]: __init__ create entity ServerEntity with id 60d745b47ec16975271b6688 mem_id=2951698718576
2021-06-26 23:20:20,359 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d745b47ec16975271b6688 
2021-06-26 23:20:20,367 - INFO - ProxyCliRpcHandler - [ProxyRpcHandler.py:90]: start: start_time=1624720820.3647406
2021-06-26 23:20:22,371 - WARNING - TcpConn - [TcpConn.py:173]: heartbeat timeout
2021-06-26 23:20:22,389 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 1833) is connected !!!!
2021-06-26 23:20:23,380 - INFO - ProxyCliRpcHandler - [ProxyRpcHandler.py:104]: end: offset=3.014223098754883
2021-06-26 23:20:23,383 - ERROR - ProxyCliRpcHandler - [ProxyRpcHandler.py:107]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_server'], rpc_fuc_kwargs={}"
2021-06-26 23:20:28,401 - DEBUG - ServerEntity.ServerEntity - [ServerEntity.py:23]: __init__ create entity ServerEntity with id 60d745bc7ec16975271b6689 mem_id=2951697436336
2021-06-26 23:20:28,404 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d745bc7ec16975271b6689 
2021-06-26 23:20:28,410 - INFO - ProxyCliRpcHandler - [ProxyRpcHandler.py:90]: start: start_time=1624720828.407699
2021-06-26 23:20:30,387 - WARNING - TcpConn - [TcpConn.py:173]: heartbeat timeout
2021-06-26 23:20:30,406 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 1837) is connected !!!!
2021-06-26 23:20:31,416 - INFO - ProxyCliRpcHandler - [ProxyRpcHandler.py:104]: end: offset=3.005800724029541
2021-06-26 23:20:31,419 - ERROR - ProxyCliRpcHandler - [ProxyRpcHandler.py:107]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_server'], rpc_fuc_kwargs={}"
2021-06-26 23:20:36,416 - DEBUG - ServerEntity.ServerEntity - [ServerEntity.py:23]: __init__ create entity ServerEntity with id 60d745c47ec16975271b668a mem_id=2951698717088
2021-06-26 23:20:36,420 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d745c47ec16975271b668a 
2021-06-26 23:20:36,430 - INFO - ProxyCliRpcHandler - [ProxyRpcHandler.py:90]: start: start_time=1624720836.424977
2021-06-26 23:20:38,414 - WARNING - TcpConn - [TcpConn.py:173]: heartbeat timeout
2021-06-26 23:20:38,432 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 1843) is connected !!!!
2021-06-26 23:22:43,235 - DEBUG - ServerEntity.LoadReporter - [ServerEntity.py:24]: __init__ create entity LoadReporter with id 60d7464380094fb1719d4a82 mem_id=2206447378048
2021-06-26 23:22:43,235 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d7464380094fb1719d4a82 
2021-06-26 23:22:43,247 - DEBUG - ServiceNode - [EtcdSupport.py:533]: we have create ServiceFinder
2021-06-26 23:22:43,256 - DEBUG - ServiceFinder - [EtcdSupport.py:352]: _init_info, now_url: http://127.0.0.1:2379/v2/keys?recursive=true
2021-06-26 23:22:43,263 - DEBUG - ServiceRegister - [EtcdSupport.py:155]: _do_regist: now_url: http://127.0.0.1:2379/v2/keys/services/lobby_gate/127.0.0.1|9201
2021-06-26 23:22:43,273 - DEBUG - TcpServer - [TcpServer.py:194]: Server on ('127.0.0.1', 9201)
2021-06-26 23:22:43,294 - DEBUG - ServiceFinder - [EtcdSupport.py:323]: add service node info--> dispatcher_service: ('127.0.0.1', 9100)
2021-06-26 23:22:43,296 - DEBUG - ServiceFinder - [EtcdSupport.py:323]: add service node info--> lobby_server: ('127.0.0.1', 10001)
2021-06-26 23:22:43,301 - DEBUG - ServiceFinder - [EtcdSupport.py:323]: add service node info--> lobby_gate: ('127.0.0.1', 9201)
2021-06-26 23:22:43,304 - DEBUG - ServiceFinder - [EtcdSupport.py:277]: init service info from etcd success, will going to watch, at etcd index -> 177
2021-06-26 23:22:43,315 - DEBUG - ServiceRegister - [EtcdSupport.py:163]: regist service : lobby_gate success, {"action":"set","node":{"key":"/services/lobby_gate/127.0.0.1|9201","value":"","expiration":"2021-06-26T15:25:43.2883734Z","ttl":180,"modifiedIndex":178,"createdIndex":178},"prevNode":{"key":"/services/lobby_gate/127.0.0.1|9201","value":"","expiration":"2021-06-26T15:22:56.2851562Z","ttl":13,"modifiedIndex":173,"createdIndex":173}}

2021-06-26 23:22:43,325 - DEBUG - ServiceFinder - [EtcdSupport.py:422]: recv watch set service node info--> lobby_gate: ('127.0.0.1', 9201) - [178]
2021-06-26 23:22:43,328 - DEBUG - ServiceFinder - [EtcdSupport.py:299]: duplicate service info  -> lobby_gate:('127.0.0.1', 9201)
2021-06-26 23:22:46,671 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 1969) is connected !!!!
2021-06-26 23:22:46,708 - DEBUG - ServerEntity.ServerEntity - [ServerEntity.py:24]: __init__ create entity ServerEntity with id 60d7464680094fb1719d4a83 mem_id=2206450479312
2021-06-26 23:22:46,711 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d7464680094fb1719d4a83 
2021-06-26 23:22:46,716 - INFO - ProxyCliRpcHandler - [ProxyRpcHandler.py:90]: start: start_time=1624720966.7146997
2021-06-26 23:22:46,751 - INFO - ProxyCliRpcHandler - [ProxyRpcHandler.py:104]: end: offset=0.03492546081542969
2021-06-26 23:22:54,690 - WARNING - TcpConn - [TcpConn.py:173]: heartbeat timeout
2021-06-26 23:22:54,709 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 1977) is connected !!!!
2021-06-26 23:22:54,783 - WARNING - TcpConn - [TcpConn.py:173]: heartbeat timeout
2021-06-26 23:23:00,721 - DEBUG - ServerEntity.ServerEntity - [ServerEntity.py:24]: __init__ create entity ServerEntity with id 60d7465480094fb1719d4a84 mem_id=2206450479456
2021-06-26 23:23:00,724 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d7465480094fb1719d4a84 
2021-06-26 23:23:00,731 - INFO - ProxyCliRpcHandler - [ProxyRpcHandler.py:90]: start: start_time=1624720980.7287412
2021-06-26 23:23:02,722 - WARNING - TcpConn - [TcpConn.py:173]: heartbeat timeout
2021-06-26 23:23:02,741 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 1982) is connected !!!!
2021-06-26 23:23:02,815 - WARNING - TcpConn - [TcpConn.py:173]: heartbeat timeout
2021-06-26 23:23:03,755 - INFO - ProxyCliRpcHandler - [ProxyRpcHandler.py:104]: end: offset=3.0239274501800537
2021-06-26 23:23:03,758 - ERROR - ProxyCliRpcHandler - [ProxyRpcHandler.py:107]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_server'], rpc_fuc_kwargs={}"
2021-06-26 23:23:08,753 - DEBUG - ServerEntity.ServerEntity - [ServerEntity.py:24]: __init__ create entity ServerEntity with id 60d7465c80094fb1719d4a85 mem_id=2206450714704
2021-06-26 23:23:08,757 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d7465c80094fb1719d4a85 
2021-06-26 23:23:08,764 - INFO - ProxyCliRpcHandler - [ProxyRpcHandler.py:90]: start: start_time=1624720988.7601101
2021-06-26 23:23:10,746 - WARNING - TcpConn - [TcpConn.py:173]: heartbeat timeout
2021-06-26 23:23:10,767 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 1986) is connected !!!!
2021-06-26 23:23:10,837 - WARNING - TcpConn - [TcpConn.py:173]: heartbeat timeout
2021-06-26 23:23:11,785 - INFO - ProxyCliRpcHandler - [ProxyRpcHandler.py:104]: end: offset=3.022763252258301
2021-06-26 23:23:11,788 - ERROR - ProxyCliRpcHandler - [ProxyRpcHandler.py:107]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_server'], rpc_fuc_kwargs={}"
2021-06-26 23:23:27,760 - DEBUG - ServerEntity.LoadReporter - [ServerEntity.py:24]: __init__ create entity LoadReporter with id 60d7466fdfafa1120f28333f mem_id=1417815045120
2021-06-26 23:23:27,760 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d7466fdfafa1120f28333f 
2021-06-26 23:23:27,772 - DEBUG - ServiceNode - [EtcdSupport.py:533]: we have create ServiceFinder
2021-06-26 23:23:27,781 - DEBUG - ServiceFinder - [EtcdSupport.py:352]: _init_info, now_url: http://127.0.0.1:2379/v2/keys?recursive=true
2021-06-26 23:23:27,786 - DEBUG - ServiceRegister - [EtcdSupport.py:155]: _do_regist: now_url: http://127.0.0.1:2379/v2/keys/services/lobby_gate/127.0.0.1|9201
2021-06-26 23:23:27,796 - DEBUG - TcpServer - [TcpServer.py:194]: Server on ('127.0.0.1', 9201)
2021-06-26 23:23:27,817 - DEBUG - ServiceFinder - [EtcdSupport.py:323]: add service node info--> dispatcher_service: ('127.0.0.1', 9100)
2021-06-26 23:23:27,820 - DEBUG - ServiceFinder - [EtcdSupport.py:323]: add service node info--> lobby_server: ('127.0.0.1', 10001)
2021-06-26 23:23:27,824 - DEBUG - ServiceFinder - [EtcdSupport.py:323]: add service node info--> lobby_gate: ('127.0.0.1', 9201)
2021-06-26 23:23:27,827 - DEBUG - ServiceFinder - [EtcdSupport.py:277]: init service info from etcd success, will going to watch, at etcd index -> 178
2021-06-26 23:23:27,839 - DEBUG - ServiceRegister - [EtcdSupport.py:163]: regist service : lobby_gate success, {"action":"set","node":{"key":"/services/lobby_gate/127.0.0.1|9201","value":"","expiration":"2021-06-26T15:26:27.8115248Z","ttl":180,"modifiedIndex":179,"createdIndex":179},"prevNode":{"key":"/services/lobby_gate/127.0.0.1|9201","value":"","expiration":"2021-06-26T15:25:43.2883734Z","ttl":136,"modifiedIndex":178,"createdIndex":178}}

2021-06-26 23:23:27,849 - DEBUG - ServiceFinder - [EtcdSupport.py:422]: recv watch set service node info--> lobby_gate: ('127.0.0.1', 9201) - [179]
2021-06-26 23:23:27,852 - DEBUG - ServiceFinder - [EtcdSupport.py:299]: duplicate service info  -> lobby_gate:('127.0.0.1', 9201)
2021-06-26 23:23:33,477 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 2012) is connected !!!!
2021-06-26 23:23:33,524 - DEBUG - ServerEntity.ServerEntity - [ServerEntity.py:24]: __init__ create entity ServerEntity with id 60d74675dfafa1120f283340 mem_id=1417817850112
2021-06-26 23:23:33,527 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d74675dfafa1120f283340 
2021-06-26 23:23:33,533 - INFO - ProxyCliRpcHandler - [ProxyRpcHandler.py:90]: start: start_time=1624721013.5309534
2021-06-26 23:23:33,574 - INFO - ProxyCliRpcHandler - [ProxyRpcHandler.py:104]: end: offset=0.04045748710632324
2021-06-26 23:23:41,492 - WARNING - TcpConn - [TcpConn.py:173]: heartbeat timeout
2021-06-26 23:23:41,511 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 2019) is connected !!!!
2021-06-26 23:23:41,601 - WARNING - TcpConn - [TcpConn.py:173]: heartbeat timeout
2021-06-26 23:23:47,507 - DEBUG - ServerEntity.ServerEntity - [ServerEntity.py:24]: __init__ create entity ServerEntity with id 60d74683dfafa1120f283341 mem_id=1417818392608
2021-06-26 23:23:47,510 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d74683dfafa1120f283341 
2021-06-26 23:23:47,516 - INFO - ProxyCliRpcHandler - [ProxyRpcHandler.py:90]: start: start_time=1624721027.5131736
2021-06-26 23:23:49,517 - WARNING - TcpConn - [TcpConn.py:173]: heartbeat timeout
2021-06-26 23:23:49,536 - DEBUG - TcpServer - [TcpServer.py:180]: ('127.0.0.1', 2025) is connected !!!!
2021-06-26 23:23:49,624 - WARNING - TcpConn - [TcpConn.py:173]: heartbeat timeout
2021-06-26 23:23:50,531 - INFO - ProxyCliRpcHandler - [ProxyRpcHandler.py:104]: end: offset=3.0152835845947266
2021-06-26 23:23:50,534 - ERROR - ProxyCliRpcHandler - [ProxyRpcHandler.py:107]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_server'], rpc_fuc_kwargs={}"
