2021-07-05 01:31:09,519 - DEBUG - RpcHandler - [RpcHandler.py:218]: _handle_create_conn: addr=('127.0.0.1', 9100)
2021-07-05 01:31:09,527 - INFO - RudpProtocol - [ConnMgr.py:131]: RUDP ROLE_TYPE_ACTIVE peer_addr=('127.0.0.1', 9100) is connected !!!!
2021-07-05 01:31:09,570 - DEBUG - __main__ - [RudpClient.py:69]: lobby server info: ('gate_0', '127.0.0.1', 9201)
2021-07-05 01:31:09,572 - INFO - ServerEntity.Avatar - [ServerEntity.py:25]: __init__ create entity Avatar with id 60e1f05d67de8ddcec4e4f7e mem_id=2021809783664
2021-07-05 01:31:09,574 - INFO - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60e1f05d67de8ddcec4e4f7e 
2021-07-05 01:31:09,583 - INFO - RudpProtocol - [ConnMgr.py:131]: RUDP ROLE_TYPE_ACTIVE peer_addr=('127.0.0.1', 9201) is connected !!!!
2021-07-05 01:32:04,217 - DEBUG - RpcHandler - [RpcHandler.py:218]: _handle_create_conn: addr=('127.0.0.1', 9100)
2021-07-05 01:32:04,226 - INFO - RudpProtocol - [ConnMgr.py:131]: RUDP ROLE_TYPE_ACTIVE peer_addr=('127.0.0.1', 9100) is connected !!!!
2021-07-05 01:32:04,268 - DEBUG - __main__ - [RudpClient.py:69]: lobby server info: ('gate_1', '127.0.0.1', 9202)
2021-07-05 01:32:04,270 - INFO - ServerEntity.Avatar - [ServerEntity.py:25]: __init__ create entity Avatar with id 60e1f094b5ce3ebda4752a8c mem_id=2101162418864
2021-07-05 01:32:04,271 - INFO - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60e1f094b5ce3ebda4752a8c 
2021-07-05 01:32:04,280 - INFO - RudpProtocol - [ConnMgr.py:131]: RUDP ROLE_TYPE_ACTIVE peer_addr=('127.0.0.1', 9202) is connected !!!!
2021-07-05 01:32:35,815 - DEBUG - RpcHandler - [RpcHandler.py:218]: _handle_create_conn: addr=('127.0.0.1', 9102)
2021-07-05 01:32:36,429 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:69"]: try reconnect rudp: ('127.0.0.1', 9102) ... 1
2021-07-05 01:32:37,052 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:69"]: try reconnect rudp: ('127.0.0.1', 9102) ... 2
2021-07-05 01:32:37,658 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:69"]: try reconnect rudp: ('127.0.0.1', 9102) ... 3
2021-07-05 01:32:38,266 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:69"]: try reconnect rudp: ('127.0.0.1', 9102) ... 4
2021-07-05 01:32:38,874 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:69"]: try reconnect rudp: ('127.0.0.1', 9102) ... 5
2021-07-05 01:32:39,482 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:69"]: try reconnect rudp: ('127.0.0.1', 9102) ... 6
2021-07-05 01:32:39,483 - ERROR - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:78"]: try 6 times , still can't connect rudp remote addr: ('127.0.0.1', 9102)
2021-07-05 01:34:17,220 - DEBUG - RpcHandler - [RpcHandler.py:218]: _handle_create_conn: addr=('127.0.0.1', 9102)
2021-07-05 01:34:17,839 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:69"]: try reconnect rudp: ('127.0.0.1', 9102) ... 1
2021-07-05 01:34:18,462 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:69"]: try reconnect rudp: ('127.0.0.1', 9102) ... 2
2021-07-05 01:34:19,070 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:69"]: try reconnect rudp: ('127.0.0.1', 9102) ... 3
2021-07-05 01:34:19,679 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:69"]: try reconnect rudp: ('127.0.0.1', 9102) ... 4
2021-07-05 01:34:20,300 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:69"]: try reconnect rudp: ('127.0.0.1', 9102) ... 5
2021-07-05 01:34:20,908 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:69"]: try reconnect rudp: ('127.0.0.1', 9102) ... 6
2021-07-05 01:34:20,910 - ERROR - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:78"]: try 6 times , still can't connect rudp remote addr: ('127.0.0.1', 9102)
2021-07-05 01:35:55,003 - DEBUG - RpcHandler - [RpcHandler.py:218]: _handle_create_conn: addr=('127.0.0.1', 9101)
2021-07-05 01:35:55,015 - INFO - RudpProtocol - [ConnMgr.py:131]: RUDP ROLE_TYPE_ACTIVE peer_addr=('127.0.0.1', 9101) is connected !!!!
2021-07-05 01:35:55,056 - DEBUG - __main__ - [RudpClient.py:69]: lobby server info: ('gate_1', '127.0.0.1', 9202)
2021-07-05 01:35:55,058 - INFO - ServerEntity.Avatar - [ServerEntity.py:25]: __init__ create entity Avatar with id 60e1f17b81c3cf63ba26786d mem_id=2280659878816
2021-07-05 01:35:55,060 - INFO - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60e1f17b81c3cf63ba26786d 
2021-07-05 01:35:55,069 - INFO - RudpProtocol - [ConnMgr.py:131]: RUDP ROLE_TYPE_ACTIVE peer_addr=('127.0.0.1', 9202) is connected !!!!
2021-07-05 01:35:59,030 - DEBUG - RpcHandler - [RpcHandler.py:218]: _handle_create_conn: addr=('127.0.0.1', 9100)
2021-07-05 01:35:59,650 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:69"]: try reconnect rudp: ('127.0.0.1', 9100) ... 1
2021-07-05 01:36:00,273 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:69"]: try reconnect rudp: ('127.0.0.1', 9100) ... 2
2021-07-05 01:36:00,895 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:69"]: try reconnect rudp: ('127.0.0.1', 9100) ... 3
2021-07-05 01:36:01,515 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:69"]: try reconnect rudp: ('127.0.0.1', 9100) ... 4
2021-07-05 01:36:02,122 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:69"]: try reconnect rudp: ('127.0.0.1', 9100) ... 5
2021-07-05 01:36:02,730 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:69"]: try reconnect rudp: ('127.0.0.1', 9100) ... 6
2021-07-05 01:36:02,731 - ERROR - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:80"]: try 6 times , still can't connect rudp remote addr: ('127.0.0.1', 9100)
2021-07-05 01:36:32,136 - DEBUG - RpcHandler - [RpcHandler.py:218]: _handle_create_conn: addr=('127.0.0.1', 9102)
2021-07-05 01:36:32,749 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:70"]: try reconnect rudp: ('127.0.0.1', 9102) ... 1
2021-07-05 01:36:33,355 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:70"]: try reconnect rudp: ('127.0.0.1', 9102) ... 2
2021-07-05 01:36:33,962 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:70"]: try reconnect rudp: ('127.0.0.1', 9102) ... 3
2021-07-05 01:36:34,571 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:70"]: try reconnect rudp: ('127.0.0.1', 9102) ... 4
2021-07-05 01:36:35,179 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:70"]: try reconnect rudp: ('127.0.0.1', 9102) ... 5
2021-07-05 01:36:35,786 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:70"]: try reconnect rudp: ('127.0.0.1', 9102) ... 6
2021-07-05 01:36:35,787 - ERROR - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:81"]: try 6 times , still can't connect rudp remote addr: ('127.0.0.1', 9102)
2021-07-05 01:36:42,784 - DEBUG - RpcHandler - [RpcHandler.py:218]: _handle_create_conn: addr=('127.0.0.1', 9100)
2021-07-05 01:36:43,401 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:70"]: try reconnect rudp: ('127.0.0.1', 9100) ... 1
2021-07-05 01:36:44,024 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:70"]: try reconnect rudp: ('127.0.0.1', 9100) ... 2
2021-07-05 01:36:44,643 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:70"]: try reconnect rudp: ('127.0.0.1', 9100) ... 3
2021-07-05 01:36:45,250 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:70"]: try reconnect rudp: ('127.0.0.1', 9100) ... 4
2021-07-05 01:36:45,859 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:70"]: try reconnect rudp: ('127.0.0.1', 9100) ... 5
2021-07-05 01:36:46,467 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:70"]: try reconnect rudp: ('127.0.0.1', 9100) ... 6
2021-07-05 01:36:46,467 - ERROR - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:81"]: try 6 times , still can't connect rudp remote addr: ('127.0.0.1', 9100)
2021-07-05 01:38:06,242 - DEBUG - RpcHandler - [RpcHandler.py:218]: _handle_create_conn: addr=('127.0.0.1', 9101)
2021-07-05 01:38:06,255 - INFO - RudpProtocol - [ConnMgr.py:131]: RUDP ROLE_TYPE_ACTIVE peer_addr=('127.0.0.1', 9101) is connected !!!!
2021-07-05 01:38:06,301 - DEBUG - __main__ - [RudpClient.py:69]: lobby server info: ('gate_1', '127.0.0.1', 9202)
2021-07-05 01:38:06,303 - INFO - ServerEntity.Avatar - [ServerEntity.py:25]: __init__ create entity Avatar with id 60e1f1fe66321186871311de mem_id=1728775258944
2021-07-05 01:38:06,304 - INFO - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60e1f1fe66321186871311de 
2021-07-05 01:38:06,313 - INFO - RudpProtocol - [ConnMgr.py:131]: RUDP ROLE_TYPE_ACTIVE peer_addr=('127.0.0.1', 9202) is connected !!!!
2021-07-05 01:38:12,084 - DEBUG - RpcHandler - [RpcHandler.py:218]: _handle_create_conn: addr=('127.0.0.1', 9100)
2021-07-05 01:38:12,697 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:73"]: try reconnect rudp: ('127.0.0.1', 9100) ... 1
2021-07-05 01:38:13,322 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:73"]: try reconnect rudp: ('127.0.0.1', 9100) ... 2
2021-07-05 01:38:13,942 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:73"]: try reconnect rudp: ('127.0.0.1', 9100) ... 3
2021-07-05 01:38:14,563 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:73"]: try reconnect rudp: ('127.0.0.1', 9100) ... 4
2021-07-05 01:38:15,183 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:73"]: try reconnect rudp: ('127.0.0.1', 9100) ... 5
2021-07-05 01:38:15,775 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:73"]: try reconnect rudp: ('127.0.0.1', 9100) ... 6
2021-07-05 01:38:15,776 - ERROR - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:84"]: try 6 times , still can't connect rudp remote addr: ('127.0.0.1', 9100)
2021-07-05 01:38:56,136 - DEBUG - RpcHandler - [RpcHandler.py:218]: _handle_create_conn: addr=('127.0.0.1', 9101)
2021-07-05 01:38:56,149 - INFO - RudpProtocol - [ConnMgr.py:131]: RUDP ROLE_TYPE_ACTIVE peer_addr=('127.0.0.1', 9101) is connected !!!!
2021-07-05 01:38:56,189 - DEBUG - __main__ - [RudpClient.py:69]: lobby server info: ('gate_2', '127.0.0.1', 9203)
2021-07-05 01:38:56,191 - INFO - ServerEntity.Avatar - [ServerEntity.py:25]: __init__ create entity Avatar with id 60e1f2304410083f00e3b1a7 mem_id=2228241826624
2021-07-05 01:38:56,193 - INFO - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60e1f2304410083f00e3b1a7 
2021-07-05 01:38:56,200 - INFO - RudpProtocol - [ConnMgr.py:131]: RUDP ROLE_TYPE_ACTIVE peer_addr=('127.0.0.1', 9203) is connected !!!!
2021-07-05 01:39:00,493 - DEBUG - RpcHandler - [RpcHandler.py:218]: _handle_create_conn: addr=('127.0.0.1', 9102)
2021-07-05 01:39:01,110 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:75"]: try reconnect rudp: ('127.0.0.1', 9102) ... 1
2021-07-05 01:39:01,719 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:75"]: try reconnect rudp: ('127.0.0.1', 9102) ... 2
2021-07-05 01:39:02,328 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:75"]: try reconnect rudp: ('127.0.0.1', 9102) ... 3
2021-07-05 01:39:02,949 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:75"]: try reconnect rudp: ('127.0.0.1', 9102) ... 4
2021-07-05 01:39:03,541 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:75"]: try reconnect rudp: ('127.0.0.1', 9102) ... 5
2021-07-05 01:39:04,150 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:75"]: try reconnect rudp: ('127.0.0.1', 9102) ... 6
2021-07-05 01:39:04,151 - ERROR - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:86"]: try 6 times , still can't connect rudp remote addr: ('127.0.0.1', 9102)
2021-07-05 01:39:16,882 - DEBUG - RpcHandler - [RpcHandler.py:218]: _handle_create_conn: addr=('127.0.0.1', 9102)
2021-07-05 01:39:17,507 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:75"]: try reconnect rudp: ('127.0.0.1', 9102) ... 1
2021-07-05 01:39:18,116 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:75"]: try reconnect rudp: ('127.0.0.1', 9102) ... 2
2021-07-05 01:39:18,722 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:75"]: try reconnect rudp: ('127.0.0.1', 9102) ... 3
2021-07-05 01:39:19,343 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:75"]: try reconnect rudp: ('127.0.0.1', 9102) ... 4
2021-07-05 01:39:19,950 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:75"]: try reconnect rudp: ('127.0.0.1', 9102) ... 5
2021-07-05 01:39:20,556 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:75"]: try reconnect rudp: ('127.0.0.1', 9102) ... 6
2021-07-05 01:39:20,557 - ERROR - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:86"]: try 6 times , still can't connect rudp remote addr: ('127.0.0.1', 9102)
2021-07-05 01:39:26,607 - DEBUG - RpcHandler - [RpcHandler.py:218]: _handle_create_conn: addr=('127.0.0.1', 9102)
2021-07-05 01:39:27,232 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:75"]: try reconnect rudp: ('127.0.0.1', 9102) ... 1
2021-07-05 01:39:27,852 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:75"]: try reconnect rudp: ('127.0.0.1', 9102) ... 2
2021-07-05 01:39:28,459 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:75"]: try reconnect rudp: ('127.0.0.1', 9102) ... 3
2021-07-05 01:39:29,080 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:75"]: try reconnect rudp: ('127.0.0.1', 9102) ... 4
2021-07-05 01:39:29,686 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:75"]: try reconnect rudp: ('127.0.0.1', 9102) ... 5
2021-07-05 01:39:30,308 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:75"]: try reconnect rudp: ('127.0.0.1', 9102) ... 6
2021-07-05 01:39:30,310 - ERROR - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:86"]: try 6 times , still can't connect rudp remote addr: ('127.0.0.1', 9102)
2021-07-05 01:39:45,950 - DEBUG - RpcHandler - [RpcHandler.py:218]: _handle_create_conn: addr=('127.0.0.1', 9102)
2021-07-05 01:39:46,569 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:75"]: try reconnect rudp: ('127.0.0.1', 9102) ... 1
2021-07-05 01:39:47,178 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:75"]: try reconnect rudp: ('127.0.0.1', 9102) ... 2
2021-07-05 01:39:47,797 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:75"]: try reconnect rudp: ('127.0.0.1', 9102) ... 3
2021-07-05 01:39:48,409 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:75"]: try reconnect rudp: ('127.0.0.1', 9102) ... 4
2021-07-05 01:39:49,027 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:75"]: try reconnect rudp: ('127.0.0.1', 9102) ... 5
2021-07-05 01:39:49,634 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:75"]: try reconnect rudp: ('127.0.0.1', 9102) ... 6
2021-07-05 01:39:49,637 - ERROR - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:86"]: try 6 times , still can't connect rudp remote addr: ('127.0.0.1', 9102)
2021-07-05 01:40:52,542 - DEBUG - RpcHandler - [RpcHandler.py:218]: _handle_create_conn: addr=('127.0.0.1', 9100)
2021-07-05 01:40:53,161 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:75"]: try reconnect rudp: ('127.0.0.1', 9100) ... 1
2021-07-05 01:40:53,768 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:75"]: try reconnect rudp: ('127.0.0.1', 9100) ... 2
2021-07-05 01:40:54,376 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:75"]: try reconnect rudp: ('127.0.0.1', 9100) ... 3
2021-07-05 01:40:54,983 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:75"]: try reconnect rudp: ('127.0.0.1', 9100) ... 4
2021-07-05 01:40:55,593 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:75"]: try reconnect rudp: ('127.0.0.1', 9100) ... 5
2021-07-05 01:40:56,211 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:75"]: try reconnect rudp: ('127.0.0.1', 9100) ... 6
2021-07-05 01:40:56,213 - ERROR - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:86"]: try 6 times , still can't connect rudp remote addr: ('127.0.0.1', 9100)
2021-07-05 01:41:00,669 - DEBUG - RpcHandler - [RpcHandler.py:218]: _handle_create_conn: addr=('127.0.0.1', 9102)
2021-07-05 01:41:01,288 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:75"]: try reconnect rudp: ('127.0.0.1', 9102) ... 1
2021-07-05 01:41:01,896 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:75"]: try reconnect rudp: ('127.0.0.1', 9102) ... 2
2021-07-05 01:41:02,502 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:75"]: try reconnect rudp: ('127.0.0.1', 9102) ... 3
2021-07-05 01:41:03,120 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:75"]: try reconnect rudp: ('127.0.0.1', 9102) ... 4
2021-07-05 01:41:03,728 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:75"]: try reconnect rudp: ('127.0.0.1', 9102) ... 5
2021-07-05 01:41:04,345 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:75"]: try reconnect rudp: ('127.0.0.1', 9102) ... 6
2021-07-05 01:41:04,347 - ERROR - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:86"]: try 6 times , still can't connect rudp remote addr: ('127.0.0.1', 9102)
2021-07-05 01:41:07,741 - DEBUG - RpcHandler - [RpcHandler.py:218]: _handle_create_conn: addr=('127.0.0.1', 9100)
2021-07-05 01:41:08,364 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:75"]: try reconnect rudp: ('127.0.0.1', 9100) ... 1
2021-07-05 01:41:08,983 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:75"]: try reconnect rudp: ('127.0.0.1', 9100) ... 2
2021-07-05 01:41:09,593 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:75"]: try reconnect rudp: ('127.0.0.1', 9100) ... 3
2021-07-05 01:41:10,199 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:75"]: try reconnect rudp: ('127.0.0.1', 9100) ... 4
2021-07-05 01:41:10,817 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:75"]: try reconnect rudp: ('127.0.0.1', 9100) ... 5
2021-07-05 01:41:11,425 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:75"]: try reconnect rudp: ('127.0.0.1', 9100) ... 6
2021-07-05 01:41:11,427 - ERROR - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:86"]: try 6 times , still can't connect rudp remote addr: ('127.0.0.1', 9100)
2021-07-05 01:41:32,945 - DEBUG - RpcHandler - [RpcHandler.py:218]: _handle_create_conn: addr=('127.0.0.1', 9102)
2021-07-05 01:41:33,560 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:75"]: try reconnect rudp: ('127.0.0.1', 9102) ... 1
2021-07-05 01:41:34,165 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:75"]: try reconnect rudp: ('127.0.0.1', 9102) ... 2
2021-07-05 01:41:34,772 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:75"]: try reconnect rudp: ('127.0.0.1', 9102) ... 3
2021-07-05 01:41:35,378 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:75"]: try reconnect rudp: ('127.0.0.1', 9102) ... 4
2021-07-05 01:41:35,986 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:75"]: try reconnect rudp: ('127.0.0.1', 9102) ... 5
2021-07-05 01:41:36,592 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:75"]: try reconnect rudp: ('127.0.0.1', 9102) ... 6
2021-07-05 01:41:36,594 - ERROR - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:86"]: try 6 times , still can't connect rudp remote addr: ('127.0.0.1', 9102)
2021-07-05 01:41:43,438 - DEBUG - RpcHandler - [RpcHandler.py:218]: _handle_create_conn: addr=('127.0.0.1', 9101)
2021-07-05 01:41:43,449 - INFO - RudpProtocol - [ConnMgr.py:131]: RUDP ROLE_TYPE_ACTIVE peer_addr=('127.0.0.1', 9101) is connected !!!!
2021-07-05 01:41:43,493 - DEBUG - __main__ - [RudpClient.py:69]: lobby server info: ('gate_1', '127.0.0.1', 9202)
2021-07-05 01:41:43,495 - INFO - ServerEntity.Avatar - [ServerEntity.py:25]: __init__ create entity Avatar with id 60e1f2d7e79e1ae81eae2f01 mem_id=2163760038768
2021-07-05 01:41:43,496 - INFO - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60e1f2d7e79e1ae81eae2f01 
2021-07-05 01:41:43,507 - INFO - RudpProtocol - [ConnMgr.py:131]: RUDP ROLE_TYPE_ACTIVE peer_addr=('127.0.0.1', 9202) is connected !!!!
2021-07-05 01:42:35,760 - DEBUG - RpcHandler - [RpcHandler.py:218]: _handle_create_conn: addr=('127.0.0.1', 9102)
2021-07-05 01:42:36,372 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:75"]: try reconnect rudp: ('127.0.0.1', 9102) ... 1
2021-07-05 01:42:36,980 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:75"]: try reconnect rudp: ('127.0.0.1', 9102) ... 2
2021-07-05 01:42:37,587 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:75"]: try reconnect rudp: ('127.0.0.1', 9102) ... 3
2021-07-05 01:42:38,194 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:75"]: try reconnect rudp: ('127.0.0.1', 9102) ... 4
2021-07-05 01:42:38,800 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:75"]: try reconnect rudp: ('127.0.0.1', 9102) ... 5
2021-07-05 01:42:39,409 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:75"]: try reconnect rudp: ('127.0.0.1', 9102) ... 6
2021-07-05 01:42:39,410 - ERROR - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:86"]: try 6 times , still can't connect rudp remote addr: ('127.0.0.1', 9102)
2021-07-05 01:44:06,916 - DEBUG - RpcHandler - [RpcHandler.py:218]: _handle_create_conn: addr=('127.0.0.1', 9101)
2021-07-05 01:44:06,930 - INFO - RudpProtocol - [ConnMgr.py:131]: RUDP ROLE_TYPE_ACTIVE peer_addr=('127.0.0.1', 9101) is connected !!!!
2021-07-05 01:44:06,971 - DEBUG - __main__ - [RudpClient.py:69]: lobby server info: ('gate_1', '127.0.0.1', 9202)
2021-07-05 01:44:06,973 - INFO - ServerEntity.Avatar - [ServerEntity.py:25]: __init__ create entity Avatar with id 60e1f366bedb6c6c148991dc mem_id=2371951010864
2021-07-05 01:44:06,974 - INFO - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60e1f366bedb6c6c148991dc 
2021-07-05 01:44:06,984 - INFO - RudpProtocol - [ConnMgr.py:131]: RUDP ROLE_TYPE_ACTIVE peer_addr=('127.0.0.1', 9202) is connected !!!!
2021-07-05 01:44:10,684 - DEBUG - RpcHandler - [RpcHandler.py:218]: _handle_create_conn: addr=('127.0.0.1', 9100)
2021-07-05 01:44:11,300 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:67"]: try reconnect rudp: ('127.0.0.1', 9100) ... 1
2021-07-05 01:44:11,921 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:67"]: try reconnect rudp: ('127.0.0.1', 9100) ... 2
2021-07-05 01:44:12,530 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:67"]: try reconnect rudp: ('127.0.0.1', 9100) ... 3
2021-07-05 01:44:13,139 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:67"]: try reconnect rudp: ('127.0.0.1', 9100) ... 4
2021-07-05 01:44:13,685 - ERROR - __main__ - ["C:/Users/b/Documents/github/realtime-server/pycharm2020.1.3/script/client/RudpClient.py:58"]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_gate'], rpc_fuc_kwargs={}"
2021-07-05 01:44:13,689 - DEBUG - RpcHandler - [RpcHandler.py:218]: _handle_create_conn: addr=('127.0.0.1', 9101)
2021-07-05 01:44:13,695 - INFO - RudpProtocol - [ConnMgr.py:131]: RUDP ROLE_TYPE_ACTIVE peer_addr=('127.0.0.1', 9101) is connected !!!!
2021-07-05 01:44:13,737 - DEBUG - __main__ - [RudpClient.py:69]: lobby server info: ('gate_1', '127.0.0.1', 9202)
2021-07-05 01:44:13,740 - INFO - ServerEntity.Avatar - [ServerEntity.py:25]: __init__ create entity Avatar with id 60e1f36d657c162ce348caea mem_id=2282908091248
2021-07-05 01:44:13,743 - INFO - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60e1f36d657c162ce348caea 
2021-07-05 01:44:13,747 - WARNING - RpcHandler - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RpcHandler.py:239"]: cancel _handle_create_conn task addr=('127.0.0.1', 9100)
2021-07-05 01:44:13,752 - INFO - RudpProtocol - [ConnMgr.py:131]: RUDP ROLE_TYPE_ACTIVE peer_addr=('127.0.0.1', 9202) is connected !!!!
2021-07-05 01:44:25,272 - DEBUG - RpcHandler - [RpcHandler.py:218]: _handle_create_conn: addr=('127.0.0.1', 9100)
2021-07-05 01:44:25,894 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:67"]: try reconnect rudp: ('127.0.0.1', 9100) ... 1
2021-07-05 01:44:26,501 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:67"]: try reconnect rudp: ('127.0.0.1', 9100) ... 2
2021-07-05 01:44:27,109 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:67"]: try reconnect rudp: ('127.0.0.1', 9100) ... 3
2021-07-05 01:44:27,717 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:67"]: try reconnect rudp: ('127.0.0.1', 9100) ... 4
2021-07-05 01:44:28,279 - ERROR - __main__ - ["C:/Users/b/Documents/github/realtime-server/pycharm2020.1.3/script/client/RudpClient.py:58"]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_gate'], rpc_fuc_kwargs={}"
2021-07-05 01:44:28,326 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:67"]: try reconnect rudp: ('127.0.0.1', 9100) ... 5
2021-07-05 01:44:28,946 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:67"]: try reconnect rudp: ('127.0.0.1', 9100) ... 6
2021-07-05 01:44:28,948 - ERROR - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:78"]: try 6 times , still can't connect rudp remote addr: ('127.0.0.1', 9100)
2021-07-05 01:44:31,309 - ERROR - __main__ - ["C:/Users/b/Documents/github/realtime-server/pycharm2020.1.3/script/client/RudpClient.py:58"]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_gate'], rpc_fuc_kwargs={}"
2021-07-05 01:44:31,313 - DEBUG - RpcHandler - [RpcHandler.py:218]: _handle_create_conn: addr=('127.0.0.1', 9100)
2021-07-05 01:44:34,318 - ERROR - __main__ - ["C:/Users/b/Documents/github/realtime-server/pycharm2020.1.3/script/client/RudpClient.py:58"]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_gate'], rpc_fuc_kwargs={}"
2021-07-05 01:44:34,320 - DEBUG - RpcHandler - [RpcHandler.py:218]: _handle_create_conn: addr=('127.0.0.1', 9100)
2021-07-05 01:44:37,334 - ERROR - __main__ - ["C:/Users/b/Documents/github/realtime-server/pycharm2020.1.3/script/client/RudpClient.py:58"]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_gate'], rpc_fuc_kwargs={}"
2021-07-05 01:44:37,338 - DEBUG - RpcHandler - [RpcHandler.py:218]: _handle_create_conn: addr=('127.0.0.1', 9102)
2021-07-05 01:44:37,944 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:67"]: try reconnect rudp: ('127.0.0.1', 9102) ... 1
2021-07-05 01:44:38,550 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:67"]: try reconnect rudp: ('127.0.0.1', 9102) ... 2
2021-07-05 01:44:39,157 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:67"]: try reconnect rudp: ('127.0.0.1', 9102) ... 3
