2021-07-04 12:30:14,094 - INFO - TcpServerProtocol - [TcpServer.py:89]: ('127.0.0.1', 9100) is connected !!!!
2021-07-04 12:30:14,098 - WARNING - RpcHandler - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RpcHandler.py:218"]: self._try_connect_times=1, id(self._conn)=1259548785632
2021-07-04 12:30:14,117 - WARNING - RpcHandler - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RpcHandler.py:82"]: self.rpc_handler_id=b'`\xe19Vf\xf1\x04\\!~!\xe9' RpcHandler Destroy!
2021-07-04 12:30:14,120 - DEBUG - __main__ - [TcpClient2.py:84]: lobby server info: ('gate_0', '127.0.0.1', 9201)
2021-07-04 12:30:14,126 - INFO - ServerEntity.Avatar - [ServerEntity.py:25]: __init__ create entity Avatar with id 60e1395666f1045c217e21ea mem_id=1259548438976
2021-07-04 12:30:14,129 - INFO - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60e1395666f1045c217e21ea 
2021-07-04 12:30:14,136 - INFO - TcpServerProtocol - [TcpServer.py:89]: ('127.0.0.1', 9201) is connected !!!!
2021-07-04 14:51:13,373 - ERROR - ConnMgr - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\ConnMgr.py:183"]: [WinError 1225] The remote computer refused the network connection
2021-07-04 14:51:13,977 - WARNING - ConnMgr - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\ConnMgr.py:186"]: try reconnect tcp: ('127.0.0.1', 9101) ... 1
2021-07-04 14:51:16,019 - ERROR - ConnMgr - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\ConnMgr.py:183"]: [WinError 1225] The remote computer refused the network connection
2021-07-04 14:51:16,630 - WARNING - ConnMgr - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\ConnMgr.py:186"]: try reconnect tcp: ('127.0.0.1', 9101) ... 2
2021-07-04 14:51:48,605 - ERROR - ConnMgr - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\ConnMgr.py:183"]: [WinError 1225] The remote computer refused the network connection
2021-07-04 14:51:49,212 - WARNING - ConnMgr - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\ConnMgr.py:186"]: try reconnect tcp: ('127.0.0.1', 9100) ... 1
2021-07-04 14:51:51,268 - ERROR - ConnMgr - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\ConnMgr.py:183"]: [WinError 1225] The remote computer refused the network connection
2021-07-04 14:51:51,876 - WARNING - ConnMgr - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\ConnMgr.py:186"]: try reconnect tcp: ('127.0.0.1', 9100) ... 2
2021-07-04 14:51:53,924 - ERROR - ConnMgr - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\ConnMgr.py:183"]: [WinError 1225] The remote computer refused the network connection
2021-07-04 14:51:54,532 - WARNING - ConnMgr - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\ConnMgr.py:186"]: try reconnect tcp: ('127.0.0.1', 9100) ... 3
2021-07-04 15:05:20,088 - ERROR - ConnMgr - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\ConnMgr.py:187"]: [WinError 1225] The remote computer refused the network connection
2021-07-04 15:06:18,126 - INFO - TcpServerProtocol - [ConnMgr.py:52]: ('127.0.0.1', 9100) is connected !!!!
2021-07-04 15:06:45,369 - INFO - TcpServerProtocol - [ConnMgr.py:52]: ('127.0.0.1', 9100) is connected !!!!
2021-07-04 15:06:45,374 - WARNING - RpcHandler - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RpcHandler.py:79"]: self.rpc_handler_id=b'`\xe1^\x05\xc3\x05\x8d=\xe9\xa8\xa5\x87' RpcHandler Destroy!
2021-07-04 15:06:45,375 - DEBUG - __main__ - [TcpClient2.py:84]: lobby server info: ('gate_0', '127.0.0.1', 9201)
2021-07-04 15:06:45,377 - INFO - ServerEntity.Avatar - [ServerEntity.py:25]: __init__ create entity Avatar with id 60e15e05c3058d3de9a8a588 mem_id=1819708918560
2021-07-04 15:06:45,379 - INFO - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60e15e05c3058d3de9a8a588 
2021-07-04 15:06:45,382 - INFO - TcpServerProtocol - [ConnMgr.py:52]: ('127.0.0.1', 9201) is connected !!!!
2021-07-04 17:31:57,976 - ERROR - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:54"]: [WinError 1225] The remote computer refused the network connection
2021-07-04 17:31:58,584 - WARNING - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:57"]: try reconnect tcp: ('127.0.0.1', 9100) ... 1
2021-07-04 17:32:33,090 - INFO - TcpProtocol - [ConnMgr.py:49]: ('127.0.0.1', 9100) is connected !!!!
2021-07-04 17:33:14,045 - INFO - TcpProtocol - [ConnMgr.py:49]: ('127.0.0.1', 9100) is connected !!!!
2021-07-04 17:34:59,650 - INFO - TcpProtocol - [ConnMgr.py:49]: ('127.0.0.1', 9100) is connected !!!!
2021-07-04 17:36:13,737 - INFO - TcpProtocol - [ConnMgr.py:49]: ('127.0.0.1', 9100) is connected !!!!
2021-07-04 17:36:23,222 - INFO - TcpProtocol - [ConnMgr.py:49]: ('127.0.0.1', 9100) is connected !!!!
2021-07-04 17:37:15,089 - INFO - TcpProtocol - [ConnMgr.py:49]: ('127.0.0.1', 9100) is connected !!!!
2021-07-04 17:37:36,045 - INFO - TcpProtocol - [ConnMgr.py:49]: ('127.0.0.1', 9100) is connected !!!!
2021-07-04 17:37:55,021 - INFO - TcpProtocol - [ConnMgr.py:49]: ('127.0.0.1', 9100) is connected !!!!
2021-07-04 17:38:26,857 - INFO - TcpProtocol - [ConnMgr.py:49]: ('127.0.0.1', 9100) is connected !!!!
2021-07-04 17:41:06,099 - INFO - TcpProtocol - [ConnMgr.py:49]: ('127.0.0.1', 9100) is connected !!!!
2021-07-04 20:58:04,158 - INFO - TcpProtocol - [ConnMgr.py:49]: ('127.0.0.1', 9100) is connected !!!!
2021-07-04 20:59:26,760 - INFO - TcpProtocol - [ConnMgr.py:49]: ('127.0.0.1', 9100) is connected !!!!
2021-07-04 21:04:57,835 - INFO - TcpProtocol - [ConnMgr.py:49]: ('127.0.0.1', 9100) is connected !!!!
2021-07-04 21:10:33,374 - INFO - TcpProtocol - [ConnMgr.py:51]: ('127.0.0.1', 9100) is connected !!!!
2021-07-04 21:14:00,184 - INFO - TcpProtocol - [ConnMgr.py:52]: ('127.0.0.1', 9100) is connected !!!!
2021-07-04 21:14:00,191 - WARNING - RpcHandler - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RpcHandler.py:79"]: self.rpc_handler_id=b'`\xe1\xb4\x181W\x9f]\xcb@\xfaJ' RpcHandler Destroy!
2021-07-04 21:14:00,192 - DEBUG - __main__ - [TcpClient2.py:84]: lobby server info: ('gate_0', '127.0.0.1', 9201)
2021-07-04 21:14:00,194 - INFO - ServerEntity.Avatar - [ServerEntity.py:25]: __init__ create entity Avatar with id 60e1b41831579f5dcb40fa4b mem_id=2352596684464
2021-07-04 21:14:00,196 - INFO - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60e1b41831579f5dcb40fa4b 
2021-07-04 21:14:00,199 - INFO - TcpProtocol - [ConnMgr.py:52]: ('127.0.0.1', 9201) is connected !!!!
2021-07-04 22:29:54,866 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:69"]: try reconnect rudp: ('127.0.0.1', 9102) ... 1
2021-07-04 22:29:55,499 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:69"]: try reconnect rudp: ('127.0.0.1', 9102) ... 2
2021-07-04 22:29:56,109 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:69"]: try reconnect rudp: ('127.0.0.1', 9102) ... 3
2021-07-04 22:29:56,715 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:69"]: try reconnect rudp: ('127.0.0.1', 9102) ... 4
2021-07-04 22:29:57,322 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:69"]: try reconnect rudp: ('127.0.0.1', 9102) ... 5
2021-07-04 22:29:57,930 - WARNING - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:69"]: try reconnect rudp: ('127.0.0.1', 9102) ... 6
2021-07-04 22:29:57,931 - ERROR - RudpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RudpConn.py:78"]: try 6 times , still can't connect rudp remote addr: ('127.0.0.1', 9102)
2021-07-04 22:39:30,548 - INFO - TcpProtocol - [ConnMgr.py:52]: TCP ('127.0.0.1', 9100) is connected !!!!
2021-07-04 22:39:30,554 - WARNING - RpcHandler - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RpcHandler.py:83"]: self.rpc_handler_id=b'`\xe1\xc8"1\xdd?h\xc4<=\xb2' RpcHandler Destroy!
2021-07-04 22:39:30,554 - DEBUG - __main__ - [TcpClient2.py:84]: lobby server info: ('gate_0', '127.0.0.1', 9201)
2021-07-04 22:39:30,556 - INFO - ServerEntity.Avatar - [ServerEntity.py:25]: __init__ create entity Avatar with id 60e1c82231dd3f68c43c3db3 mem_id=2025900278352
2021-07-04 22:39:30,557 - INFO - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60e1c82231dd3f68c43c3db3 
2021-07-04 22:39:30,561 - INFO - TcpProtocol - [ConnMgr.py:52]: TCP ('127.0.0.1', 9201) is connected !!!!
2021-07-04 22:39:48,266 - ERROR - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:54"]: [WinError 1225] The remote computer refused the network connection
2021-07-04 22:39:48,884 - WARNING - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:57"]: try reconnect tcp: ('127.0.0.1', 9101) ... 1
2021-07-04 22:39:50,939 - ERROR - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:54"]: [WinError 1225] The remote computer refused the network connection
2021-07-04 22:39:51,544 - WARNING - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:57"]: try reconnect tcp: ('127.0.0.1', 9101) ... 2
2021-07-04 22:39:53,597 - ERROR - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:54"]: [WinError 1225] The remote computer refused the network connection
2021-07-04 22:39:54,202 - WARNING - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:57"]: try reconnect tcp: ('127.0.0.1', 9101) ... 3
2021-07-04 22:39:56,255 - ERROR - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:54"]: [WinError 1225] The remote computer refused the network connection
2021-07-04 22:39:56,863 - WARNING - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:57"]: try reconnect tcp: ('127.0.0.1', 9101) ... 4
2021-07-04 22:39:58,918 - ERROR - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:54"]: [WinError 1225] The remote computer refused the network connection
2021-07-04 22:39:59,524 - WARNING - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:57"]: try reconnect tcp: ('127.0.0.1', 9101) ... 5
2021-07-04 22:40:01,581 - ERROR - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:54"]: [WinError 1225] The remote computer refused the network connection
2021-07-04 22:40:02,188 - WARNING - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:57"]: try reconnect tcp: ('127.0.0.1', 9101) ... 6
2021-07-04 22:40:02,189 - ERROR - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:65"]: try 6 times , still can't connect tcp remote addr: ('127.0.0.1', 9101)
2021-07-04 22:43:13,875 - ERROR - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:54"]: [WinError 1225] The remote computer refused the network connection
2021-07-04 22:43:14,490 - WARNING - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:57"]: try reconnect tcp: ('127.0.0.1', 9102) ... 1
2021-07-04 22:43:16,531 - ERROR - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:54"]: [WinError 1225] The remote computer refused the network connection
2021-07-04 22:43:17,138 - WARNING - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:57"]: try reconnect tcp: ('127.0.0.1', 9102) ... 2
2021-07-04 22:43:19,168 - ERROR - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:54"]: [WinError 1225] The remote computer refused the network connection
2021-07-04 22:43:19,778 - WARNING - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:57"]: try reconnect tcp: ('127.0.0.1', 9102) ... 3
2021-07-04 22:43:21,838 - ERROR - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:54"]: [WinError 1225] The remote computer refused the network connection
2021-07-04 22:43:22,459 - WARNING - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:57"]: try reconnect tcp: ('127.0.0.1', 9102) ... 4
2021-07-04 22:43:24,515 - ERROR - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:54"]: [WinError 1225] The remote computer refused the network connection
2021-07-04 22:43:25,123 - WARNING - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:57"]: try reconnect tcp: ('127.0.0.1', 9102) ... 5
2021-07-04 22:43:27,163 - ERROR - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:54"]: [WinError 1225] The remote computer refused the network connection
2021-07-04 22:43:27,772 - WARNING - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:57"]: try reconnect tcp: ('127.0.0.1', 9102) ... 6
2021-07-04 22:43:27,775 - ERROR - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:65"]: try 6 times , still can't connect tcp remote addr: ('127.0.0.1', 9102)
2021-07-04 22:43:42,835 - INFO - TcpProtocol - [ConnMgr.py:52]: TCP ('127.0.0.1', 9100) is connected !!!!
2021-07-04 22:43:42,840 - WARNING - RpcHandler - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RpcHandler.py:83"]: self.rpc_handler_id=b'`\xe1\xc9\x1e\x08\xc4\xdd$S\x1a\\-' RpcHandler Destroy!
2021-07-04 22:43:42,841 - DEBUG - __main__ - [TcpClient2.py:84]: lobby server info: ('gate_0', '127.0.0.1', 9201)
2021-07-04 22:43:42,843 - INFO - ServerEntity.Avatar - [ServerEntity.py:25]: __init__ create entity Avatar with id 60e1c91e08c4dd24531a5c2e mem_id=2510344094720
2021-07-04 22:43:42,845 - INFO - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60e1c91e08c4dd24531a5c2e 
2021-07-04 22:43:42,849 - INFO - TcpProtocol - [ConnMgr.py:52]: TCP ('127.0.0.1', 9201) is connected !!!!
2021-07-04 22:46:49,915 - ERROR - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:54"]: [WinError 1225] The remote computer refused the network connection
2021-07-04 22:46:50,522 - WARNING - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:57"]: try reconnect tcp: ('127.0.0.1', 9101) ... 1
2021-07-04 22:46:50,848 - ERROR - __main__ - ["C:/Users/b/Documents/github/realtime-server/pycharm2020.1.3/script/client/TcpClient2.py:73"]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_gate'], rpc_fuc_kwargs={}"
2021-07-04 22:46:52,574 - ERROR - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:54"]: [WinError 1225] The remote computer refused the network connection
2021-07-04 22:46:53,186 - WARNING - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:57"]: try reconnect tcp: ('127.0.0.1', 9101) ... 2
2021-07-04 22:46:53,857 - ERROR - __main__ - ["C:/Users/b/Documents/github/realtime-server/pycharm2020.1.3/script/client/TcpClient2.py:73"]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_gate'], rpc_fuc_kwargs={}"
2021-07-04 22:46:55,228 - ERROR - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:54"]: [WinError 1225] The remote computer refused the network connection
2021-07-04 22:46:55,838 - WARNING - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:57"]: try reconnect tcp: ('127.0.0.1', 9101) ... 3
2021-07-04 22:46:56,882 - ERROR - __main__ - ["C:/Users/b/Documents/github/realtime-server/pycharm2020.1.3/script/client/TcpClient2.py:73"]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_gate'], rpc_fuc_kwargs={}"
2021-07-04 22:46:57,891 - ERROR - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:54"]: [WinError 1225] The remote computer refused the network connection
2021-07-04 22:46:58,501 - WARNING - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:57"]: try reconnect tcp: ('127.0.0.1', 9101) ... 4
2021-07-04 22:46:59,884 - ERROR - __main__ - ["C:/Users/b/Documents/github/realtime-server/pycharm2020.1.3/script/client/TcpClient2.py:73"]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_gate'], rpc_fuc_kwargs={}"
2021-07-04 22:47:00,554 - ERROR - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:54"]: [WinError 1225] The remote computer refused the network connection
2021-07-04 22:47:01,162 - WARNING - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:57"]: try reconnect tcp: ('127.0.0.1', 9101) ... 5
2021-07-04 22:47:02,888 - ERROR - __main__ - ["C:/Users/b/Documents/github/realtime-server/pycharm2020.1.3/script/client/TcpClient2.py:73"]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_gate'], rpc_fuc_kwargs={}"
2021-07-04 22:47:03,212 - ERROR - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:54"]: [WinError 1225] The remote computer refused the network connection
2021-07-04 22:47:03,822 - WARNING - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:57"]: try reconnect tcp: ('127.0.0.1', 9101) ... 6
2021-07-04 22:47:03,824 - ERROR - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:65"]: try 6 times , still can't connect tcp remote addr: ('127.0.0.1', 9101)
2021-07-04 22:47:05,915 - ERROR - __main__ - ["C:/Users/b/Documents/github/realtime-server/pycharm2020.1.3/script/client/TcpClient2.py:73"]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_gate'], rpc_fuc_kwargs={}"
2021-07-04 22:59:28,837 - ERROR - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:54"]: [WinError 1225] The remote computer refused the network connection
2021-07-04 22:59:29,444 - WARNING - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:57"]: try reconnect tcp: ('127.0.0.1', 9101) ... 1
2021-07-04 22:59:29,772 - ERROR - __main__ - ["C:/Users/b/Documents/github/realtime-server/pycharm2020.1.3/script/client/TcpClient2.py:73"]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_gate'], rpc_fuc_kwargs={}"
2021-07-04 22:59:31,499 - ERROR - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:54"]: [WinError 1225] The remote computer refused the network connection
2021-07-04 22:59:32,107 - WARNING - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:57"]: try reconnect tcp: ('127.0.0.1', 9101) ... 2
2021-07-04 22:59:32,797 - ERROR - __main__ - ["C:/Users/b/Documents/github/realtime-server/pycharm2020.1.3/script/client/TcpClient2.py:73"]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_gate'], rpc_fuc_kwargs={}"
2021-07-04 22:59:34,152 - ERROR - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:54"]: [WinError 1225] The remote computer refused the network connection
2021-07-04 22:59:34,759 - WARNING - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:57"]: try reconnect tcp: ('127.0.0.1', 9101) ... 3
2021-07-04 22:59:35,818 - ERROR - __main__ - ["C:/Users/b/Documents/github/realtime-server/pycharm2020.1.3/script/client/TcpClient2.py:73"]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_gate'], rpc_fuc_kwargs={}"
2021-07-04 22:59:36,811 - ERROR - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:54"]: [WinError 1225] The remote computer refused the network connection
2021-07-04 22:59:37,425 - WARNING - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:57"]: try reconnect tcp: ('127.0.0.1', 9101) ... 4
2021-07-04 22:59:38,825 - ERROR - __main__ - ["C:/Users/b/Documents/github/realtime-server/pycharm2020.1.3/script/client/TcpClient2.py:73"]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_gate'], rpc_fuc_kwargs={}"
2021-07-04 22:59:39,476 - ERROR - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:54"]: [WinError 1225] The remote computer refused the network connection
2021-07-04 22:59:40,084 - WARNING - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:57"]: try reconnect tcp: ('127.0.0.1', 9101) ... 5
2021-07-04 22:59:41,843 - ERROR - __main__ - ["C:/Users/b/Documents/github/realtime-server/pycharm2020.1.3/script/client/TcpClient2.py:73"]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_gate'], rpc_fuc_kwargs={}"
2021-07-04 22:59:42,140 - ERROR - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:54"]: [WinError 1225] The remote computer refused the network connection
2021-07-04 22:59:42,745 - WARNING - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:57"]: try reconnect tcp: ('127.0.0.1', 9101) ... 6
2021-07-04 22:59:42,746 - ERROR - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:65"]: try 6 times , still can't connect tcp remote addr: ('127.0.0.1', 9101)
2021-07-04 22:59:44,865 - ERROR - __main__ - ["C:/Users/b/Documents/github/realtime-server/pycharm2020.1.3/script/client/TcpClient2.py:73"]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_gate'], rpc_fuc_kwargs={}"
2021-07-04 23:01:59,173 - INFO - TcpProtocol - [ConnMgr.py:52]: TCP ('127.0.0.1', 9100) is connected !!!!
2021-07-04 23:02:08,806 - ERROR - __main__ - ["C:/Users/b/Documents/github/realtime-server/pycharm2020.1.3/script/client/TcpClient2.py:73"]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_gate'], rpc_fuc_kwargs={}"
2021-07-04 23:02:18,171 - ERROR - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:54"]: [WinError 1225] The remote computer refused the network connection
2021-07-04 23:02:18,778 - WARNING - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:57"]: try reconnect tcp: ('127.0.0.1', 9101) ... 1
2021-07-04 23:02:24,434 - ERROR - __main__ - ["C:/Users/b/Documents/github/realtime-server/pycharm2020.1.3/script/client/TcpClient2.py:73"]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_gate'], rpc_fuc_kwargs={}"
2021-07-04 23:02:24,443 - ERROR - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:54"]: [WinError 1225] The remote computer refused the network connection
2021-07-04 23:02:34,882 - WARNING - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:57"]: try reconnect tcp: ('127.0.0.1', 9101) ... 2
2021-07-04 23:02:34,888 - ERROR - __main__ - ["C:/Users/b/Documents/github/realtime-server/pycharm2020.1.3/script/client/TcpClient2.py:73"]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_gate'], rpc_fuc_kwargs={}"
2021-07-04 23:02:36,938 - ERROR - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:54"]: [WinError 1225] The remote computer refused the network connection
2021-07-04 23:02:37,546 - WARNING - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:57"]: try reconnect tcp: ('127.0.0.1', 9101) ... 3
2021-07-04 23:02:37,908 - ERROR - __main__ - ["C:/Users/b/Documents/github/realtime-server/pycharm2020.1.3/script/client/TcpClient2.py:73"]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_gate'], rpc_fuc_kwargs={}"
2021-07-04 23:02:39,604 - ERROR - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:54"]: [WinError 1225] The remote computer refused the network connection
2021-07-04 23:02:40,214 - WARNING - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:57"]: try reconnect tcp: ('127.0.0.1', 9101) ... 4
2021-07-04 23:02:40,931 - ERROR - __main__ - ["C:/Users/b/Documents/github/realtime-server/pycharm2020.1.3/script/client/TcpClient2.py:73"]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_gate'], rpc_fuc_kwargs={}"
2021-07-04 23:02:42,267 - ERROR - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:54"]: [WinError 1225] The remote computer refused the network connection
2021-07-04 23:02:42,873 - WARNING - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:57"]: try reconnect tcp: ('127.0.0.1', 9101) ... 5
2021-07-04 23:02:43,935 - ERROR - __main__ - ["C:/Users/b/Documents/github/realtime-server/pycharm2020.1.3/script/client/TcpClient2.py:73"]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_gate'], rpc_fuc_kwargs={}"
2021-07-04 23:02:44,929 - ERROR - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:54"]: [WinError 1225] The remote computer refused the network connection
2021-07-04 23:02:45,537 - WARNING - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:57"]: try reconnect tcp: ('127.0.0.1', 9101) ... 6
2021-07-04 23:02:45,540 - ERROR - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:65"]: try 6 times , still can't connect tcp remote addr: ('127.0.0.1', 9101)
2021-07-04 23:04:51,574 - ERROR - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:54"]: [WinError 1225] The remote computer refused the network connection
2021-07-04 23:04:52,191 - WARNING - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:57"]: try reconnect tcp: ('127.0.0.1', 9102) ... 1
2021-07-04 23:04:52,476 - ERROR - __main__ - ["C:/Users/b/Documents/github/realtime-server/pycharm2020.1.3/script/client/TcpClient2.py:73"]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_gate'], rpc_fuc_kwargs={}"
2021-07-04 23:06:32,192 - ERROR - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:54"]: [WinError 1225] The remote computer refused the network connection
2021-07-04 23:06:32,197 - ERROR - __main__ - ["C:/Users/b/Documents/github/realtime-server/pycharm2020.1.3/script/client/TcpClient2.py:73"]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_gate'], rpc_fuc_kwargs={}"
2021-07-04 23:07:23,100 - WARNING - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:57"]: try reconnect tcp: ('127.0.0.1', 9102) ... 2
2021-07-04 23:07:23,105 - ERROR - __main__ - ["C:/Users/b/Documents/github/realtime-server/pycharm2020.1.3/script/client/TcpClient2.py:73"]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_gate'], rpc_fuc_kwargs={}"
2021-07-04 23:07:25,186 - ERROR - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:54"]: [WinError 1225] The remote computer refused the network connection
2021-07-04 23:07:25,793 - WARNING - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:57"]: try reconnect tcp: ('127.0.0.1', 9102) ... 3
2021-07-04 23:07:26,136 - ERROR - __main__ - ["C:/Users/b/Documents/github/realtime-server/pycharm2020.1.3/script/client/TcpClient2.py:73"]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_gate'], rpc_fuc_kwargs={}"
2021-07-04 23:07:33,563 - ERROR - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:54"]: [WinError 1225] The remote computer refused the network connection
2021-07-04 23:07:34,179 - WARNING - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:57"]: try reconnect tcp: ('127.0.0.1', 9101) ... 1
2021-07-04 23:07:34,493 - ERROR - __main__ - ["C:/Users/b/Documents/github/realtime-server/pycharm2020.1.3/script/client/TcpClient2.py:73"]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_gate'], rpc_fuc_kwargs={}"
2021-07-04 23:07:36,217 - ERROR - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:54"]: [WinError 1225] The remote computer refused the network connection
2021-07-04 23:07:36,823 - WARNING - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:57"]: try reconnect tcp: ('127.0.0.1', 9101) ... 2
2021-07-04 23:07:37,512 - ERROR - __main__ - ["C:/Users/b/Documents/github/realtime-server/pycharm2020.1.3/script/client/TcpClient2.py:73"]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_gate'], rpc_fuc_kwargs={}"
2021-07-04 23:11:48,525 - ERROR - __main__ - ["C:/Users/b/Documents/github/realtime-server/pycharm2020.1.3/script/client/TcpClient2.py:73"]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_gate'], rpc_fuc_kwargs={}"
2021-07-04 23:11:51,532 - ERROR - __main__ - ["C:/Users/b/Documents/github/realtime-server/pycharm2020.1.3/script/client/TcpClient2.py:73"]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_gate'], rpc_fuc_kwargs={}"
2021-07-04 23:11:54,551 - ERROR - __main__ - ["C:/Users/b/Documents/github/realtime-server/pycharm2020.1.3/script/client/TcpClient2.py:73"]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_gate'], rpc_fuc_kwargs={}"
2021-07-04 23:11:57,568 - ERROR - __main__ - ["C:/Users/b/Documents/github/realtime-server/pycharm2020.1.3/script/client/TcpClient2.py:73"]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_gate'], rpc_fuc_kwargs={}"
2021-07-04 23:12:00,578 - ERROR - __main__ - ["C:/Users/b/Documents/github/realtime-server/pycharm2020.1.3/script/client/TcpClient2.py:73"]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_gate'], rpc_fuc_kwargs={}"
2021-07-04 23:12:03,584 - ERROR - __main__ - ["C:/Users/b/Documents/github/realtime-server/pycharm2020.1.3/script/client/TcpClient2.py:73"]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_gate'], rpc_fuc_kwargs={}"
2021-07-04 23:12:24,307 - ERROR - __main__ - ["C:/Users/b/Documents/github/realtime-server/pycharm2020.1.3/script/client/TcpClient2.py:73"]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_gate'], rpc_fuc_kwargs={}"
2021-07-04 23:12:27,314 - ERROR - __main__ - ["C:/Users/b/Documents/github/realtime-server/pycharm2020.1.3/script/client/TcpClient2.py:73"]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_gate'], rpc_fuc_kwargs={}"
2021-07-04 23:12:30,324 - ERROR - __main__ - ["C:/Users/b/Documents/github/realtime-server/pycharm2020.1.3/script/client/TcpClient2.py:73"]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_gate'], rpc_fuc_kwargs={}"
2021-07-04 23:14:29,633 - INFO - TcpProtocol - [ConnMgr.py:52]: TCP ('127.0.0.1', 9100) is connected !!!!
2021-07-04 23:14:29,639 - WARNING - RpcHandler - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RpcHandler.py:83"]: self.rpc_handler_id=b'`\xe1\xd0U\xcc8J\nQ\x1bw\xb1' RpcHandler Destroy!
2021-07-04 23:14:29,640 - DEBUG - __main__ - [TcpClient2.py:84]: lobby server info: ('gate_0', '127.0.0.1', 9201)
2021-07-04 23:14:29,641 - INFO - ServerEntity.Avatar - [ServerEntity.py:25]: __init__ create entity Avatar with id 60e1d055cc384a0a511b77b2 mem_id=2075823050816
2021-07-04 23:14:29,644 - INFO - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60e1d055cc384a0a511b77b2 
2021-07-04 23:14:29,649 - INFO - TcpProtocol - [ConnMgr.py:52]: TCP ('127.0.0.1', 9201) is connected !!!!
2021-07-04 23:16:31,662 - INFO - TcpProtocol - [ConnMgr.py:52]: TCP ('127.0.0.1', 9100) is connected !!!!
2021-07-04 23:16:50,662 - ERROR - __main__ - ["C:/Users/b/Documents/github/realtime-server/pycharm2020.1.3/script/client/TcpClient2.py:73"]: _err="request rpc timeout, rpc_fuc_name='pick_lowest_load_service_addr', rpc_fuc_args=['lobby_gate'], rpc_fuc_kwargs={}"
2021-07-04 23:18:17,334 - WARNING - RpcHandler - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RpcHandler.py:83"]: self.rpc_handler_id=b'`\xe1\xd0\xc3\xeb\xfe\x1f\xf4arr\xf8' RpcHandler Destroy!
2021-07-04 23:18:17,337 - DEBUG - __main__ - [TcpClient2.py:84]: lobby server info: ('gate_0', '127.0.0.1', 9201)
2021-07-04 23:18:17,340 - INFO - ServerEntity.Avatar - [ServerEntity.py:25]: __init__ create entity Avatar with id 60e1d139ebfe1ff4617272f9 mem_id=1583185073536
2021-07-04 23:18:17,345 - INFO - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60e1d139ebfe1ff4617272f9 
2021-07-04 23:18:18,796 - INFO - TcpProtocol - [ConnMgr.py:52]: TCP ('127.0.0.1', 9201) is connected !!!!
2021-07-04 23:18:37,226 - INFO - TcpProtocol - [ConnMgr.py:52]: TCP ('127.0.0.1', 9100) is connected !!!!
2021-07-04 23:18:37,233 - WARNING - RpcHandler - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RpcHandler.py:83"]: self.rpc_handler_id=b'`\xe1\xd1M\xaaPWB\x19gn\xa1' RpcHandler Destroy!
2021-07-04 23:18:37,234 - DEBUG - __main__ - [TcpClient2.py:84]: lobby server info: ('gate_0', '127.0.0.1', 9201)
2021-07-04 23:18:37,236 - INFO - ServerEntity.Avatar - [ServerEntity.py:25]: __init__ create entity Avatar with id 60e1d14daa50574219676ea2 mem_id=2052809816000
2021-07-04 23:18:37,238 - INFO - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60e1d14daa50574219676ea2 
2021-07-04 23:18:37,244 - INFO - TcpProtocol - [ConnMgr.py:52]: TCP ('127.0.0.1', 9201) is connected !!!!
2021-07-04 23:19:10,994 - INFO - TcpProtocol - [ConnMgr.py:52]: TCP ('127.0.0.1', 9100) is connected !!!!
2021-07-04 23:19:11,001 - WARNING - RpcHandler - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RpcHandler.py:83"]: self.rpc_handler_id=b'`\xe1\xd1n\x0c\x87\xae\x8f|\x8b7\x01' RpcHandler Destroy!
2021-07-04 23:19:11,002 - DEBUG - __main__ - [TcpClient2.py:84]: lobby server info: ('gate_0', '127.0.0.1', 9201)
2021-07-04 23:19:11,004 - INFO - ServerEntity.Avatar - [ServerEntity.py:25]: __init__ create entity Avatar with id 60e1d16f0c87ae8f7c8b3702 mem_id=1956807832768
2021-07-04 23:19:11,006 - INFO - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60e1d16f0c87ae8f7c8b3702 
2021-07-04 23:19:11,009 - INFO - TcpProtocol - [ConnMgr.py:52]: TCP ('127.0.0.1', 9201) is connected !!!!
2021-07-04 23:19:19,916 - INFO - TcpProtocol - [ConnMgr.py:52]: TCP ('127.0.0.1', 9100) is connected !!!!
2021-07-04 23:19:19,922 - WARNING - RpcHandler - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RpcHandler.py:83"]: self.rpc_handler_id=b'`\xe1\xd1w`\xc0\xc1\xa0\x05\x18\xce\xfe' RpcHandler Destroy!
2021-07-04 23:19:19,924 - DEBUG - __main__ - [TcpClient2.py:84]: lobby server info: ('gate_0', '127.0.0.1', 9201)
2021-07-04 23:19:19,925 - INFO - ServerEntity.Avatar - [ServerEntity.py:25]: __init__ create entity Avatar with id 60e1d17760c0c1a00518ceff mem_id=2292435122160
2021-07-04 23:19:19,927 - INFO - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60e1d17760c0c1a00518ceff 
2021-07-04 23:19:19,931 - INFO - TcpProtocol - [ConnMgr.py:52]: TCP ('127.0.0.1', 9201) is connected !!!!
2021-07-04 23:19:34,026 - INFO - TcpProtocol - [ConnMgr.py:52]: TCP ('127.0.0.1', 9100) is connected !!!!
2021-07-04 23:19:34,031 - WARNING - RpcHandler - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RpcHandler.py:83"]: self.rpc_handler_id=b'`\xe1\xd1\x85Y9\xce\xa7\xf4\x9aT\xf9' RpcHandler Destroy!
2021-07-04 23:19:34,032 - DEBUG - __main__ - [TcpClient2.py:84]: lobby server info: ('gate_0', '127.0.0.1', 9201)
2021-07-04 23:19:34,034 - INFO - ServerEntity.Avatar - [ServerEntity.py:25]: __init__ create entity Avatar with id 60e1d1865939cea7f49a54fa mem_id=1830891161488
2021-07-04 23:19:34,037 - INFO - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60e1d1865939cea7f49a54fa 
2021-07-04 23:19:34,042 - INFO - TcpProtocol - [ConnMgr.py:52]: TCP ('127.0.0.1', 9201) is connected !!!!
2021-07-04 23:19:39,830 - INFO - TcpProtocol - [ConnMgr.py:52]: TCP ('127.0.0.1', 9100) is connected !!!!
2021-07-04 23:19:39,838 - WARNING - RpcHandler - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RpcHandler.py:83"]: self.rpc_handler_id=b'`\xe1\xd1\x8b\xbb\x05\x84Cq\xe6A@' RpcHandler Destroy!
2021-07-04 23:19:39,840 - DEBUG - __main__ - [TcpClient2.py:84]: lobby server info: ('gate_0', '127.0.0.1', 9201)
2021-07-04 23:19:39,843 - INFO - ServerEntity.Avatar - [ServerEntity.py:25]: __init__ create entity Avatar with id 60e1d18bbb05844371e64141 mem_id=1847867602832
2021-07-04 23:19:39,844 - INFO - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60e1d18bbb05844371e64141 
2021-07-04 23:19:39,849 - INFO - TcpProtocol - [ConnMgr.py:52]: TCP ('127.0.0.1', 9201) is connected !!!!
2021-07-04 23:22:32,967 - INFO - TcpProtocol - [ConnMgr.py:52]: TCP ('127.0.0.1', 9100) is connected !!!!
2021-07-04 23:22:32,972 - WARNING - RpcHandler - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RpcHandler.py:83"]: self.rpc_handler_id=b'`\xe1\xd28\x93\x94h\xa4\x983b\xbe' RpcHandler Destroy!
2021-07-04 23:22:32,973 - DEBUG - __main__ - [TcpClient2.py:84]: lobby server info: ('gate_0', '127.0.0.1', 9201)
2021-07-04 23:22:32,975 - INFO - ServerEntity.Avatar - [ServerEntity.py:25]: __init__ create entity Avatar with id 60e1d238939468a4983362bf mem_id=1984531724176
2021-07-04 23:22:32,976 - INFO - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60e1d238939468a4983362bf 
2021-07-04 23:22:32,982 - INFO - TcpProtocol - [ConnMgr.py:52]: TCP ('127.0.0.1', 9201) is connected !!!!
2021-07-04 23:22:37,547 - INFO - TcpProtocol - [ConnMgr.py:52]: TCP ('127.0.0.1', 9100) is connected !!!!
2021-07-04 23:22:37,553 - WARNING - RpcHandler - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RpcHandler.py:83"]: self.rpc_handler_id=b"`\xe1\xd2=\x98'i\xa6\x0brm\xa3" RpcHandler Destroy!
2021-07-04 23:22:37,555 - DEBUG - __main__ - [TcpClient2.py:84]: lobby server info: ('gate_0', '127.0.0.1', 9201)
2021-07-04 23:22:37,556 - INFO - ServerEntity.Avatar - [ServerEntity.py:25]: __init__ create entity Avatar with id 60e1d23d982769a60b726da4 mem_id=2379906611040
2021-07-04 23:22:37,558 - INFO - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60e1d23d982769a60b726da4 
2021-07-04 23:22:37,563 - INFO - TcpProtocol - [ConnMgr.py:52]: TCP ('127.0.0.1', 9201) is connected !!!!
2021-07-04 23:23:15,451 - INFO - TcpProtocol - [ConnMgr.py:52]: TCP ('127.0.0.1', 9100) is connected !!!!
2021-07-04 23:23:15,456 - WARNING - RpcHandler - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RpcHandler.py:83"]: self.rpc_handler_id=b'`\xe1\xd2cJ\xbb\xa9\tTO\x87\t' RpcHandler Destroy!
2021-07-04 23:23:15,457 - DEBUG - __main__ - [TcpClient2.py:84]: lobby server info: ('gate_0', '127.0.0.1', 9201)
2021-07-04 23:23:15,459 - INFO - ServerEntity.Avatar - [ServerEntity.py:25]: __init__ create entity Avatar with id 60e1d2634abba909544f870a mem_id=2803339494592
2021-07-04 23:23:15,461 - INFO - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60e1d2634abba909544f870a 
2021-07-04 23:23:15,465 - INFO - TcpProtocol - [ConnMgr.py:52]: TCP ('127.0.0.1', 9201) is connected !!!!
2021-07-04 23:35:01,080 - WARNING - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\ConnBase.py:192"]: peer addr: ('127.0.0.1', 9100), close_reason='[WinError 64] The specified network name is no longer available'
2021-07-04 23:35:11,608 - WARNING - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\ConnBase.py:192"]: peer addr: ('127.0.0.1', 9201), close_reason='[WinError 64] The specified network name is no longer available'
2021-07-04 23:35:38,691 - INFO - TcpProtocol - [ConnMgr.py:52]: TCP ('127.0.0.1', 9100) is connected !!!!
2021-07-04 23:35:38,697 - WARNING - RpcHandler - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RpcHandler.py:83"]: self.rpc_handler_id=b'`\xe1\xd5J\xb9\xbb\xf0\x97-_\xcd\xbf' RpcHandler Destroy!
2021-07-04 23:35:38,697 - DEBUG - __main__ - [TcpClient2.py:84]: lobby server info: ('gate_0', '127.0.0.1', 9201)
2021-07-04 23:35:38,699 - INFO - ServerEntity.Avatar - [ServerEntity.py:25]: __init__ create entity Avatar with id 60e1d54ab9bbf0972d5fcdc0 mem_id=2227301053632
2021-07-04 23:35:38,700 - INFO - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60e1d54ab9bbf0972d5fcdc0 
2021-07-04 23:35:38,704 - INFO - TcpProtocol - [ConnMgr.py:52]: TCP ('127.0.0.1', 9201) is connected !!!!
2021-07-04 23:37:39,812 - INFO - TcpProtocol - [ConnMgr.py:52]: TCP ('127.0.0.1', 9100) is connected !!!!
2021-07-04 23:37:39,818 - WARNING - RpcHandler - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RpcHandler.py:83"]: self.rpc_handler_id=b'`\xe1\xd5\xc3\xf0\xd9Eu\xdd4\xc9?' RpcHandler Destroy!
2021-07-04 23:37:39,819 - DEBUG - __main__ - [TcpClient2.py:84]: lobby server info: ('gate_0', '127.0.0.1', 9201)
2021-07-04 23:37:39,821 - INFO - ServerEntity.Avatar - [ServerEntity.py:25]: __init__ create entity Avatar with id 60e1d5c3f0d94575dd34c940 mem_id=2691918393792
2021-07-04 23:37:39,822 - INFO - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60e1d5c3f0d94575dd34c940 
2021-07-04 23:37:39,826 - INFO - TcpProtocol - [ConnMgr.py:52]: TCP ('127.0.0.1', 9201) is connected !!!!
2021-07-04 23:39:04,861 - INFO - TcpProtocol - [ConnMgr.py:52]: TCP ('127.0.0.1', 9100) is connected !!!!
2021-07-04 23:39:04,868 - WARNING - RpcHandler - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RpcHandler.py:83"]: self.rpc_handler_id=b'`\xe1\xd6\x18q\x9b\x9e\xe4\x0c\xca\xc22' RpcHandler Destroy!
2021-07-04 23:39:04,869 - DEBUG - __main__ - [TcpClient2.py:84]: lobby server info: ('gate_0', '127.0.0.1', 9201)
2021-07-04 23:39:04,871 - INFO - ServerEntity.Avatar - [ServerEntity.py:25]: __init__ create entity Avatar with id 60e1d618719b9ee40ccac233 mem_id=1475939337264
2021-07-04 23:39:04,872 - INFO - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60e1d618719b9ee40ccac233 
2021-07-04 23:39:04,876 - INFO - TcpProtocol - [ConnMgr.py:52]: TCP ('127.0.0.1', 9201) is connected !!!!
2021-07-04 23:39:19,601 - INFO - TcpProtocol - [ConnMgr.py:52]: TCP ('127.0.0.1', 9100) is connected !!!!
2021-07-04 23:39:19,607 - WARNING - RpcHandler - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RpcHandler.py:83"]: self.rpc_handler_id=b"`\xe1\xd6'\x84\x16\xaa\xe1\x1b\xf7\xfb\xc9" RpcHandler Destroy!
2021-07-04 23:39:19,608 - DEBUG - __main__ - [TcpClient2.py:84]: lobby server info: ('gate_0', '127.0.0.1', 9201)
2021-07-04 23:39:19,609 - INFO - ServerEntity.Avatar - [ServerEntity.py:25]: __init__ create entity Avatar with id 60e1d6278416aae11bf7fbca mem_id=1310327244832
2021-07-04 23:39:19,611 - INFO - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60e1d6278416aae11bf7fbca 
2021-07-04 23:39:19,616 - INFO - TcpProtocol - [ConnMgr.py:52]: TCP ('127.0.0.1', 9201) is connected !!!!
2021-07-04 23:40:00,558 - INFO - TcpProtocol - [ConnMgr.py:52]: TCP ('127.0.0.1', 9100) is connected !!!!
2021-07-04 23:40:00,564 - WARNING - RpcHandler - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RpcHandler.py:83"]: self.rpc_handler_id=b'`\xe1\xd6P\xbel\xa6>:Dj\xc1' RpcHandler Destroy!
2021-07-04 23:40:00,565 - DEBUG - __main__ - [TcpClient2.py:84]: lobby server info: ('gate_0', '127.0.0.1', 9201)
2021-07-04 23:40:00,566 - INFO - ServerEntity.Avatar - [ServerEntity.py:25]: __init__ create entity Avatar with id 60e1d650be6ca63e3a446ac2 mem_id=2017634546784
2021-07-04 23:40:00,568 - INFO - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60e1d650be6ca63e3a446ac2 
2021-07-04 23:40:00,573 - INFO - TcpProtocol - [ConnMgr.py:52]: TCP ('127.0.0.1', 9201) is connected !!!!
2021-07-04 23:40:20,719 - INFO - TcpProtocol - [ConnMgr.py:52]: TCP ('127.0.0.1', 9100) is connected !!!!
2021-07-04 23:40:20,726 - WARNING - RpcHandler - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RpcHandler.py:83"]: self.rpc_handler_id=b'`\xe1\xd6d\xd7\xc6\xb0\xd2\\H\x8d\x00' RpcHandler Destroy!
2021-07-04 23:40:20,727 - DEBUG - __main__ - [TcpClient2.py:84]: lobby server info: ('gate_0', '127.0.0.1', 9201)
2021-07-04 23:40:20,729 - INFO - ServerEntity.Avatar - [ServerEntity.py:25]: __init__ create entity Avatar with id 60e1d664d7c6b0d25c488d01 mem_id=1443558191888
2021-07-04 23:40:20,730 - INFO - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60e1d664d7c6b0d25c488d01 
2021-07-04 23:40:20,735 - INFO - TcpProtocol - [ConnMgr.py:52]: TCP ('127.0.0.1', 9201) is connected !!!!
2021-07-04 23:47:53,598 - INFO - TcpProtocol - [ConnMgr.py:53]: TCP ROLE_TYPE_ACTIVE ('127.0.0.1', 9100) is connected !!!!
2021-07-04 23:47:53,600 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9100)
2021-07-04 23:47:53,603 - WARNING - RpcHandler - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RpcHandler.py:83"]: self.rpc_handler_id=b'`\xe1\xd8)6\xb9\xa0fp`\xf3}' RpcHandler Destroy!
2021-07-04 23:47:53,604 - DEBUG - __main__ - [TcpClient2.py:84]: lobby server info: ('gate_0', '127.0.0.1', 9201)
2021-07-04 23:47:53,606 - INFO - ServerEntity.Avatar - [ServerEntity.py:25]: __init__ create entity Avatar with id 60e1d82936b9a0667060f37e mem_id=2073297032336
2021-07-04 23:47:53,607 - INFO - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60e1d82936b9a0667060f37e 
2021-07-04 23:47:53,612 - INFO - TcpProtocol - [ConnMgr.py:53]: TCP ROLE_TYPE_ACTIVE ('127.0.0.1', 9201) is connected !!!!
2021-07-04 23:47:53,640 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9201)
2021-07-04 23:47:53,671 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9201)
2021-07-04 23:47:56,632 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9201)
2021-07-04 23:47:56,644 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9201)
2021-07-04 23:52:00,629 - INFO - TcpProtocol - [ConnMgr.py:53]: TCP ROLE_TYPE_ACTIVE peer_addr=('127.0.0.1', 9100) is connected !!!!
2021-07-04 23:52:00,632 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9100)
2021-07-04 23:52:00,635 - WARNING - RpcHandler - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RpcHandler.py:83"]: self.rpc_handler_id=b'`\xe1\xd9 V1\xb1!3z\x97\xd9' RpcHandler Destroy!
2021-07-04 23:52:00,636 - DEBUG - __main__ - [TcpClient2.py:84]: lobby server info: ('gate_0', '127.0.0.1', 9201)
2021-07-04 23:52:00,637 - INFO - ServerEntity.Avatar - [ServerEntity.py:25]: __init__ create entity Avatar with id 60e1d9205631b121337a97da mem_id=1360708674560
2021-07-04 23:52:00,639 - INFO - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60e1d9205631b121337a97da 
2021-07-04 23:52:00,643 - INFO - TcpProtocol - [ConnMgr.py:53]: TCP ROLE_TYPE_ACTIVE peer_addr=('127.0.0.1', 9201) is connected !!!!
2021-07-04 23:52:00,672 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9201)
2021-07-04 23:52:03,677 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9201)
2021-07-04 23:52:06,688 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9201)
2021-07-04 23:52:09,686 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9201)
2021-07-04 23:56:04,526 - INFO - TcpProtocol - [ConnMgr.py:53]: TCP ROLE_TYPE_ACTIVE peer_addr=('127.0.0.1', 9100) is connected !!!!
2021-07-04 23:56:04,528 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9100)
2021-07-04 23:56:04,533 - WARNING - RpcHandler - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RpcHandler.py:83"]: self.rpc_handler_id=b'`\xe1\xda\x14\x8e{\xa2\x08~Y-Q' RpcHandler Destroy!
2021-07-04 23:56:04,534 - DEBUG - __main__ - [TcpClient2.py:84]: lobby server info: ('gate_0', '127.0.0.1', 9201)
2021-07-04 23:56:04,535 - INFO - ServerEntity.Avatar - [ServerEntity.py:25]: __init__ create entity Avatar with id 60e1da148e7ba2087e592d52 mem_id=1674323948880
2021-07-04 23:56:04,536 - INFO - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60e1da148e7ba2087e592d52 
2021-07-04 23:56:04,541 - INFO - TcpProtocol - [ConnMgr.py:53]: TCP ROLE_TYPE_ACTIVE peer_addr=('127.0.0.1', 9201) is connected !!!!
2021-07-04 23:56:04,567 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9201)
2021-07-04 23:56:07,585 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9201)
2021-07-04 23:56:08,706 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9201)
2021-07-04 23:56:10,600 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9201)
2021-07-04 23:56:12,306 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9201)
2021-07-04 23:56:12,339 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9201)
2021-07-04 23:56:13,620 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9201)
2021-07-04 23:56:13,636 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9201)
2021-07-04 23:56:16,627 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9201)
2021-07-04 23:56:16,643 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9201)
2021-07-04 23:56:19,647 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9201)
2021-07-04 23:56:19,662 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9201)
2021-07-04 23:56:22,650 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9201)
2021-07-04 23:56:22,666 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9201)
2021-07-04 23:57:14,477 - INFO - TcpProtocol - [ConnMgr.py:53]: TCP ROLE_TYPE_ACTIVE peer_addr=('127.0.0.1', 9100) is connected !!!!
2021-07-04 23:57:14,479 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9100)
2021-07-04 23:57:14,483 - WARNING - RpcHandler - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RpcHandler.py:83"]: self.rpc_handler_id=b'`\xe1\xdaZ\xb5\x9b\x16\xa4P\xd7!\xe3' RpcHandler Destroy!
2021-07-04 23:57:14,484 - DEBUG - __main__ - [TcpClient2.py:84]: lobby server info: ('gate_0', '127.0.0.1', 9201)
2021-07-04 23:57:14,485 - INFO - ServerEntity.Avatar - [ServerEntity.py:25]: __init__ create entity Avatar with id 60e1da5ab59b16a450d721e4 mem_id=1950947275920
2021-07-04 23:57:14,486 - INFO - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60e1da5ab59b16a450d721e4 
2021-07-04 23:57:14,490 - INFO - TcpProtocol - [ConnMgr.py:53]: TCP ROLE_TYPE_ACTIVE peer_addr=('127.0.0.1', 9201) is connected !!!!
2021-07-04 23:57:14,522 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9201)
2021-07-04 23:57:17,530 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9201)
2021-07-04 23:57:20,530 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9201)
2021-07-04 23:57:23,535 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9201)
2021-07-04 23:57:26,557 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9201)
2021-07-04 23:57:29,560 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9201)
2021-07-04 23:57:32,567 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9201)
2021-07-04 23:57:35,593 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9201)
2021-07-04 23:57:38,598 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9201)
2021-07-04 23:57:41,612 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9201)
2021-07-04 23:57:44,639 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9201)
2021-07-04 23:57:47,643 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9201)
2021-07-04 23:57:50,665 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9201)
2021-07-04 23:57:53,670 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9201)
2021-07-04 23:57:56,676 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9201)
2021-07-04 23:57:59,683 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9201)
2021-07-04 23:58:02,688 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9201)
2021-07-04 23:58:05,687 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9201)
2021-07-04 23:58:08,688 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9201)
2021-07-04 23:58:11,714 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9201)
2021-07-04 23:58:14,716 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9201)
2021-07-04 23:58:17,720 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9201)
2021-07-04 23:58:20,736 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9201)
2021-07-04 23:58:23,752 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9201)
2021-07-04 23:58:26,770 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9201)
2021-07-04 23:58:29,778 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9201)
2021-07-04 23:58:32,785 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9201)
2021-07-04 23:58:35,808 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9201)
2021-07-04 23:58:38,816 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9201)
2021-07-04 23:58:41,840 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9201)
2021-07-04 23:58:44,856 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9201)
2021-07-04 23:58:47,863 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9201)
2021-07-04 23:58:50,882 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9201)
2021-07-04 23:58:53,892 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9201)
2021-07-04 23:58:56,896 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9201)
2021-07-04 23:58:59,916 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9201)
2021-07-04 23:59:02,918 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9201)
2021-07-04 23:59:05,920 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9201)
2021-07-04 23:59:08,921 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9201)
2021-07-04 23:59:11,931 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9201)
2021-07-04 23:59:14,949 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9201)
2021-07-04 23:59:17,954 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9201)
2021-07-04 23:59:20,959 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9201)
2021-07-04 23:59:23,969 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9201)
2021-07-04 23:59:26,963 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9201)
2021-07-04 23:59:29,975 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9201)
2021-07-04 23:59:32,997 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9201)
2021-07-04 23:59:35,998 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9201)
2021-07-04 23:59:39,005 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9201)
2021-07-04 23:59:42,021 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9201)
2021-07-04 23:59:45,036 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9201)
2021-07-04 23:59:48,043 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9201)
2021-07-04 23:59:51,047 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9201)
2021-07-04 23:59:54,054 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9201)
2021-07-04 23:59:57,068 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9201)
